<?php
namespace Digitalisimo\Tools;
defined( 'ABSPATH' ) || exit;
final class Media_WebP {
	const ACTION = 'digitalisimo_tools_webp_batch';
	public static function init() { add_action( 'admin_post_' . self::ACTION, array( __CLASS__, 'run' ) ); }
	public static function page() { if ( ! current_user_can( 'manage_network_options' ) ) return; echo '<h2>Optimizar imágenes WebP</h2><p>Convierte 20 JPEG o PNG por lote a WebP con calidad 75. Conserva el original y registra el resultado para una reversión segura.</p><form method="post" action="' . esc_url( network_admin_url( 'admin-post.php' ) ) . '">'; wp_nonce_field( self::ACTION ); echo '<input type="hidden" name="action" value="' . esc_attr( self::ACTION ) . '"><button class="button button-primary">Procesar lote</button></form>'; }
	public static function run() { if ( ! current_user_can( 'manage_network_options' ) ) wp_die( 'No autorizado.' ); check_admin_referer( self::ACTION ); $done = 0; foreach ( get_sites( array( 'number' => 0 ) ) as $site ) { switch_to_blog( $site->blog_id ); try { $ids = get_posts( array( 'post_type' => 'attachment', 'post_mime_type' => array( 'image/jpeg', 'image/png' ), 'posts_per_page' => 20 - $done, 'fields' => 'ids', 'meta_query' => array( array( 'key' => '_digitalisimo_tools_webp', 'compare' => 'NOT EXISTS' ) ) ) ); foreach ( $ids as $id ) { $file = get_attached_file( $id ); $editor = $file ? wp_get_image_editor( $file ) : new \WP_Error( 'missing' ); if ( is_wp_error( $editor ) ) continue; $editor->set_quality( 75 ); $saved = $editor->save( preg_replace( '/\.[^.]+$/', '.webp', $file ), 'image/webp' ); if ( ! is_wp_error( $saved ) ) update_post_meta( $id, '_digitalisimo_tools_webp', $saved['path'] ); if ( ++$done >= 20 ) break; } } finally { restore_current_blog(); } if ( $done >= 20 ) break; } wp_safe_redirect( network_admin_url( 'admin.php?page=digitalisimo-tools-elementor-templates&tab=webp&done=' . $done ) ); exit; }
}
