<?php
defined( 'ABSPATH' ) || exit;

/** Respaldo manual completo: base de datos, archivos y copia opcional remota. */
final class Digitalisimo_Backups {
	const OPTION = 'digitalisimo_backups_settings';
	const HISTORY = 'digitalisimo_backups_history';
	const ACTION_SAVE = 'digitalisimo_backups_save';
	const ACTION_RUN = 'digitalisimo_backups_run';
	const ACTION_OAUTH = 'digitalisimo_backups_oauth';
	const ACTION_LOCK = 'digitalisimo_backups_lock';
	const ACTION_DOWNLOAD = 'digitalisimo_backups_download';
	public static function init() { add_action( 'admin_post_' . self::ACTION_SAVE, array( __CLASS__, 'save' ) ); add_action( 'admin_post_' . self::ACTION_RUN, array( __CLASS__, 'run' ) ); add_action( 'admin_post_' . self::ACTION_OAUTH, array( __CLASS__, 'oauth_callback' ) ); add_action( 'admin_post_' . self::ACTION_LOCK, array( __CLASS__, 'toggle_lock' ) ); add_action( 'admin_post_' . self::ACTION_DOWNLOAD, array( __CLASS__, 'download' ) ); add_filter( 'cron_schedules', array( __CLASS__, 'cron_schedules' ) ); add_action( 'digitalisimo_backups_full', array( __CLASS__, 'scheduled_backup' ), 10, 1 ); add_action( 'digitalisimo_backups_db', array( __CLASS__, 'scheduled_backup' ), 10, 1 ); }
	private static function defaults() { return array( 'destination' => 'local', 'sftp_host' => '', 'sftp_port' => '22', 'sftp_user' => '', 'sftp_path' => '/', 'sftp_password' => '', 'google_client_id' => '', 'google_client_secret' => '', 'google_refresh_token' => '', 'google_folder_id' => '', 'onedrive_client_id' => '', 'onedrive_client_secret' => '', 'onedrive_refresh_token' => '', 'onedrive_folder' => 'Digitalisimo Backups', 'retention' => '5', 'full_schedule' => 'disabled', 'database_schedule' => 'disabled' ); }
	private static function local_directory() { return WP_PLUGIN_DIR . '/digitalisimo-backups-storage'; }
	/** Detecta y agrupa los archivos estándar de UpdraftPlus sin asumir que un ZIP aislado es restaurable. */
	public static function detect_updraft_sets( $directory = '' ) { $directory = $directory ?: WP_CONTENT_DIR . '/updraft'; $sets = array(); foreach ( glob( trailingslashit( $directory ) . 'backup_*' ) ?: array() as $path ) { $name = wp_basename( $path ); if ( ! preg_match( '/^(backup_[0-9-]{15}_.+?_[0-9a-f]{12})-(db|plugins|themes|uploads|others)([0-9]+)?\.(zip|gz)(?:\.crypt)?$/i', $name, $m ) ) continue; $key = $m[1]; if ( ! isset( $sets[ $key ] ) ) $sets[ $key ] = array( 'id' => $key, 'files' => array(), 'complete' => false ); $sets[ $key ]['files'][ strtolower( $m[2] ) ][] = array( 'path' => $path, 'part' => absint( $m[3] ), 'encrypted' => false !== strpos( $name, '.crypt' ) ); } foreach ( $sets as &$set ) { foreach ( $set['files'] as &$parts ) usort( $parts, function( $a, $b ) { return $a['part'] <=> $b['part']; } ); $set['complete'] = ! empty( $set['files']['db'] ) && ! array_filter( $set['files'], function( $parts ) { return array_filter( $parts, function( $part ) { return $part['encrypted']; } ); } ); } return $sets; }
	/** Rechaza piezas ausentes, cifradas o ilegibles antes de extraer cualquier archivo. */
	public static function validate_backup_set( $set ) { if ( empty( $set['complete'] ) || empty( $set['files']['db'] ) ) return new WP_Error( 'digitalisimo_backup_incomplete', 'El conjunto no incluye una base de datos legible o tiene piezas cifradas.' ); foreach ( $set['files'] as $parts ) foreach ( $parts as $part ) if ( ! is_readable( $part['path'] ) ) return new WP_Error( 'digitalisimo_backup_unreadable', 'Una pieza del respaldo no se puede leer.' ); return true; }
	private static function settings() { return wp_parse_args( (array) get_option( self::OPTION, array() ), self::defaults() ); }
	public static function cron_schedules( $schedules ) { $schedules['digitalisimo_every_6_hours'] = array( 'interval' => 6 * HOUR_IN_SECONDS, 'display' => 'Cada 6 horas' ); $schedules['digitalisimo_every_12_hours'] = array( 'interval' => 12 * HOUR_IN_SECONDS, 'display' => 'Cada 12 horas' ); return $schedules; }
	private static function schedule_options() { return array( 'disabled' => 'Desactivado', 'hourly' => 'Cada hora', 'digitalisimo_every_6_hours' => 'Cada 6 horas', 'digitalisimo_every_12_hours' => 'Cada 12 horas', 'daily' => 'Diario', 'weekly' => 'Semanal' ); }
	private static function sync_schedules( $settings ) { foreach ( array( 'full' => 'full_schedule', 'db' => 'database_schedule' ) as $type => $key ) { $hook = 'digitalisimo_backups_' . $type; wp_clear_scheduled_hook( $hook ); if ( 'disabled' !== $settings[ $key ] ) wp_schedule_event( time() + MINUTE_IN_SECONDS, $settings[ $key ], $hook, array( get_current_blog_id() ) ); } }
	public static function scheduled_backup( $site_id ) { if ( $site_id && get_current_blog_id() !== (int) $site_id && is_multisite() ) switch_to_blog( $site_id ); try { $type = current_filter() === 'digitalisimo_backups_db' ? 'database' : 'full'; $file = self::create_site( get_current_blog_id(), $type ); $s = self::settings(); if ( 'local' !== $s['destination'] ) self::transfer( $file, $s ); self::remember( $file, $s['destination'], 'site' ); self::prune( dirname( $file ), (int) $s['retention'] ); } catch ( Exception $e ) { error_log( 'Digitalisimo Backups: ' . $e->getMessage() ); } if ( $site_id && is_multisite() ) restore_current_blog(); }
	private static function can_manage() { return is_multisite() && is_network_admin() ? current_user_can( 'manage_network_options' ) : current_user_can( 'manage_options' ); }
	private static function admin_url() { return is_multisite() && is_network_admin() ? network_admin_url( 'admin.php?page=digitalisimo-network-backups' ) : admin_url( 'admin.php?page=digitalisimo-backups' ); }
	public static function page() { if ( ! self::can_manage() ) return; self::render( false ); }
	public static function network_page() { if ( ! self::can_manage() ) return; self::render( true ); }
	private static function secret_fields() { return array( 'sftp_password', 'google_client_secret', 'google_refresh_token', 'onedrive_client_secret', 'onedrive_refresh_token' ); }
	private static function render( $network ) {
		$s = self::settings(); $history = array_slice( (array) get_option( self::HISTORY, array() ), 0, 10 );
		echo '<div class="wrap digitalisimo-backups"><h1>Backups · Digitalisimo</h1><p>Genera un ZIP integral: archivos de WordPress, plugins, temas, medios y base de datos. El respaldo se crea primero en el hosting y después se copia al destino elegido.</p>';
		if ( isset( $_GET['backup'] ) ) echo '<div class="notice notice-' . ( 'ok' === $_GET['backup'] ? 'success' : 'error' ) . '"><p>' . esc_html( sanitize_text_field( wp_unslash( $_GET['message'] ?? '' ) ) ) . '</p></div>';
			echo '<div class="digitalisimo-backups-grid"><section class="digitalisimo-backups-card"><h2>' . ( $network ? 'Respaldos de la red' : 'Respaldar este sitio' ) . '</h2><p>Este proceso puede tardar según el tamaño de los archivos y la base de datos. No cierres esta pantalla mientras se genera.</p><form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '">'; wp_nonce_field( self::ACTION_RUN ); echo '<input type="hidden" name="action" value="' . esc_attr( self::ACTION_RUN ) . '"><input type="hidden" name="digitalisimo_backup_scope" value="' . ( $network ? 'network' : 'site' ) . '"><button class="button button-primary button-hero">' . ( $network ? 'Crear respaldo completo de la red' : 'Crear respaldo de este sitio' ) . '</button></form>';
			if ( $network ) { $sites = get_sites( array( 'number' => 0, 'orderby' => 'blog_id' ) ); echo '<hr><h3>Exportar un sitio como WordPress independiente</h3><p>Incluye sólo sus tablas, sus medios y los archivos comunes necesarios. El SQL usa el prefijo estándar <code>wp_</code> y el ZIP incluye instrucciones de migración.</p><form method="post" action="' . esc_url( network_admin_url( 'admin-post.php' ) ) . '">'; wp_nonce_field( self::ACTION_RUN ); echo '<input type="hidden" name="action" value="' . esc_attr( self::ACTION_RUN ) . '"><input type="hidden" name="digitalisimo_backup_scope" value="site"><select name="digitalisimo_backup_site">'; foreach ( $sites as $site ) echo '<option value="' . esc_attr( $site->blog_id ) . '">' . esc_html( $site->blog_id . ' · ' . $site->domain . $site->path ) . '</option>'; echo '</select> <button class="button button-secondary">Crear respaldo individual</button></form>'; }
			echo '<p class="description">Destino actual: <strong>' . esc_html( self::destination_label( $s['destination'] ) ) . '</strong></p></section><section class="digitalisimo-backups-card"><h2>Últimos respaldos</h2>';
			if ( ! $history ) echo '<p>Aún no hay respaldos creados.</p>'; else { echo '<table class="widefat striped"><thead><tr><th>Fecha</th><th>Archivo</th><th>Tipo</th><th>Tamaño</th><th>Destino</th><th>Protección</th></tr></thead><tbody>'; foreach ( $history as $item ) { echo '<tr><td>' . esc_html( $item['date'] ?? '' ) . '</td><td>' . esc_html( $item['file'] ?? '' ) . '</td><td>' . esc_html( ( $item['scope'] ?? 'site' ) === 'network' ? 'Red completa' : 'Sitio individual' ) . '</td><td>' . esc_html( size_format( (int) ( $item['size'] ?? 0 ) ) ) . '</td><td>' . esc_html( self::destination_label( $item['destination'] ?? 'local' ) ) . '</td><td><form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '">'; wp_nonce_field( self::ACTION_LOCK ); echo '<input type="hidden" name="action" value="' . esc_attr( self::ACTION_LOCK ) . '"><input type="hidden" name="file" value="' . esc_attr( $item['file'] ?? '' ) . '"><input type="hidden" name="locked" value="' . ( empty( $item['locked'] ) ? '1' : '0' ) . '"><button class="button button-small">' . ( empty( $item['locked'] ) ? 'Bloquear' : 'Bloqueado ✓' ) . '</button></form></td></tr>'; } echo '</tbody></table>'; } echo '</section></div>';
			self::updraft_panel(); echo '<h2>Destino y retención</h2><form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '">'; wp_nonce_field( self::ACTION_SAVE ); echo '<input type="hidden" name="action" value="' . esc_attr( self::ACTION_SAVE ) . '"><table class="form-table"><tr><th><label for="destination">Destino</label></th><td><select name="digitalisimo_backups[destination]" id="destination"><option value="local" ' . selected( $s['destination'], 'local', false ) . '>Hosting / almacenamiento local</option><option value="sftp" ' . selected( $s['destination'], 'sftp', false ) . '>Servidor Linux por SFTP</option><option value="google" ' . selected( $s['destination'], 'google', false ) . '>Google Drive</option><option value="onedrive" ' . selected( $s['destination'], 'onedrive', false ) . '>Microsoft OneDrive</option></select><p class="description">Los respaldos locales se guardan automáticamente en la carpeta protegida de Digitalisimo Backups.</p></td></tr><tr><th><label for="retention">Conservar localmente</label></th><td><input type="number" min="1" max="100" id="retention" name="digitalisimo_backups[retention]" value="' . esc_attr( $s['retention'] ) . '"> respaldos no bloqueados</td></tr></table>';
			self::schedule_fields( $s ); self::connection_fields( $s ); submit_button( 'Guardar destino y automatizaciones' ); echo '</form></div>';
		}
		private static function updraft_panel() { $sets = self::detect_updraft_sets(); echo '<h2>Respaldos detectados de UpdraftPlus</h2><p>Se analizan los archivos estándar dentro de <code>wp-content/updraft</code>. Sólo los conjuntos completos y sin cifrado se marcarán como disponibles para restauración.</p>'; if ( ! $sets ) { echo '<p>No se detectaron respaldos de UpdraftPlus en el almacenamiento local.</p>'; return; } echo '<table class="widefat striped"><thead><tr><th>Conjunto</th><th>Componentes</th><th>Estado</th></tr></thead><tbody>'; foreach ( $sets as $set ) { $components = array_map( function( $name, $parts ) { return $name . ( count( $parts ) > 1 ? ' × ' . count( $parts ) : '' ); }, array_keys( $set['files'] ), $set['files'] ); echo '<tr><td>' . esc_html( $set['id'] ) . '</td><td>' . esc_html( implode( ', ', $components ) ) . '</td><td>' . ( $set['complete'] ? 'Listo para validar' : 'Incompleto o cifrado' ) . '</td></tr>'; } echo '</tbody></table>'; }
		private static function schedule_fields( $s ) { echo '<h2>Respaldos automáticos</h2><p>Los dos ciclos son independientes. La retención conserva los últimos archivos no bloqueados de cada tipo; un respaldo bloqueado nunca entra en la rotación.</p><table class="form-table"><tr><th>WordPress completo</th><td><select name="digitalisimo_backups[full_schedule]">'; foreach ( self::schedule_options() as $value => $label ) echo '<option value="' . esc_attr( $value ) . '" ' . selected( $s['full_schedule'], $value, false ) . '>' . esc_html( $label ) . '</option>'; echo '</select><p class="description">Archivos, temas, plugins, medios y base de datos.</p></td></tr><tr><th>Base de datos</th><td><select name="digitalisimo_backups[database_schedule]">'; foreach ( self::schedule_options() as $value => $label ) echo '<option value="' . esc_attr( $value ) . '" ' . selected( $s['database_schedule'], $value, false ) . '>' . esc_html( $label ) . '</option>'; echo '</select><p class="description">Sólo SQL y manifiesto, para conservar más puntos de recuperación con menos espacio.</p></td></tr></table>'; }
	private static function connection_fields( $s ) {
		echo '<h2>Conexiones externas</h2><p>Configura sólo el destino que usarás. Los secretos ya guardados no se muestran; deja el campo vacío para conservarlos.</p><table class="form-table"><tr><th colspan="2"><h3>Servidor Linux por SFTP</h3></th></tr>';
		self::field( 'sftp_host', 'Host o IP', $s ); self::field( 'sftp_port', 'Puerto', $s, 'number' ); self::field( 'sftp_user', 'Usuario', $s ); self::field( 'sftp_password', 'Contraseña', $s, 'password' ); self::field( 'sftp_path', 'Carpeta remota', $s );
		echo '<tr><th colspan="2"><h3>Google Drive</h3></th></tr>'; self::field( 'google_client_id', 'Client ID', $s ); self::field( 'google_client_secret', 'Client secret', $s, 'password' ); self::field( 'google_refresh_token', 'Refresh token', $s, 'password' ); self::field( 'google_folder_id', 'ID de carpeta', $s ); echo '<tr><th>Cómo obtener Google Drive</th><td><ol><li>Abre <a href="https://console.cloud.google.com/" target="_blank" rel="noopener">Google Cloud Console</a> y crea o elige un proyecto.</li><li>Activa <strong>Google Drive API</strong> en APIs y servicios.</li><li>En Credenciales crea un cliente OAuth de tipo <strong>Aplicación web</strong>.</li><li>Agrega como URI de redirección autorizada: <code>' . esc_html( self::oauth_callback_url() ) . '</code></li><li>Copia Client ID y Client secret aquí, guarda y usa «Conectar Google Drive con mi sesión».</li></ol><p class="description">El permiso solicitado es sólo para los archivos creados por Digitalisimo Backups. El ID de carpeta se toma de la URL de la carpeta después de <code>/folders/</code>; puede dejarse vacío para usar Mi unidad.</p></td></tr>';
		echo '<tr><th colspan="2"><h3>Microsoft OneDrive</h3></th></tr>'; self::field( 'onedrive_client_id', 'Client ID', $s ); self::field( 'onedrive_client_secret', 'Client secret', $s, 'password' ); self::field( 'onedrive_refresh_token', 'Refresh token', $s, 'password' ); self::field( 'onedrive_folder', 'Carpeta remota', $s ); echo '<tr><th>Cómo obtener OneDrive</th><td><ol><li>Abre <a href="https://entra.microsoft.com/" target="_blank" rel="noopener">Microsoft Entra</a> → App registrations → New registration.</li><li>Selecciona cuentas personales y organizacionales si usarás una cuenta Microsoft personal.</li><li>En Authentication agrega plataforma <strong>Web</strong> y esta URL de redirección: <code>' . esc_html( self::oauth_callback_url() ) . '</code></li><li>En Certificates & secrets crea un Client secret.</li><li>Copia Application (client) ID y el valor del secret aquí, guarda y usa «Conectar OneDrive con mi sesión».</li></ol><p class="description">La carpeta debe existir previamente. Puedes usar, por ejemplo, <code>Digitalisimo Backups/Producción</code>.</p></td></tr>'; echo '</table><p><a class="button button-secondary" href="' . esc_url( self::oauth_url( 'google' ) ) . '">Conectar Google Drive con mi sesión</a> <a class="button button-secondary" href="' . esc_url( self::oauth_url( 'onedrive' ) ) . '">Conectar OneDrive con mi sesión</a></p><p class="description">Después de guardar las credenciales, abre el proveedor, inicia sesión si hace falta y autoriza con un clic; el plugin guarda el refresh token sin mostrarlo.</p>';
		}
	private static function field( $key, $label, $s, $type = 'text' ) { $secret = in_array( $key, self::secret_fields(), true ); echo '<tr><th><label for="' . esc_attr( $key ) . '">' . esc_html( $label ) . '</label></th><td><input class="regular-text" type="' . esc_attr( $type ) . '" id="' . esc_attr( $key ) . '" name="digitalisimo_backups[' . esc_attr( $key ) . ']" value="' . esc_attr( $secret ? '' : $s[ $key ] ) . '"' . ( $secret && $s[ $key ] ? ' placeholder="Guardado · escribe sólo para reemplazar"' : '' ) . '></td></tr>'; }
	private static function oauth_callback_url() { return admin_url( 'admin-post.php?action=' . self::ACTION_OAUTH ); }
	private static function oauth_url( $provider ) { return wp_nonce_url( add_query_arg( array( 'action' => self::ACTION_OAUTH, 'provider' => $provider ), admin_url( 'admin-post.php' ) ), self::ACTION_OAUTH ); }
	private static function download_url( $file ) { return wp_nonce_url( add_query_arg( array( 'action' => self::ACTION_DOWNLOAD, 'file' => rawurlencode( $file ) ), admin_url( 'admin-post.php' ) ), self::ACTION_DOWNLOAD ); }
	public static function download() { if ( ! self::can_manage() ) wp_die( 'No autorizado.' ); check_admin_referer( self::ACTION_DOWNLOAD ); $file = sanitize_file_name( wp_unslash( $_GET['file'] ?? '' ) ); $path = trailingslashit( self::local_directory() ) . $file; if ( ! $file || ! file_exists( $path ) || 0 !== strpos( wp_normalize_path( realpath( $path ) ), trailingslashit( wp_normalize_path( realpath( self::local_directory() ) ) ) ) ) wp_die( 'Respaldo no disponible.' ); nocache_headers(); header( 'Content-Type: application/zip' ); header( 'Content-Disposition: attachment; filename="' . $file . '"' ); header( 'Content-Length: ' . filesize( $path ) ); readfile( $path ); exit; }
	public static function oauth_callback() { if ( ! self::can_manage() ) wp_die( 'No autorizado.' ); $provider = sanitize_key( $_REQUEST['provider'] ?? '' ); if ( ! in_array( $provider, array( 'google', 'onedrive' ), true ) ) self::redirect( false, 'Proveedor no válido.' ); $settings = self::settings(); if ( empty( $_GET['code'] ) ) { check_admin_referer( self::ACTION_OAUTH ); if ( empty( $settings[ $provider . '_client_id' ] ) || empty( $settings[ $provider . '_client_secret' ] ) ) self::redirect( false, 'Guarda antes el Client ID y Client secret del proveedor.' ); $state = wp_generate_password( 32, false, false ); set_transient( 'digitalisimo_backup_oauth_' . get_current_user_id(), array( 'state' => $state, 'provider' => $provider ), 15 * MINUTE_IN_SECONDS ); $redirect = self::oauth_callback_url(); if ( 'google' === $provider ) $url = add_query_arg( array( 'client_id' => $settings['google_client_id'], 'redirect_uri' => $redirect, 'response_type' => 'code', 'access_type' => 'offline', 'prompt' => 'consent', 'scope' => 'https://www.googleapis.com/auth/drive.file', 'state' => $state ), 'https://accounts.google.com/o/oauth2/v2/auth' ); else $url = add_query_arg( array( 'client_id' => $settings['onedrive_client_id'], 'redirect_uri' => $redirect, 'response_type' => 'code', 'response_mode' => 'query', 'scope' => 'offline_access Files.ReadWrite', 'state' => $state ), 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize' ); wp_redirect( $url ); exit; } $saved = get_transient( 'digitalisimo_backup_oauth_' . get_current_user_id() ); if ( empty( $saved['state'] ) || ! hash_equals( $saved['state'], (string) $_GET['state'] ) || $provider !== $saved['provider'] ) self::redirect( false, 'La autorización expiró o no coincide. Inténtalo nuevamente.' ); delete_transient( 'digitalisimo_backup_oauth_' . get_current_user_id() ); $endpoint = 'google' === $provider ? 'https://oauth2.googleapis.com/token' : 'https://login.microsoftonline.com/common/oauth2/v2.0/token'; $response = wp_remote_post( $endpoint, array( 'timeout' => 30, 'body' => array( 'client_id' => $settings[ $provider . '_client_id' ], 'client_secret' => $settings[ $provider . '_client_secret' ], 'code' => sanitize_text_field( wp_unslash( $_GET['code'] ) ), 'redirect_uri' => self::oauth_callback_url(), 'grant_type' => 'authorization_code' ) ) ); $data = json_decode( wp_remote_retrieve_body( $response ), true ); if ( is_wp_error( $response ) || empty( $data['refresh_token'] ) ) self::redirect( false, 'El proveedor no devolvió un refresh token. Revisa la URL de redirección registrada en su aplicación.' ); $settings[ $provider . '_refresh_token' ] = sanitize_text_field( $data['refresh_token'] ); update_option( self::OPTION, $settings, false ); self::redirect( true, ( 'google' === $provider ? 'Google Drive' : 'OneDrive' ) . ' conectado correctamente.' ); }
	public static function save() {
		if ( ! self::can_manage() ) wp_die( 'No autorizado.' ); check_admin_referer( self::ACTION_SAVE ); $old = self::settings(); $input = (array) ( $_POST['digitalisimo_backups'] ?? array() ); $out = self::defaults();
			$out['destination'] = in_array( $input['destination'] ?? '', array( 'local', 'sftp', 'google', 'onedrive' ), true ) ? $input['destination'] : 'local'; $out['retention'] = min( 100, max( 1, absint( $input['retention'] ?? 5 ) ) );
		foreach ( array( 'sftp_host', 'sftp_user', 'sftp_path', 'google_client_id', 'google_folder_id', 'onedrive_client_id', 'onedrive_folder' ) as $key ) $out[ $key ] = sanitize_text_field( $input[ $key ] ?? '' ); $out['sftp_port'] = min( 65535, max( 1, absint( $input['sftp_port'] ?? 22 ) ) );
			foreach ( self::secret_fields() as $key ) $out[ $key ] = '' !== trim( (string) ( $input[ $key ] ?? '' ) ) ? sanitize_text_field( $input[ $key ] ) : $old[ $key ]; foreach ( array( 'full_schedule', 'database_schedule' ) as $key ) $out[ $key ] = array_key_exists( $input[ $key ] ?? '', self::schedule_options() ) ? $input[ $key ] : 'disabled'; update_option( self::OPTION, $out, false ); self::sync_schedules( $out ); wp_safe_redirect( add_query_arg( array( 'backup' => 'ok', 'message' => rawurlencode( 'Destino y automatizaciones guardados.' ) ), self::admin_url() ) ); exit;
	}
	public static function run() {
		if ( ! self::can_manage() ) wp_die( 'No autorizado.' ); check_admin_referer( self::ACTION_RUN ); @set_time_limit( 0 ); ignore_user_abort( true );
			$scope = sanitize_key( $_POST['digitalisimo_backup_scope'] ?? 'site' ); $network = 'network' === $scope && is_multisite() && current_user_can( 'manage_network_options' ); $site_id = $network ? get_current_blog_id() : absint( $_POST['digitalisimo_backup_site'] ?? get_current_blog_id() ); if ( $site_id && is_multisite() && ! get_site( $site_id ) ) self::redirect( false, 'El sitio elegido no existe.', $network );
			try { $file = $network ? self::create_network() : self::create_site( $site_id ?: get_current_blog_id() ); $s = self::settings(); if ( 'local' !== $s['destination'] ) self::transfer( $file, $s ); self::remember( $file, $s['destination'], $network ? 'network' : 'site' ); self::prune( dirname( $file ), (int) $s['retention'] ); self::redirect( true, ( $network ? 'Respaldo completo de la red creado: ' : 'Respaldo individual creado: ' ) . wp_basename( $file ), $network ); } catch ( Exception $e ) { self::redirect( false, $e->getMessage(), $network ); }
		}
		private static function create_network() {
		if ( ! class_exists( 'ZipArchive' ) ) throw new Exception( 'El servidor necesita la extensión PHP ZipArchive para crear el respaldo.' ); $s = self::settings(); $dir = self::local_directory(); if ( ! wp_mkdir_p( $dir ) || ! is_writable( $dir ) ) throw new Exception( 'No se puede escribir en la carpeta protegida de Digitalisimo Backups.' ); self::protect( $dir );
		$name = 'digitalisimo-backup-' . sanitize_title( wp_parse_url( home_url(), PHP_URL_HOST ) ) . '-' . gmdate( 'Ymd-His' ) . '.zip'; $file = trailingslashit( $dir ) . $name; $zip = new ZipArchive(); if ( true !== $zip->open( $file, ZipArchive::CREATE | ZipArchive::OVERWRITE ) ) throw new Exception( 'No se pudo crear el archivo ZIP.' );
			$sql = self::database_sql(); $zip->addFromString( 'database.sql', $sql ); $zip->addFromString( 'manifest.json', wp_json_encode( array( 'scope' => 'network', 'created_at' => gmdate( 'c' ), 'site' => home_url(), 'wordpress' => get_bloginfo( 'version' ), 'multisite' => is_multisite(), 'database' => DB_NAME ), JSON_PRETTY_PRINT ) ); self::add_directory( $zip, ABSPATH, $dir ); $zip->close(); if ( ! file_exists( $file ) || ! filesize( $file ) ) throw new Exception( 'El ZIP se creó vacío.' ); return $file;
		}
	private static function create_site( $site_id, $type = 'full' ) { if ( ! class_exists( 'ZipArchive' ) ) throw new Exception( 'El servidor necesita la extensión PHP ZipArchive para crear el respaldo.' ); $s = self::settings(); $dir = self::local_directory(); if ( ! wp_mkdir_p( $dir ) || ! is_writable( $dir ) ) throw new Exception( 'No se puede escribir en la carpeta protegida de Digitalisimo Backups.' ); self::protect( $dir ); $site = get_site( $site_id ); $name = 'digitalisimo-site-' . $site_id . '-' . sanitize_title( $site->domain ) . '-' . ( 'database' === $type ? 'db-' : 'full-' ) . gmdate( 'Ymd-His' ) . '.zip'; $file = trailingslashit( $dir ) . $name; $zip = new ZipArchive(); if ( true !== $zip->open( $file, ZipArchive::CREATE | ZipArchive::OVERWRITE ) ) throw new Exception( 'No se pudo crear el archivo ZIP.' ); switch_to_blog( $site_id ); global $wpdb; $prefix = $wpdb->prefix; $upload = wp_upload_dir(); $source_url = home_url(); $zip->addFromString( 'database.sql', self::database_sql( self::site_tables( $prefix ), $prefix, 'wp_' ) ); $zip->addFromString( 'migration.json', wp_json_encode( array( 'scope' => 'site', 'type' => $type, 'source_url' => $source_url, 'target_table_prefix' => 'wp_', 'upload_directory' => $upload['basedir'], 'created_at' => gmdate( 'c' ) ), JSON_PRETTY_PRINT ) ); if ( 'full' === $type ) { $zip->addFromString( 'MIGRAR-A-WORDPRESS-UNICO.txt', "1. Instala WordPress limpio.\n2. Copia wordpress/ sobre la instalación, excepto wp-config.php.\n3. Importa database.sql en la base de datos destino (usa prefijo wp_).\n4. Sustituye " . $source_url . " por la URL nueva en la base de datos con WP-CLI search-replace o una herramienta que preserve datos serializados.\n5. Revisa Ajustes > Enlaces permanentes y guarda una vez.\n" ); self::add_directory( $zip, ABSPATH, $dir, true ); self::add_upload_directory( $zip, $upload['basedir'] ); } restore_current_blog(); $zip->close(); if ( ! file_exists( $file ) || ! filesize( $file ) ) throw new Exception( 'El ZIP individual se creó vacío.' ); return $file; }
		private static function add_directory( $zip, $root, $backup_dir, $exclude_uploads = false ) { $iterator = new RecursiveIteratorIterator( new RecursiveDirectoryIterator( $root, FilesystemIterator::SKIP_DOTS ), RecursiveIteratorIterator::LEAVES_ONLY ); $backup_dir = trailingslashit( wp_normalize_path( $backup_dir ) ); foreach ( $iterator as $file ) { if ( ! $file->isFile() || $file->isLink() ) continue; $path = wp_normalize_path( $file->getPathname() ); if ( 0 === strpos( $path, $backup_dir ) || false !== strpos( $path, '/.git/' ) || false !== strpos( $path, '/node_modules/' ) || false !== strpos( $path, '/cache/' ) || ( $exclude_uploads && 0 === strpos( $path, trailingslashit( wp_normalize_path( WP_CONTENT_DIR . '/uploads' ) ) ) ) ) continue; $relative = ltrim( substr( $path, strlen( wp_normalize_path( ABSPATH ) ) ), '/' ); if ( $exclude_uploads && 'wp-config.php' === $relative ) continue; $zip->addFile( $path, 'wordpress/' . $relative ); } }
		private static function add_upload_directory( $zip, $directory ) { if ( ! is_dir( $directory ) ) return; $iterator = new RecursiveIteratorIterator( new RecursiveDirectoryIterator( $directory, FilesystemIterator::SKIP_DOTS ), RecursiveIteratorIterator::LEAVES_ONLY ); foreach ( $iterator as $file ) if ( $file->isFile() && ! $file->isLink() ) { $path = wp_normalize_path( $file->getPathname() ); $relative = ltrim( substr( $path, strlen( wp_normalize_path( $directory ) ) ), '/' ); $zip->addFile( $path, 'wordpress/wp-content/uploads/' . $relative ); } }
		private static function site_tables( $prefix ) { global $wpdb; $like = $wpdb->esc_like( $prefix ) . '%'; $tables = (array) $wpdb->get_col( $wpdb->prepare( 'SHOW TABLES LIKE %s', $like ) ); foreach ( array( $wpdb->base_prefix . 'users', $wpdb->base_prefix . 'usermeta' ) as $table ) if ( ! in_array( $table, $tables, true ) ) $tables[] = $table; return $tables; }
		private static function database_sql( $tables = null, $source_prefix = '', $target_prefix = '' ) { global $wpdb; $sql = "-- Digitalisimo WordPress backup\n-- " . gmdate( 'c' ) . "\nSET NAMES utf8mb4;\nSET foreign_key_checks = 0;\n\n"; foreach ( $tables ?: (array) $wpdb->get_col( 'SHOW TABLES' ) as $table ) { $output = $target_prefix && 0 === strpos( $table, $source_prefix ) ? $target_prefix . substr( $table, strlen( $source_prefix ) ) : $table; $create = $wpdb->get_row( "SHOW CREATE TABLE `" . str_replace( '`', '``', $table ) . "`", ARRAY_N ); if ( empty( $create[1] ) ) continue; $definition = str_replace( '`' . $table . '`', '`' . $output . '`', $create[1] ); $sql .= "DROP TABLE IF EXISTS `" . str_replace( '`', '``', $output ) . "`;\n" . $definition . ";\n"; $rows = $wpdb->get_results( "SELECT * FROM `" . str_replace( '`', '``', $table ) . "`", ARRAY_A ); foreach ( (array) $rows as $row ) { $columns = array_map( function( $column ) { return '`' . str_replace( '`', '``', $column ) . '`'; }, array_keys( $row ) ); $values = array_map( array( __CLASS__, 'sql_value' ), array_values( $row ) ); $sql .= 'INSERT INTO `' . str_replace( '`', '``', $output ) . '` (' . implode( ',', $columns ) . ') VALUES (' . implode( ',', $values ) . ");\n"; } $sql .= "\n"; } return $sql . "SET foreign_key_checks = 1;\n"; }
	private static function sql_value( $value ) { if ( null === $value ) return 'NULL'; return "'" . str_replace( array( '\\', "\0", "\n", "\r", "\x1a", "'" ), array( '\\\\', '\\0', '\\n', '\\r', '\\Z', "\\'" ), (string) $value ) . "'"; }
	private static function protect( $dir ) { if ( ! file_exists( trailingslashit( $dir ) . 'index.php' ) ) file_put_contents( trailingslashit( $dir ) . 'index.php', "<?php // Silence is golden.\n" ); if ( ! file_exists( trailingslashit( $dir ) . '.htaccess' ) ) file_put_contents( trailingslashit( $dir ) . '.htaccess', "Deny from all\n" ); }
	private static function transfer( $file, $s ) { if ( 'sftp' === $s['destination'] ) return self::sftp( $file, $s ); if ( 'google' === $s['destination'] ) return self::google( $file, $s ); if ( 'onedrive' === $s['destination'] ) return self::onedrive( $file, $s ); }
	private static function sftp( $file, $s ) { if ( ! function_exists( 'ssh2_connect' ) ) throw new Exception( 'SFTP requiere que el hosting tenga instalada la extensión PHP ssh2.' ); if ( ! $s['sftp_host'] || ! $s['sftp_user'] || ! $s['sftp_password'] ) throw new Exception( 'Completa host, usuario y contraseña SFTP.' ); $conn = @ssh2_connect( $s['sftp_host'], (int) $s['sftp_port'] ); if ( ! $conn || ! @ssh2_auth_password( $conn, $s['sftp_user'], $s['sftp_password'] ) ) throw new Exception( 'No se pudo autenticar en el servidor SFTP.' ); $remote = rtrim( $s['sftp_path'], '/' ) . '/' . wp_basename( $file ); $stream = @fopen( 'ssh2.sftp://' . intval( ssh2_sftp( $conn ) ) . $remote, 'w' ); $source = @fopen( $file, 'r' ); if ( ! $stream || ! $source ) throw new Exception( 'No se pudo abrir el destino SFTP.' ); stream_copy_to_stream( $source, $stream ); fclose( $source ); fclose( $stream ); }
	private static function token( $url, $s, $prefix ) { if ( ! $s[ $prefix . '_client_id' ] || ! $s[ $prefix . '_client_secret' ] || ! $s[ $prefix . '_refresh_token' ] ) throw new Exception( 'Completa Client ID, Client secret y Refresh token del destino.' ); $response = wp_remote_post( $url, array( 'timeout' => 30, 'body' => array( 'client_id' => $s[ $prefix . '_client_id' ], 'client_secret' => $s[ $prefix . '_client_secret' ], 'refresh_token' => $s[ $prefix . '_refresh_token' ], 'grant_type' => 'refresh_token' ) ) ); $data = json_decode( wp_remote_retrieve_body( $response ), true ); if ( is_wp_error( $response ) || empty( $data['access_token'] ) ) throw new Exception( 'No se pudo renovar el acceso al almacenamiento remoto.' ); return $data['access_token']; }
	private static function google( $file, $s ) { $token = self::token( 'https://oauth2.googleapis.com/token', $s, 'google' ); $metadata = array( 'name' => wp_basename( $file ) ); if ( $s['google_folder_id'] ) $metadata['parents'] = array( $s['google_folder_id'] ); $response = wp_remote_post( 'https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable', array( 'timeout' => 30, 'headers' => array( 'Authorization' => 'Bearer ' . $token, 'Content-Type' => 'application/json; charset=UTF-8', 'X-Upload-Content-Type' => 'application/zip', 'X-Upload-Content-Length' => filesize( $file ) ), 'body' => wp_json_encode( $metadata ) ) ); $session = wp_remote_retrieve_header( $response, 'location' ); if ( is_wp_error( $response ) || ! $session ) throw new Exception( 'Google Drive no pudo iniciar la carga.' ); self::resumable_upload( $session, $file, array( 'Content-Type' => 'application/zip' ) ); }
	private static function onedrive( $file, $s ) { $token = self::token( 'https://login.microsoftonline.com/common/oauth2/v2.0/token', $s, 'onedrive' ); $folder = trim( $s['onedrive_folder'], '/' ); $path = implode( '/', array_map( 'rawurlencode', array_filter( explode( '/', $folder ) ) ) ); $url = 'https://graph.microsoft.com/v1.0/me/drive/root:/' . $path . '/' . rawurlencode( wp_basename( $file ) ) . ':/createUploadSession'; $response = wp_remote_post( $url, array( 'timeout' => 30, 'headers' => array( 'Authorization' => 'Bearer ' . $token, 'Content-Type' => 'application/json' ), 'body' => wp_json_encode( array( 'item' => array( '@microsoft.graph.conflictBehavior' => 'rename' ) ) ) ) ); $data = json_decode( wp_remote_retrieve_body( $response ), true ); if ( is_wp_error( $response ) || empty( $data['uploadUrl'] ) ) throw new Exception( 'OneDrive no pudo iniciar la carga. Verifica que exista la carpeta remota.' ); self::resumable_upload( $data['uploadUrl'], $file, array(), 3276800 ); }
	/** Sube en fragmentos para que archivos grandes no agoten la memoria del hosting. */
	private static function resumable_upload( $url, $file, $headers = array(), $chunk_size = 8388608 ) { $size = filesize( $file ); $handle = @fopen( $file, 'rb' ); if ( ! $handle ) throw new Exception( 'No se pudo leer el ZIP para transferirlo.' ); $offset = 0; while ( ! feof( $handle ) ) { $chunk = fread( $handle, $chunk_size ); if ( false === $chunk || '' === $chunk ) break; $end = $offset + strlen( $chunk ) - 1; $response = wp_remote_request( $url, array( 'method' => 'PUT', 'timeout' => 120, 'headers' => array_merge( $headers, array( 'Content-Length' => strlen( $chunk ), 'Content-Range' => 'bytes ' . $offset . '-' . $end . '/' . $size ) ), 'body' => $chunk ) ); $code = wp_remote_retrieve_response_code( $response ); if ( is_wp_error( $response ) || ! in_array( $code, array( 200, 201, 202, 308 ), true ) ) { fclose( $handle ); throw new Exception( 'El almacenamiento remoto interrumpió la transferencia.' ); } $offset = $end + 1; } fclose( $handle ); if ( $offset !== $size ) throw new Exception( 'La transferencia remota quedó incompleta.' ); }
	private static function remember( $file, $destination, $scope = 'site' ) { $history = (array) get_option( self::HISTORY, array() ); array_unshift( $history, array( 'date' => current_time( 'mysql' ), 'file' => wp_basename( $file ), 'size' => filesize( $file ), 'destination' => $destination, 'scope' => $scope ) ); update_option( self::HISTORY, array_slice( $history, 0, 30 ), false ); }
	public static function toggle_lock() { if ( ! self::can_manage() ) wp_die( 'No autorizado.' ); check_admin_referer( self::ACTION_LOCK ); $file = sanitize_file_name( wp_unslash( $_POST['file'] ?? '' ) ); $history = (array) get_option( self::HISTORY, array() ); foreach ( $history as &$item ) if ( hash_equals( (string) ( $item['file'] ?? '' ), $file ) ) $item['locked'] = ! empty( $_POST['locked'] ); unset( $item ); update_option( self::HISTORY, $history, false ); self::redirect( true, ! empty( $_POST['locked'] ) ? 'Respaldo bloqueado: no se eliminará durante la rotación.' : 'Respaldo desbloqueado.' ); }
	private static function prune( $dir, $keep ) { $history = (array) get_option( self::HISTORY, array() ); $locked = array_filter( array_column( array_filter( $history, function( $item ) { return ! empty( $item['locked'] ); } ), 'file' ) ); $files = glob( trailingslashit( $dir ) . 'digitalisimo-*.zip' ) ?: array(); usort( $files, function( $a, $b ) { return filemtime( $b ) <=> filemtime( $a ); } ); $rotating = array_values( array_filter( $files, function( $file ) use ( $locked ) { return ! in_array( wp_basename( $file ), $locked, true ); } ) ); foreach ( array_slice( $rotating, $keep ) as $file ) @unlink( $file ); }
		private static function redirect( $ok, $message, $network = false ) { $url = $network ? network_admin_url( 'admin.php?page=digitalisimo-network-backups' ) : admin_url( 'admin.php?page=digitalisimo-backups' ); wp_safe_redirect( add_query_arg( array( 'backup' => $ok ? 'ok' : 'error', 'message' => rawurlencode( $message ) ), $url ) ); exit; }
	private static function destination_label( $destination ) { return array( 'local' => 'Hosting / local', 'sftp' => 'Servidor Linux por SFTP', 'google' => 'Google Drive', 'onedrive' => 'OneDrive' )[ $destination ] ?? 'Local'; }
}
