<?php
defined( 'ABSPATH' ) || exit;

class Digitalisimo_Integrations_WooCommerce {
	public static function init() {
		if ( ! Digitalisimo_Ecommerce_Settings::get( 'enable_woocommerce' ) ) return;
		add_action( 'rest_api_init', array( __CLASS__, 'routes' ) ); add_action( 'wp_enqueue_scripts', array( __CLASS__, 'assets' ) ); add_shortcode( 'digitalisimo_domain_search', array( __CLASS__, 'shortcode' ) );
		if ( class_exists( 'WooCommerce' ) ) { add_filter( 'woocommerce_add_cart_item_data', array( __CLASS__, 'cart_domain' ), 10, 3 ); add_filter( 'woocommerce_get_item_data', array( __CLASS__, 'cart_item_data' ), 10, 2 ); add_action( 'woocommerce_checkout_create_order_line_item', array( __CLASS__, 'order_item_domain' ), 10, 4 );
			add_filter( 'digitalisimo_ai_context', array( __CLASS__, 'ai_context' ), 10, 3 );
			if ( Digitalisimo_Ecommerce_Settings::get( 'require_domain_hosting' ) ) add_action( 'woocommerce_check_cart_items', array( __CLASS__, 'validate_cart' ) ); if ( Digitalisimo_Ecommerce_Settings::get( 'replace_hosting' ) ) add_filter( 'woocommerce_add_to_cart_validation', array( __CLASS__, 'replace_hosting' ), 10, 3 ); if ( Digitalisimo_Ecommerce_Settings::get( 'simplify_checkout' ) ) add_filter( 'woocommerce_checkout_fields', array( __CLASS__, 'checkout_fields' ) ); }
	}
	public static function ai_context( $context, $profile ) { if ( 'chatbot' !== $profile || ! class_exists( 'WooCommerce' ) ) return $context; $products = wc_get_products( array( 'status' => 'publish', 'limit' => 8, 'return' => 'objects' ) ); if ( ! $products ) return $context; $context .= "\nProductos disponibles:"; foreach ( $products as $product ) $context .= "\n- " . $product->get_name() . ': ' . wp_strip_all_tags( $product->get_short_description() ) . ' ' . $product->get_price_html(); return $context; }
	public static function assets() { wp_register_style( 'digitalisimo-domain-search', DIGITALISIMO_ECOMMERCE_URL . 'assets/domain-search.css', array(), DIGITALISIMO_ECOMMERCE_VERSION ); wp_register_script( 'digitalisimo-domain-search', DIGITALISIMO_ECOMMERCE_URL . 'assets/domain-search.js', array(), DIGITALISIMO_ECOMMERCE_VERSION, true ); wp_localize_script( 'digitalisimo-domain-search', 'digitalisimoDomainSearch', array( 'endpoint' => esc_url_raw( rest_url( 'digitalisimo/v1/' ) ), 'nonce' => wp_create_nonce( 'wp_rest' ) ) ); }
	private static function products() { $items = array(); foreach ( preg_split( '/\r\n|\r|\n/', (string) Digitalisimo_Ecommerce_Settings::get( 'domain_products' ) ) as $line ) { $parts = array_map( 'trim', explode( '|', $line, 2 ) ); if ( 2 === count( $parts ) && $parts[0] && absint( $parts[1] ) ) $items[ strtolower( $parts[0] ) ] = absint( $parts[1] ); } return $items; }
	private static function rate_limit() { $ip = (string) ( $_SERVER['REMOTE_ADDR'] ?? '' ); $key = 'digitalisimo_ecommerce_domain_rate_' . md5( wp_salt( 'nonce' ) . '|' . $ip ); $count = (int) get_transient( $key ); if ( $count >= 20 ) return false; set_transient( $key, $count + 1, MINUTE_IN_SECONDS ); return true; }
	public static function shortcode() { if ( ! class_exists( 'WooCommerce' ) ) return ''; wp_enqueue_style( 'digitalisimo-domain-search' ); wp_enqueue_script( 'digitalisimo-domain-search' ); $options = ''; foreach ( self::products() as $extension => $id ) $options .= '<option value="' . esc_attr( $extension ) . '" data-product-id="' . esc_attr( $id ) . '">' . esc_html( $extension ) . '</option>'; return '<form class="digitalisimo-domain-search"><label>Dominio <input required name="domain" pattern="[A-Za-z0-9-]+" autocomplete="off"></label><label>Extensión <select required name="extension">' . $options . '</select></label><button type="submit">Verificar dominio</button><div class="digitalisimo-domain-result" aria-live="polite"></div></form>'; }
	public static function routes() { register_rest_route( 'digitalisimo/v1', '/check-domain', array( 'methods' => 'GET', 'callback' => array( __CLASS__, 'check_domain' ), 'permission_callback' => '__return_true', 'args' => array( 'domain' => array( 'required' => true, 'sanitize_callback' => 'sanitize_text_field' ) ) ) ); register_rest_route( 'digitalisimo/v1', '/product-price', array( 'methods' => 'GET', 'callback' => array( __CLASS__, 'price' ), 'permission_callback' => '__return_true' ) ); }
	public static function check_domain( WP_REST_Request $request ) { $domain = strtolower( $request->get_param( 'domain' ) ); if ( ! preg_match( '/^[a-z0-9-]+\.[a-z]{2,20}$/', $domain ) ) return new WP_Error( 'invalid_domain', __( 'Dominio no válido.', 'digitalisimo-integrations' ), array( 'status' => 400 ) ); if ( ! self::rate_limit() ) return new WP_Error( 'rate_limit', __( 'Demasiadas consultas. Intenta de nuevo en un minuto.', 'digitalisimo-integrations' ), array( 'status' => 429 ) ); $key = Digitalisimo_Ecommerce_Settings::get( 'namecheap_api_key' ); $user = Digitalisimo_Ecommerce_Settings::get( 'namecheap_api_user' ); $name = Digitalisimo_Ecommerce_Settings::get( 'namecheap_username' ); $ip = Digitalisimo_Ecommerce_Settings::get( 'namecheap_client_ip' ); if ( ! $key || ! $user || ! $name || ! $ip ) return new WP_Error( 'not_configured', __( 'La consulta de dominios no está configurada.', 'digitalisimo-integrations' ), array( 'status' => 503 ) ); $response = wp_remote_get( add_query_arg( array( 'ApiUser' => $user, 'ApiKey' => $key, 'UserName' => $name, 'ClientIp' => $ip, 'Command' => 'namecheap.domains.check', 'DomainList' => $domain ), 'https://api.namecheap.com/xml.response' ), array( 'timeout' => 15 ) ); if ( is_wp_error( $response ) ) return $response; $xml = simplexml_load_string( wp_remote_retrieve_body( $response ) ); if ( ! $xml || ! isset( $xml->CommandResponse->DomainCheckResult ) ) return new WP_Error( 'namecheap_response', __( 'Respuesta inválida de Namecheap.', 'digitalisimo-integrations' ), array( 'status' => 502 ) ); return rest_ensure_response( array( 'available' => 'true' === strtolower( (string) $xml->CommandResponse->DomainCheckResult['Available'] ) ) ); }
	public static function price( WP_REST_Request $request ) { $product = function_exists( 'wc_get_product' ) ? wc_get_product( absint( $request->get_param( 'product_id' ) ) ) : false; if ( ! $product ) return new WP_Error( 'product_not_found', __( 'Producto no encontrado.', 'digitalisimo-integrations' ), array( 'status' => 404 ) ); return rest_ensure_response( array( 'price_html' => $product->get_price_html(), 'price' => $product->get_price(), 'currency' => get_woocommerce_currency_symbol() ) ); }
	public static function cart_domain( $data, $product_id, $variation_id ) { $domain = $_REQUEST['digitalisimo_domain'] ?? $_REQUEST['domain_name'] ?? ''; if ( $domain ) $data['digitalisimo_domain'] = sanitize_text_field( wp_unslash( $domain ) ); return $data; }
	public static function cart_item_data( $data, $item ) { if ( ! empty( $item['digitalisimo_domain'] ) ) $data[] = array( 'name' => __( 'Dominio', 'digitalisimo-integrations' ), 'value' => $item['digitalisimo_domain'] ); return $data; }
	public static function order_item_domain( $item, $cart_item_key, $values, $order ) { if ( ! empty( $values['digitalisimo_domain'] ) ) $item->add_meta_data( __( 'Dominio', 'digitalisimo-integrations' ), $values['digitalisimo_domain'], true ); }
	private static function ids( $key ) { return array_filter( array_map( 'absint', preg_split( '/\s*,\s*/', (string) Digitalisimo_Ecommerce_Settings::get( $key ) ) ) ); }
	private static function is_hosting( $product_id ) { $products = self::ids( 'hosting_product_ids' ); $categories = self::ids( 'hosting_category_ids' ); return in_array( $product_id, $products, true ) || ( $categories && has_term( $categories, 'product_cat', $product_id ) ); }
	public static function validate_cart() { $has_hosting = false; $has_domain = false; $domain_ids = array_values( self::products() ); foreach ( WC()->cart->get_cart() as $item ) { $id = $item['product_id']; $has_hosting = $has_hosting || self::is_hosting( $id ); $has_domain = $has_domain || in_array( $id, $domain_ids, true ); } if ( $has_hosting xor $has_domain ) wc_add_notice( __( 'Agrega un dominio y un plan de hosting para continuar.', 'digitalisimo-integrations' ), 'error' ); }
	public static function replace_hosting( $passed, $product_id, $quantity ) { if ( ! self::is_hosting( $product_id ) ) return $passed; foreach ( WC()->cart->get_cart() as $key => $item ) if ( self::is_hosting( $item['product_id'] ) ) WC()->cart->remove_cart_item( $key ); return $passed; }
	public static function checkout_fields( $fields ) { $fields['billing'] = array( 'billing_first_name' => array( 'label' => __( 'Nombre', 'digitalisimo-integrations' ), 'required' => true, 'class' => array( 'form-row-wide' ) ), 'billing_phone' => array( 'label' => __( 'Teléfono', 'digitalisimo-integrations' ), 'required' => true, 'class' => array( 'form-row-wide' ) ), 'billing_email' => array( 'label' => __( 'Correo electrónico', 'digitalisimo-integrations' ), 'required' => true, 'class' => array( 'form-row-wide' ) ) ); unset( $fields['shipping'], $fields['order'] ); return $fields; }
}
