<?php
defined( 'ABSPATH' ) || exit;

/** Configuración autónoma del módulo Ecommerce. */
class Digitalisimo_Ecommerce_Admin {
	const OPTION = 'digitalisimo_integrations_options';
	public static function page() {
		if ( ! current_user_can( 'manage_options' ) ) return;
		if ( isset( $_POST['digitalisimo_ecommerce_save'] ) && check_admin_referer( 'digitalisimo_ecommerce_save' ) ) self::save();
		$o = (array) get_option( self::OPTION, array() );
		foreach ( array( 'enable_woocommerce', 'namecheap_api_user', 'namecheap_username', 'namecheap_api_key', 'namecheap_client_ip', 'domain_products', 'hosting_product_ids', 'hosting_category_ids', 'require_domain_hosting', 'replace_hosting', 'simplify_checkout' ) as $key ) $o[ $key ] = Digitalisimo_Ecommerce_Settings::get( $key, $o[ $key ] ?? '' );
		echo '<div class="wrap"><h1>Digitalisimo · Ecommerce</h1><p>Dominio, hosting y checkout para WooCommerce. Instala WooCommerce únicamente si usarás el flujo de compra.</p><form method="post">'; wp_nonce_field( 'digitalisimo_ecommerce_save' ); if ( is_multisite() ) { $inherit = (array) get_option( 'digitalisimo_module_network_inherit', array() ); echo '<p class="notice notice-info inline"><label><input type="hidden" name="ecommerce[inherit_network]" value="0"><input type="checkbox" name="ecommerce[inherit_network]" value="1" ' . checked( ! array_key_exists( 'enable_woocommerce', $inherit ) || ! empty( $inherit['enable_woocommerce'] ), true, false ) . '> <strong>Heredar la configuración Ecommerce de la red</strong></label><br><span class="description">Valor efectivo: ' . esc_html( Digitalisimo_Ecommerce_Settings::origin( 'enable_woocommerce' ) ) . '. Al desactivar herencia, este sitio puede personalizar sus valores.</span></p>'; }
		self::check( 'enable_woocommerce', 'Activar integraciones WooCommerce', $o, 1 );
		echo '<h2>Búsqueda de dominios</h2>'; self::field( 'namecheap_api_user', 'Usuario API Namecheap', $o ); self::field( 'namecheap_username', 'Usuario Namecheap', $o ); self::field( 'namecheap_api_key', 'Clave API Namecheap', $o, 'password' ); self::field( 'namecheap_client_ip', 'IP autorizada por Namecheap', $o ); self::area( 'domain_products', 'Productos de dominio', $o, 'Formato: .com|ID-del-producto, una línea por extensión.' );
		echo '<h2>Hosting y checkout</h2>'; self::area( 'hosting_product_ids', 'IDs de productos de hosting', $o, 'Separados por comas.' ); self::area( 'hosting_category_ids', 'IDs de categorías de hosting', $o, 'Separados por comas.' ); self::check( 'require_domain_hosting', 'Exigir dominio y hosting juntos', $o ); self::check( 'replace_hosting', 'Sustituir hosting anterior al añadir uno nuevo', $o ); self::check( 'simplify_checkout', 'Simplificar campos del checkout', $o );
		echo '<p><code>[digitalisimo_domain_search]</code> inserta el buscador de dominios.</p>'; submit_button( 'Guardar Ecommerce' ); echo '</form></div>';
	}
	public static function network_page() {
		if ( ! current_user_can( 'manage_network_options' ) ) return;
		if ( isset( $_POST['digitalisimo_ecommerce_network_save'] ) && check_admin_referer( 'digitalisimo_ecommerce_network_save' ) ) { $o = (array) get_site_option( self::OPTION, array() ); $in = (array) wp_unslash( $_POST['ecommerce'] ?? array() ); foreach ( array( 'enable_woocommerce', 'require_domain_hosting', 'replace_hosting', 'simplify_checkout' ) as $key ) $o[ $key ] = empty( $in[ $key ] ) ? 0 : 1; foreach ( array( 'namecheap_api_user', 'namecheap_username', 'namecheap_client_ip' ) as $key ) $o[ $key ] = sanitize_text_field( $in[ $key ] ?? '' ); foreach ( array( 'domain_products', 'hosting_product_ids', 'hosting_category_ids' ) as $key ) $o[ $key ] = sanitize_textarea_field( $in[ $key ] ?? '' ); if ( ! empty( $in['namecheap_api_key'] ) ) $o['namecheap_api_key'] = sanitize_text_field( $in['namecheap_api_key'] ); update_site_option( self::OPTION, $o ); }
		$o = (array) get_site_option( self::OPTION, array() ); echo '<div class="wrap"><h1>Digitalisimo · Ecommerce de red</h1><p>Valores heredables dinámicamente por los sitios de la red.</p><form method="post">'; wp_nonce_field( 'digitalisimo_ecommerce_network_save' ); self::check( 'enable_woocommerce', 'Activar integraciones WooCommerce', $o, 1 ); self::field( 'namecheap_api_user', 'Usuario API Namecheap', $o ); self::field( 'namecheap_username', 'Usuario Namecheap', $o ); self::field( 'namecheap_api_key', 'Clave API Namecheap', $o, 'password' ); self::field( 'namecheap_client_ip', 'IP autorizada', $o ); self::area( 'domain_products', 'Productos de dominio', $o ); self::area( 'hosting_product_ids', 'IDs hosting', $o ); self::check( 'require_domain_hosting', 'Exigir dominio y hosting juntos', $o ); self::check( 'simplify_checkout', 'Simplificar checkout', $o ); submit_button( 'Guardar Ecommerce de red', 'primary', 'digitalisimo_ecommerce_network_save' ); echo '</form></div>';
	}
	private static function field( $key, $label, $o, $type = 'text' ) { $value = 'password' === $type ? '' : ( $o[ $key ] ?? '' ); echo '<p><label><strong>' . esc_html( $label ) . '</strong><br><input class="regular-text" type="' . esc_attr( $type ) . '" name="ecommerce[' . esc_attr( $key ) . ']" value="' . esc_attr( $value ) . '">'; if ( 'password' === $type && ! empty( $o[ $key ] ) ) echo ' <span class="description">Ya configurada; déjala vacía para conservarla.</span>'; echo '</label></p>'; }
	private static function area( $key, $label, $o, $help = '' ) { echo '<p><label><strong>' . esc_html( $label ) . '</strong><br><textarea class="large-text code" rows="3" name="ecommerce[' . esc_attr( $key ) . ']">' . esc_textarea( $o[ $key ] ?? '' ) . '</textarea></label>' . ( $help ? '<br><span class="description">' . esc_html( $help ) . '</span>' : '' ) . '</p>'; }
	private static function check( $key, $label, $o, $default = 0 ) { echo '<p><label><input type="hidden" name="ecommerce[' . esc_attr( $key ) . ']" value="0"><input type="checkbox" name="ecommerce[' . esc_attr( $key ) . ']" value="1" ' . checked( ! empty( $o[ $key ] ) || ( ! isset( $o[ $key ] ) && $default ), true, false ) . '> <strong>' . esc_html( $label ) . '</strong></label></p>'; }
	private static function save() { $old = (array) get_option( self::OPTION, array() ); $in = (array) wp_unslash( $_POST['ecommerce'] ?? array() ); $keys = array( 'enable_woocommerce', 'require_domain_hosting', 'replace_hosting', 'simplify_checkout', 'namecheap_api_user', 'namecheap_username', 'namecheap_api_key', 'namecheap_client_ip', 'domain_products', 'hosting_product_ids', 'hosting_category_ids' ); if ( is_multisite() ) { $inherit = (array) get_option( 'digitalisimo_module_network_inherit', array() ); foreach ( $keys as $key ) $inherit[ $key ] = ! empty( $in['inherit_network'] ) ? 1 : 0; update_option( 'digitalisimo_module_network_inherit', $inherit, false ); } foreach ( array( 'enable_woocommerce', 'require_domain_hosting', 'replace_hosting', 'simplify_checkout' ) as $key ) $old[ $key ] = empty( $in[ $key ] ) ? 0 : 1; foreach ( array( 'namecheap_api_user', 'namecheap_username', 'namecheap_client_ip' ) as $key ) $old[ $key ] = sanitize_text_field( $in[ $key ] ?? '' ); foreach ( array( 'domain_products', 'hosting_product_ids', 'hosting_category_ids' ) as $key ) $old[ $key ] = sanitize_textarea_field( $in[ $key ] ?? '' ); if ( ! empty( $in['namecheap_api_key'] ) ) $old['namecheap_api_key'] = sanitize_text_field( $in['namecheap_api_key'] ); update_option( self::OPTION, $old, false ); }
}
