<?php
namespace Digitalisimo\Tools;
defined( 'ABSPATH' ) || exit;
final class Updater {
	const CACHE_KEY = 'digitalisimo_tools_release';
	public static function init() { add_filter( 'pre_set_site_transient_update_plugins', array( __CLASS__, 'check' ) ); add_filter( 'pre_set_transient_update_plugins', array( __CLASS__, 'check' ) ); add_filter( 'site_transient_update_plugins', array( __CLASS__, 'check' ) ); add_filter( 'transient_update_plugins', array( __CLASS__, 'check' ) ); }
	private static function release() { $cached = get_site_transient( self::CACHE_KEY ); if ( false !== $cached ) return (array) $cached; $r = wp_remote_get( 'https://api.github.com/repos/danbutanda/digitalisimo-plugin/releases?per_page=50', array( 'timeout' => 10, 'headers' => array( 'User-Agent' => 'Digitalisimo-Tools' ) ) ); if ( is_wp_error( $r ) || 200 !== wp_remote_retrieve_response_code( $r ) ) { set_site_transient( self::CACHE_KEY, array(), 5 * MINUTE_IN_SECONDS ); return array(); } $best = array(); foreach ( (array) json_decode( wp_remote_retrieve_body( $r ), true ) as $release ) foreach ( (array) ( $release['assets'] ?? array() ) as $asset ) if ( preg_match( '/^digitalisimo-tools-([0-9.]+)\\.zip$/', $asset['name'] ?? '', $m ) && ( empty( $best['version'] ) || version_compare( $m[1], $best['version'], '>' ) ) ) $best = array( 'version' => $m[1], 'package' => esc_url_raw( $asset['browser_download_url'] ?? '' ) ); set_site_transient( self::CACHE_KEY, $best, HOUR_IN_SECONDS ); return $best; }
	public static function check( $t ) { if ( ! is_object( $t ) ) $t = new \stdClass(); $file = plugin_basename( DIGITALISIMO_TOOLS_FILE ); if ( ! isset( $t->checked ) || ! is_array( $t->checked ) ) $t->checked = array(); $t->checked[ $file ] = DIGITALISIMO_TOOLS_VERSION; if ( ! isset( $t->response ) || ! is_array( $t->response ) ) $t->response = array(); if ( ! isset( $t->no_update ) || ! is_array( $t->no_update ) ) $t->no_update = array(); $best = self::release(); if ( ! empty( $best['version'] ) && version_compare( $best['version'], DIGITALISIMO_TOOLS_VERSION, '>' ) ) { unset( $t->no_update[ $file ] ); $t->response[ $file ] = (object) array( 'slug' => 'digitalisimo-tools', 'plugin' => $file, 'new_version' => $best['version'], 'package' => $best['package'] ); } else { unset( $t->response[ $file ] ); $t->no_update[ $file ] = (object) array( 'slug' => 'digitalisimo-tools', 'plugin' => $file, 'new_version' => DIGITALISIMO_TOOLS_VERSION, 'package' => '' ); } return $t; }
}
