<?php
defined( 'ABSPATH' ) || exit;

/** Configuración autónoma y consciente de privacidad para IPinfo. */
class Digitalisimo_Geolocation_Admin {
	const OPTION = 'digitalisimo_integrations_options';
	public static function page() {
		if ( ! current_user_can( 'manage_options' ) ) return;
		if ( isset( $_POST['digitalisimo_geo_save'] ) && check_admin_referer( 'digitalisimo_geo_save' ) ) { $o = (array) get_option( self::OPTION, array() ); $in = (array) wp_unslash( $_POST['geo'] ?? array() ); if ( is_multisite() ) { $inherit = (array) get_option( 'digitalisimo_module_network_inherit', array() ); foreach ( array( 'enable_ipinfo', 'ipinfo_tokens', 'ipinfo_cache_minutes' ) as $key ) $inherit[ $key ] = ! empty( $in['inherit_network'] ) ? 1 : 0; update_option( 'digitalisimo_module_network_inherit', $inherit, false ); } $o['enable_ipinfo'] = empty( $in['enable_ipinfo'] ) ? 0 : 1; $o['ipinfo_cache_minutes'] = max( 0, absint( $in['ipinfo_cache_minutes'] ?? 60 ) ); if ( '' !== trim( (string) ( $in['ipinfo_tokens'] ?? '' ) ) ) $o['ipinfo_tokens'] = sanitize_textarea_field( $in['ipinfo_tokens'] ); update_option( self::OPTION, $o, false ); echo '<div class="notice notice-success is-dismissible"><p>Configuración guardada.</p></div>'; }
		$o = (array) get_option( self::OPTION, array() );
		foreach ( array( 'enable_ipinfo', 'ipinfo_tokens', 'ipinfo_cache_minutes' ) as $key ) $o[ $key ] = Digitalisimo_Geolocation_Settings::get( $key, $o[ $key ] ?? '' );
		echo '<div class="wrap"><h1>Digitalisimo · Geolocalización</h1><p>Ubicación aproximada mediante IPinfo, sólo cuando se inserta expresamente el shortcode. Las IP no se guardan; la respuesta se guarda temporalmente según la caché configurada.</p><form method="post">'; wp_nonce_field( 'digitalisimo_geo_save' ); if ( is_multisite() ) { $inherit = (array) get_option( 'digitalisimo_module_network_inherit', array() ); echo '<p class="notice notice-info inline"><label><input type="hidden" name="geo[inherit_network]" value="0"><input type="checkbox" name="geo[inherit_network]" value="1" ' . checked( ! array_key_exists( 'enable_ipinfo', $inherit ) || ! empty( $inherit['enable_ipinfo'] ), true, false ) . '> <strong>Heredar la configuración de red</strong></label><br><span class="description">Valor efectivo: ' . esc_html( Digitalisimo_Geolocation_Settings::origin( 'enable_ipinfo' ) ) . '. Al desactivar herencia, este sitio puede personalizar su configuración.</span></p>'; }
		echo '<p><label><input type="hidden" name="geo[enable_ipinfo]" value="0"><input type="checkbox" name="geo[enable_ipinfo]" value="1" ' . checked( ! empty( $o['enable_ipinfo'] ), true, false ) . '> <strong>Activar ubicación aproximada</strong></label></p><p><label><strong>Tokens de IPinfo</strong><br><textarea class="large-text code" rows="5" name="geo[ipinfo_tokens]" placeholder="Un token por línea"></textarea></label>'; if ( ! empty( $o['ipinfo_tokens'] ) ) echo '<br><span class="description">Ya hay tokens guardados. Deja el campo vacío para conservarlos.</span>'; echo '</p><p><label><strong>Caché en minutos</strong><br><input type="number" min="0" name="geo[ipinfo_cache_minutes]" value="' . esc_attr( $o['ipinfo_cache_minutes'] ?? 60 ) . '"></label></p><p><code>[ubicacion_usuario]</code> muestra “en Ciudad, Región, País”.</p>'; submit_button( 'Guardar Geolocalización' ); echo '</form></div>';
	}
	public static function network_page() {
		if ( ! current_user_can( 'manage_network_options' ) ) return;
		if ( isset( $_POST['digitalisimo_geo_network_save'] ) && check_admin_referer( 'digitalisimo_geo_network_save' ) ) { $o = (array) get_site_option( self::OPTION, array() ); $in = (array) wp_unslash( $_POST['geo'] ?? array() ); $o['enable_ipinfo'] = empty( $in['enable_ipinfo'] ) ? 0 : 1; $o['ipinfo_cache_minutes'] = max( 0, absint( $in['ipinfo_cache_minutes'] ?? 60 ) ); if ( '' !== trim( (string) ( $in['ipinfo_tokens'] ?? '' ) ) ) $o['ipinfo_tokens'] = sanitize_textarea_field( $in['ipinfo_tokens'] ); update_site_option( self::OPTION, $o ); echo '<div class="notice notice-success is-dismissible"><p>Configuración de red guardada.</p></div>'; }
		$o = (array) get_site_option( self::OPTION, array() ); echo '<div class="wrap"><h1>Digitalisimo · Geolocalización de red</h1><p>Valores heredables dinámicamente por cada sitio.</p><form method="post">'; wp_nonce_field( 'digitalisimo_geo_network_save' ); echo '<p><label><input type="hidden" name="geo[enable_ipinfo]" value="0"><input type="checkbox" name="geo[enable_ipinfo]" value="1" ' . checked( ! empty( $o['enable_ipinfo'] ), true, false ) . '> <strong>Activar ubicación aproximada</strong></label></p><p><label><strong>Tokens IPinfo</strong><br><textarea class="large-text code" rows="5" name="geo[ipinfo_tokens]" placeholder="Un token por línea"></textarea></label>'; echo ! empty( $o['ipinfo_tokens'] ) ? '<br><span class="description">Ya hay tokens guardados. Deja el campo vacío para conservarlos.</span>' : '<br><span class="description">Sin tokens configurados.</span>'; echo '</p><p><label><strong>Caché (minutos)</strong><br><input type="number" min="0" name="geo[ipinfo_cache_minutes]" value="' . esc_attr( $o['ipinfo_cache_minutes'] ?? 60 ) . '"></label></p>'; submit_button( 'Guardar Geolocalización de red', 'primary', 'digitalisimo_geo_network_save' ); echo '</form></div>';
	}
}
