<?php
defined( 'ABSPATH' ) || exit;

/** Perfil editorial compartido de IA Tools para Codex, MCP y generación interna. */
class Digitalisimo_AI_Content_Playbook {
	private static function resource() { static $profile = null; if ( null !== $profile ) return $profile; $file = dirname( __DIR__ ) . '/resources/editorial-profile.json'; $data = is_readable( $file ) ? json_decode( (string) file_get_contents( $file ), true ) : array(); $profile = is_array( $data ) ? $data : array(); return $profile; }
	public static function version() { return (string) ( self::resource()['version'] ?? 'sin-versión' ); }
	private static function legacy( $key ) { if ( class_exists( 'Digitalisimo_Integrations_Settings' ) ) return (string) Digitalisimo_Integrations_Settings::get( 'content_editorial_' . $key, '' ); return ''; }
	public static function profile() { $resource = self::resource(); $options = Digitalisimo_AI::get(); $out = array( 'id' => $resource['id'] ?? 'digitalisimo-editorial', 'version' => self::version() ); foreach ( array( 'voice', 'context', 'cta', 'method' ) as $key ) { $value = trim( (string) ( $options[ 'editorial_' . $key ] ?? '' ) ); $out[ $key ] = $value ?: ( self::legacy( $key ) ?: (string) ( $resource[ $key ] ?? '' ) ); } return $out; }
	public static function fields( $network = false ) { $p = self::profile(); foreach ( array( 'voice' => 'Voz de marca', 'context' => 'Contexto de Digitalísimo', 'cta' => 'CTA editorial', 'method' => 'Reglas de redacción SEO' ) as $key => $label ) echo '<p><label><strong>' . esc_html( $label ) . '</strong><br><textarea class="large-text" rows="4" name="ai[editorial_' . esc_attr( $key ) . ']">' . esc_textarea( $p[ $key ] ) . '</textarea></label></p>'; if ( ! $network ) echo '<p class="description">Este perfil se usa en la generación interna, el publisher y las conexiones MCP. La configuración anterior de SEO se conserva como respaldo hasta que guardes aquí.</p>'; }
	public static function prompt( $primary, $secondary = array(), $title = '' ) { $p = self::profile(); return "Método editorial DIGITALISIMO:\nVoz: {$p['voice']}\nContexto: {$p['context']}\nCTA: {$p['cta']}\nReglas: {$p['method']}\n\nKeyword principal: {$primary}\nKeywords secundarias: " . implode( ', ', array_map( 'sanitize_text_field', (array) $secondary ) ) . "\nTítulo sugerido: {$title}\n\nDevuelve JSON válido con title, seo_title, meta_description (120-160 caracteres), secondary_keywords y content (HTML sin H1)."; }
	public static function generate( $primary, $secondary = array(), $title = '' ) { $answer = Digitalisimo_AI::complete( 'content', self::prompt( $primary, $secondary, $title ), 'Genera solamente el JSON solicitado; usa datos proporcionados y no inventes servicios, resultados ni enlaces.' ); if ( is_wp_error( $answer ) ) return $answer; $data = json_decode( trim( preg_replace( '/^```(?:json)?|```$/m', '', $answer ) ), true ); if ( ! is_array( $data ) || empty( $data['content'] ) || empty( $data['title'] ) || empty( $data['meta_description'] ) ) return new WP_Error( 'digitalisimo_ai_format', 'La IA no devolvió un borrador estructurado válido.' ); $data['content'] = preg_replace( '#^\s*<h1\b[^>]*>.*?</h1>\s*#is', '', wp_kses_post( $data['content'] ), 1 ); return $data; }
}
