<?php
defined( 'ABSPATH' ) || exit;

/** Generación bajo demanda: guarda el resultado como borrador de medio, nunca lo publica. */
class Digitalisimo_AI_Images {
	public static function init() { add_action( 'rest_api_init', array( __CLASS__, 'routes' ) ); add_action( 'admin_menu', array( __CLASS__, 'menu' ), 30 ); }
	public static function menu() { add_submenu_page( null, 'IA · Imágenes', 'IA · Imágenes', 'upload_files', 'digitalisimo-ai-images', array( __CLASS__, 'page' ) ); }
	public static function routes() { register_rest_route( 'digitalisimo-ai/v1', '/image', array( 'methods' => 'POST', 'callback' => array( __CLASS__, 'generate' ), 'permission_callback' => function(){ return current_user_can( 'upload_files' ); }, 'args' => array( 'prompt' => array( 'required' => true, 'sanitize_callback' => 'sanitize_textarea_field' ) ) ) ); }
	public static function generate( $request ) { $all = Digitalisimo_AI::get(); $profile = $all['profiles']['images'] ?? array(); $provider = $all['providers'][ $profile['provider'] ?? '' ] ?? array(); if ( 'openai' !== ( $profile['provider'] ?? '' ) || empty( $provider['enabled'] ) || empty( $provider['key'] ) ) return new WP_Error( 'image_provider', 'La generación de imágenes requiere un perfil OpenAI activo.', array( 'status' => 400 ) ); $response = wp_remote_post( $provider['url'] ?: 'https://api.openai.com/v1/images/generations', array( 'timeout' => 90, 'headers' => array( 'Authorization' => 'Bearer ' . $provider['key'], 'Content-Type' => 'application/json' ), 'body' => wp_json_encode( array( 'model' => $profile['model'] ?: 'gpt-image-1', 'prompt' => $request['prompt'], 'size' => sanitize_text_field( $all['image_size'] ?? '1024x1024' ) ) ) ) ); if ( is_wp_error( $response ) ) return $response; $body = json_decode( wp_remote_retrieve_body( $response ), true ); $url = $body['data'][0]['url'] ?? ''; $base64 = $body['data'][0]['b64_json'] ?? ''; require_once ABSPATH . 'wp-admin/includes/media.php'; require_once ABSPATH . 'wp-admin/includes/file.php'; require_once ABSPATH . 'wp-admin/includes/image.php'; if ( $base64 ) { $upload = wp_upload_bits( 'digitalisimo-ai-' . time() . '.png', null, base64_decode( $base64 ) ); if ( $upload['error'] ) return new WP_Error( 'image_upload', $upload['error'] ); $attachment = wp_insert_attachment( array( 'post_mime_type' => 'image/png', 'post_title' => sanitize_text_field( wp_trim_words( $request['prompt'], 10, '' ) ), 'post_status' => 'inherit' ), $upload['file'] ); wp_update_attachment_metadata( $attachment, wp_generate_attachment_metadata( $attachment, $upload['file'] ) ); } elseif ( $url ) { $attachment = media_sideload_image( esc_url_raw( $url ), 0, sanitize_text_field( wp_trim_words( $request['prompt'], 10, '' ) ), 'id' ); } else return new WP_Error( 'image_response', 'El proveedor no devolvió una imagen.', array( 'status' => 502 ) ); if ( is_wp_error( $attachment ) ) return $attachment; update_post_meta( $attachment, '_digitalisimo_ai_generated', '1' ); return rest_ensure_response( array( 'attachment_id' => $attachment, 'url' => wp_get_attachment_url( $attachment ) ) ); }
	public static function page() {
		if ( ! current_user_can( 'upload_files' ) ) return;
		echo '<div class="wrap"><h1>Digitalisimo AI · Imágenes</h1><p>Genera una imagen bajo demanda. El resultado llegará a la Biblioteca de Medios y nunca se publica ni se asigna automáticamente.</p><p><label for="digitalisimo-ai-image-prompt"><strong>Instrucción</strong></label><br><textarea id="digitalisimo-ai-image-prompt" class="large-text" rows="5" maxlength="2000" placeholder="Describe la imagen que quieres crear."></textarea></p><p><button type="button" class="button button-primary" id="digitalisimo-ai-image-generate">Generar imagen</button> <span id="digitalisimo-ai-image-status"></span></p><div id="digitalisimo-ai-image-result"></div></div>';
		$endpoint = esc_url_raw( rest_url( 'digitalisimo-ai/v1/image' ) ); $nonce = wp_create_nonce( 'wp_rest' );
		echo '<script>document.addEventListener("DOMContentLoaded",function(){var button=document.getElementById("digitalisimo-ai-image-generate"),prompt=document.getElementById("digitalisimo-ai-image-prompt"),status=document.getElementById("digitalisimo-ai-image-status"),result=document.getElementById("digitalisimo-ai-image-result");button.addEventListener("click",function(){if(!prompt.value.trim()){status.textContent="Escribe una instrucción.";return;}button.disabled=true;status.textContent="Generando…";fetch("' . esc_js( $endpoint ) . '",{method:"POST",headers:{"Content-Type":"application/json","X-WP-Nonce":"' . esc_js( $nonce ) . '"},body:JSON.stringify({prompt:prompt.value})}).then(function(r){return r.json();}).then(function(data){if(data.url){status.textContent="Lista para revisar.";result.innerHTML="<p><a href=\""+data.url+"\" target=\"_blank\" rel=\"noopener\"><img style=\"max-width:512px;height:auto\" src=\""+data.url+"\" alt=\"Imagen generada\"></a></p>";}else status.textContent=data.message||"No fue posible generar la imagen.";}).catch(function(){status.textContent="Error de conexión.";}).finally(function(){button.disabled=false;});});});</script>';
	}
}
