<?php
defined( 'ABSPATH' ) || exit;

/** Generación contextual de imágenes para artículos; nunca publica contenido. */
class Digitalisimo_AI_Images {
	const API_SIZE = '1536x1024';
	const OUTPUT_WIDTH = 1536;
	const OUTPUT_HEIGHT = 864;

	public static function init() {
		add_action( 'rest_api_init', array( __CLASS__, 'routes' ) );
		add_action( 'admin_menu', array( __CLASS__, 'menu' ), 30 );
		add_action( 'add_meta_boxes', array( __CLASS__, 'post_metabox' ) );
	}

	public static function menu() {
		add_submenu_page( null, 'IA · Imágenes de artículos', 'IA · Imágenes de artículos', 'upload_files', 'digitalisimo-ai-images', array( __CLASS__, 'page' ) );
	}

	public static function post_metabox() {
		foreach ( get_post_types( array( 'public' => true, 'show_ui' => true ), 'names' ) as $type ) add_meta_box( 'digitalisimo-ai-article-image', 'Imagen SEO del artículo', array( __CLASS__, 'post_metabox_html' ), $type, 'side', 'default' );
	}

	public static function routes() {
		register_rest_route( 'digitalisimo-ai/v1', '/image', array( 'methods' => 'POST', 'callback' => array( __CLASS__, 'generate' ), 'permission_callback' => function() { return current_user_can( 'upload_files' ); }, 'args' => array(
			'prompt' => array( 'required' => false, 'sanitize_callback' => 'sanitize_textarea_field' ), 'post_id' => array( 'required' => false, 'sanitize_callback' => 'absint' ), 'image_title' => array( 'required' => false, 'sanitize_callback' => 'sanitize_text_field' ), 'image_alt' => array( 'required' => false, 'sanitize_callback' => 'sanitize_text_field' ),
		) ) );
	}

	public static function generate( $request ) {
		$all = Digitalisimo_AI::get(); $profile = $all['profiles']['images'] ?? array(); $provider = $all['providers'][ $profile['provider'] ?? '' ] ?? array();
		if ( 'openai' !== ( $profile['provider'] ?? '' ) || empty( $provider['enabled'] ) || empty( $provider['key'] ) ) return new WP_Error( 'image_provider', 'La generación de imágenes requiere un perfil OpenAI activo.', array( 'status' => 400 ) );
		$post_id = absint( $request->get_param( 'post_id' ) ); $post = $post_id ? get_post( $post_id ) : null;
		if ( $post_id && ( ! $post || ! current_user_can( 'edit_post', $post_id ) ) ) return new WP_Error( 'image_post', 'No puedes editar el artículo indicado.', array( 'status' => 403 ) );
		$context = self::article_context( $post ); $prompt = sanitize_textarea_field( (string) $request->get_param( 'prompt' ) ); if ( ! $prompt ) $prompt = self::default_prompt(); if ( $context ) $prompt .= "\n\nContexto SEO del artículo:\n" . $context;
		$response = wp_remote_post( $provider['url'] ?: 'https://api.openai.com/v1/images/generations', array( 'timeout' => 120, 'headers' => array( 'Authorization' => 'Bearer ' . $provider['key'], 'Content-Type' => 'application/json' ), 'body' => wp_json_encode( array( 'model' => $profile['model'] ?: 'gpt-image-1', 'prompt' => $prompt, 'size' => self::API_SIZE ) ) ) );
		if ( is_wp_error( $response ) ) return $response; $code = wp_remote_retrieve_response_code( $response ); $body = json_decode( wp_remote_retrieve_body( $response ), true ); if ( $code < 200 || $code >= 300 ) return new WP_Error( 'image_provider_response', sanitize_text_field( $body['error']['message'] ?? 'El proveedor de imágenes devolvió un error.' ), array( 'status' => 502 ) );
		$url = $body['data'][0]['url'] ?? ''; $base64 = $body['data'][0]['b64_json'] ?? ''; require_once ABSPATH . 'wp-admin/includes/media.php'; require_once ABSPATH . 'wp-admin/includes/file.php'; require_once ABSPATH . 'wp-admin/includes/image.php';
		$title = sanitize_text_field( $request->get_param( 'image_title' ) ?: ( $post ? $post->post_title : wp_trim_words( $prompt, 10, '' ) ) ); $alt = sanitize_text_field( $request->get_param( 'image_alt' ) ?: $title );
		if ( $base64 ) { $upload = wp_upload_bits( 'digitalisimo-ai-' . time() . '.png', null, base64_decode( $base64 ) ); if ( $upload['error'] ) return new WP_Error( 'image_upload', $upload['error'] ); $attachment = wp_insert_attachment( array( 'post_mime_type' => 'image/png', 'post_title' => $title, 'post_status' => 'inherit' ), $upload['file'], $post_id ); $file = $upload['file']; } elseif ( $url ) { $attachment = media_sideload_image( esc_url_raw( $url ), $post_id, $title, 'id' ); $file = $attachment && ! is_wp_error( $attachment ) ? get_attached_file( $attachment ) : ''; } else return new WP_Error( 'image_response', 'El proveedor no devolvió una imagen.', array( 'status' => 502 ) );
		if ( is_wp_error( $attachment ) ) return $attachment; if ( $file ) self::crop_to_article_ratio( $attachment, $file ); wp_update_post( array( 'ID' => $attachment, 'post_title' => $title, 'post_name' => sanitize_title( $title ) ) ); update_post_meta( $attachment, '_wp_attachment_image_alt', $alt ); update_post_meta( $attachment, '_digitalisimo_ai_generated', '1' ); if ( $post_id ) set_post_thumbnail( $post_id, $attachment ); $size = wp_get_attachment_image_src( $attachment, 'full' );
		return rest_ensure_response( array( 'attachment_id' => $attachment, 'post_id' => $post_id, 'url' => wp_get_attachment_url( $attachment ), 'title' => $title, 'alt' => $alt, 'width' => (int) ( $size[1] ?? self::OUTPUT_WIDTH ), 'height' => (int) ( $size[2] ?? self::OUTPUT_HEIGHT ) ) );
	}

	private static function article_context( $post ) { if ( ! $post ) return ''; $keywords = array_filter( array_map( 'trim', explode( ',', (string) get_post_meta( $post->ID, 'digitalisimo_seo_keywords', true ) ) ) ); return 'Título: ' . $post->post_title . '. Keyword principal: ' . ( $keywords[0] ?? '' ) . '. Keywords secundarias: ' . implode( ', ', array_slice( $keywords, 1 ) ) . '. Contenido: ' . wp_trim_words( wp_strip_all_tags( $post->post_content ), 130, '' ); }
	private static function default_prompt() { return 'Crea una imagen editorial horizontal para la imagen destacada de un artículo SEO de Digitalísimo. Representa visualmente el tema del artículo con estilo tecnológico, profesional, cercano y humano. No incluyas texto, letras, logotipos, marcas de agua ni interfaces ilegibles. Usa composición limpia, sujeto principal claro, espacio visual equilibrado y aspecto fotográfico o ilustrativo de alta calidad.'; }
	private static function crop_to_article_ratio( $attachment, $file ) { $editor = wp_get_image_editor( $file ); if ( is_wp_error( $editor ) ) return; $size = $editor->get_size(); $width = (int) ( $size['width'] ?? 0 ); $height = (int) ( $size['height'] ?? 0 ); if ( ! $width || ! $height ) return; $ratio = self::OUTPUT_WIDTH / self::OUTPUT_HEIGHT; if ( $width / $height > $ratio ) { $crop_height = $height; $crop_width = (int) round( $height * $ratio ); $x = (int) floor( ( $width - $crop_width ) / 2 ); $y = 0; } else { $crop_width = $width; $crop_height = (int) round( $width / $ratio ); $x = 0; $y = (int) floor( ( $height - $crop_height ) / 2 ); } $editor->crop( $x, $y, $crop_width, $crop_height, self::OUTPUT_WIDTH, self::OUTPUT_HEIGHT ); $editor->save( $file ); wp_update_attachment_metadata( $attachment, wp_generate_attachment_metadata( $attachment, $file ) ); }

	public static function post_metabox_html( $post ) { $keywords = array_filter( array_map( 'trim', explode( ',', (string) get_post_meta( $post->ID, 'digitalisimo_seo_keywords', true ) ) ) ); $endpoint = esc_url_raw( rest_url( 'digitalisimo-ai/v1/image' ) ); $nonce = wp_create_nonce( 'wp_rest' ); echo '<p>Genera una imagen destacada contextual para este artículo. Se guarda en la Biblioteca y se recorta automáticamente a 1536 × 864 px (16:9).</p><p><label><strong>Texto alternativo</strong><br><input id="digitalisimo-ai-article-alt" class="widefat" value="' . esc_attr( $post->post_title ) . '"></label></p><p><button type="button" class="button button-primary" id="digitalisimo-ai-article-image" data-post-id="' . absint( $post->ID ) . '" data-keyword="' . esc_attr( $keywords[0] ?? '' ) . '">Generar imagen del artículo</button> <span id="digitalisimo-ai-article-image-status"></span></p><div id="digitalisimo-ai-article-image-result"></div>'; self::script( $endpoint, $nonce, true ); }
	public static function page() { if ( ! current_user_can( 'upload_files' ) ) return; echo '<div class="wrap"><h1>Digitalísimo IA Tools · Imágenes de artículos</h1><p>Genera imágenes destacadas contextualizadas por título, keyword y contenido. Todas terminan en formato horizontal 1536 × 864 px (16:9) y quedan en la Biblioteca para revisión.</p><p><label for="digitalisimo-ai-image-post"><strong>ID de entrada opcional</strong></label><br><input id="digitalisimo-ai-image-post" class="small-text" type="number" min="0" placeholder="Ej. 1622"></p><p><label for="digitalisimo-ai-image-prompt"><strong>Instrucción adicional opcional</strong></label><br><textarea id="digitalisimo-ai-image-prompt" class="large-text" rows="5" maxlength="2000" placeholder="El contexto del artículo se añadirá automáticamente."></textarea></p><p><label for="digitalisimo-ai-image-alt"><strong>Texto alternativo</strong></label><br><input id="digitalisimo-ai-image-alt" class="large-text" maxlength="180" placeholder="Descripción SEO natural de la imagen"></p><p><button type="button" class="button button-primary" id="digitalisimo-ai-image-generate">Generar imagen</button> <span id="digitalisimo-ai-image-status"></span></p><div id="digitalisimo-ai-image-result"></div></div>'; self::script( esc_url_raw( rest_url( 'digitalisimo-ai/v1/image' ) ), wp_create_nonce( 'wp_rest' ), false ); }
	private static function script( $endpoint, $nonce, $article ) { $button = $article ? 'digitalisimo-ai-article-image' : 'digitalisimo-ai-image-generate'; $status = $article ? 'digitalisimo-ai-article-image-status' : 'digitalisimo-ai-image-status'; $result = $article ? 'digitalisimo-ai-article-image-result' : 'digitalisimo-ai-image-result'; $post = $article ? 'b.dataset.postId' : '(document.getElementById("digitalisimo-ai-image-post")||{}).value||0'; $alt = $article ? 'document.getElementById("digitalisimo-ai-article-alt").value' : '(document.getElementById("digitalisimo-ai-image-alt")||{}).value||""'; $prompt = $article ? '""' : '(document.getElementById("digitalisimo-ai-image-prompt")||{}).value||""'; echo '<script>document.addEventListener("DOMContentLoaded",function(){var b=document.getElementById("' . esc_js( $button ) . '"),s=document.getElementById("' . esc_js( $status ) . '"),r=document.getElementById("' . esc_js( $result ) . '");if(!b)return;b.addEventListener("click",function(){var post=' . $post . ',alt=' . $alt . ',prompt=' . $prompt . ';b.disabled=true;s.textContent="Generando…";fetch("' . esc_js( $endpoint ) . '",{method:"POST",headers:{"Content-Type":"application/json","X-WP-Nonce":"' . esc_js( $nonce ) . '"},body:JSON.stringify({post_id:post,prompt:prompt,image_alt:alt})}).then(function(x){return x.json()}).then(function(x){if(x.url){s.textContent="Imagen lista y guardada en la Biblioteca.";r.innerHTML="<p><a href=\""+x.url+"\" target=\"_blank\" rel=\"noopener\"><img style=\"max-width:640px;height:auto\" src=\""+x.url+"\" alt=\"Imagen generada\"></a></p>"}else s.textContent=x.message||"No fue posible generar la imagen."}).catch(function(){s.textContent="Error de conexión."}).finally(function(){b.disabled=false})})})</script>'; }
}
