<?php
defined( 'ABSPATH' ) || exit;

/** Herramientas editoriales nativas: ubicaciones, clusters y estado de producción. */
class Digitalisimo_Integrations_Editorial {
	public static function init() {
		add_action( 'init', array( __CLASS__, 'locations_cpt' ) ); add_action( 'add_meta_boxes', array( __CLASS__, 'metaboxes' ) ); add_action( 'save_post', array( __CLASS__, 'save' ), 30 ); add_action( 'wp_after_insert_post', array( __CLASS__, 'apply_default_cluster' ), 20, 4 ); add_action( 'save_post_digitalisimo_location', array( __CLASS__, 'save_location' ), 10, 2 ); add_action( 'admin_post_digitalisimo_create_location', array( __CLASS__, 'create_location' ) );
		// Variables editoriales dinámicas para plantillas de contenido.
		add_shortcode( 'palabra_clave', array( __CLASS__, 'shortcode_primary_keyword' ) );
		add_shortcode( 'palabras_clave_secundarias', array( __CLASS__, 'shortcode_secondary_keywords' ) );
		add_shortcode( 'contenido_pilar', array( __CLASS__, 'shortcode_pillar' ) );
		add_shortcode( 'contenido_secundario', array( __CLASS__, 'shortcode_secondary' ) );
		add_shortcode( 'descripcion_sitio', array( __CLASS__, 'shortcode_site_description' ) );
		add_shortcode( 'ubicacion_seo', array( __CLASS__, 'shortcode_location' ) ); add_shortcode( 'pais_seo', array( __CLASS__, 'shortcode_country' ) ); add_shortcode( 'estado_seo', array( __CLASS__, 'shortcode_state' ) ); add_shortcode( 'ciudad_seo', array( __CLASS__, 'shortcode_city' ) ); add_shortcode( 'zona_seo', array( __CLASS__, 'shortcode_zone' ) );
		add_action( 'admin_enqueue_scripts', array( __CLASS__, 'assets' ) );
		add_filter( 'manage_post_posts_columns', array( __CLASS__, 'columns' ) ); add_filter( 'manage_page_posts_columns', array( __CLASS__, 'columns' ) ); add_action( 'manage_post_posts_custom_column', array( __CLASS__, 'column_value' ), 10, 2 ); add_action( 'manage_page_posts_custom_column', array( __CLASS__, 'column_value' ), 10, 2 );
		add_filter( 'manage_edit-post_sortable_columns', array( __CLASS__, 'sortable' ) ); add_filter( 'manage_edit-page_sortable_columns', array( __CLASS__, 'sortable' ) ); add_action( 'restrict_manage_posts', array( __CLASS__, 'filters' ) ); add_action( 'pre_get_posts', array( __CLASS__, 'query' ) );
		add_action( 'bulk_edit_custom_box', array( __CLASS__, 'bulk_fields' ), 10, 2 ); add_action( 'admin_action_editpost', array( __CLASS__, 'bulk_save' ) );
	}
	/** Obtiene la entrada principal incluso cuando Elementor cambia el post global para otro widget. */
	private static function current_content_id() {
		global $wp_query, $post;
		$candidates = array( get_queried_object_id(), $wp_query instanceof WP_Query ? $wp_query->get_queried_object_id() : 0, $wp_query instanceof WP_Query && ! empty( $wp_query->post->ID ) ? $wp_query->post->ID : 0, ! empty( $post->ID ) ? $post->ID : 0, get_the_ID() );
		foreach ( $candidates as $candidate ) { $id = absint( $candidate ); if ( $id && in_array( get_post_type( $id ), self::types(), true ) ) return $id; }
		return 0;
	}
	private static function post_keywords( $post_id = 0 ) {
		$post_id = $post_id ?: self::current_content_id();
		return array_values( array_filter( array_map( 'trim', explode( ',', (string) get_post_meta( $post_id, 'digitalisimo_seo_keywords', true ) ) ) ) );
	}
	/** Inserta la keyword principal configurada para que una plantilla se actualice al editarla. */
	public static function shortcode_primary_keyword() {
		$keywords = self::post_keywords();
		return esc_html( $keywords[0] ?? '' );
	}
	/** Inserta las keywords secundarias configuradas como una lista semántica. */
	public static function shortcode_secondary_keywords() {
		$keywords = self::post_keywords();
		array_shift( $keywords );
		return $keywords ? '<ul><li>' . implode( '</li><li>', array_map( 'esc_html', $keywords ) ) . '</li></ul>' : '';
	}
	public static function shortcode_pillar() {
		$pillar = get_post( absint( get_post_meta( get_the_ID(), '_related_pillar', true ) ) );
		return $pillar ? '<a href="' . esc_url( get_permalink( $pillar ) ) . '">' . esc_html( $pillar->post_title ) . '</a>' : '';
	}
	public static function shortcode_secondary() {
		$posts = get_posts( array( 'post_type' => self::types(), 'post_status' => 'publish', 'posts_per_page' => -1, 'meta_key' => '_related_pillar', 'meta_value' => get_the_ID() ) );
		if ( ! $posts ) return '';
		$html = '<ul>';
		foreach ( $posts as $post ) $html .= '<li><a href="' . esc_url( get_permalink( $post ) ) . '">' . esc_html( $post->post_title ) . '</a></li>';
		return $html . '</ul>';
	}
	public static function shortcode_site_description() { return esc_html( get_bloginfo( 'description' ) ); }
	public static function assets( $hook ) { if ( ! in_array( $hook, array( 'post.php', 'post-new.php' ), true ) ) return; wp_enqueue_style( 'digitalisimo-keyword-manager', DIGITALISIMO_INTEGRATIONS_URL . 'assets/keyword-manager.css', array(), DIGITALISIMO_INTEGRATIONS_VERSION ); wp_enqueue_script( 'digitalisimo-keyword-manager', DIGITALISIMO_INTEGRATIONS_URL . 'assets/keyword-manager.js', array(), DIGITALISIMO_INTEGRATIONS_VERSION, true ); }
	public static function locations_cpt() { register_post_type( 'digitalisimo_location', array( 'labels' => array( 'name' => 'Ubicaciones SEO', 'singular_name' => 'Ubicación SEO', 'add_new_item' => 'Añadir ubicación' ), 'public' => false, 'show_ui' => true, 'show_in_menu' => 'digitalisimo', 'hierarchical' => true, 'supports' => array( 'title', 'page-attributes' ), 'capability_type' => 'post' ) ); }
	private static function location_levels() { return array( 'country' => 'País', 'state' => 'Estado', 'city' => 'Ciudad', 'zone' => 'Zona' ); }
	private static function location_level( $id ) { $level = get_post_meta( $id, '_digitalisimo_location_level', true ); return array_key_exists( $level, self::location_levels() ) ? $level : ''; }
	private static function location_parts( $id = 0 ) { $parts = array_fill_keys( array_keys( self::location_levels() ), '' ); while ( $id && ( $location = get_post( $id ) ) && 'digitalisimo_location' === $location->post_type ) { $level = self::location_level( $id ); if ( $level && ! $parts[ $level ] ) $parts[ $level ] = $location->post_title; $id = (int) $location->post_parent; } return $parts; }
	private static function location_label( $id ) { $parts = array_filter( self::location_parts( $id ) ); return $parts ? implode( ' · ', $parts ) : get_the_title( $id ); }
	private static function current_location_parts() { return self::location_parts( absint( get_post_meta( self::current_content_id(), '_related_location_id', true ) ) ); }
	public static function shortcode_location() { return esc_html( implode( ', ', array_filter( self::current_location_parts() ) ) ); }
	public static function shortcode_country() { $p = self::current_location_parts(); return esc_html( $p['country'] ); }
	public static function shortcode_state() { $p = self::current_location_parts(); return esc_html( $p['state'] ); }
	public static function shortcode_city() { $p = self::current_location_parts(); return esc_html( $p['city'] ); }
	public static function shortcode_zone() { $p = self::current_location_parts(); return esc_html( $p['zone'] ); }
	/** Tipos realmente públicos: nunca plantillas, bloques internos ni biblioteca de Elementor. */
	public static function content_types() {
		$excluded = array( 'attachment', 'elementor_library', 'elementor-hf', 'wp_template', 'wp_template_part', 'wp_global_styles', 'wp_navigation', 'wp_block' );
		$types = get_post_types( array( 'public' => true, 'show_ui' => true ), 'objects' );
		return array_values( array_keys( array_filter( $types, function( $type, $slug ) use ( $excluded ) { return ! in_array( $slug, $excluded, true ); }, ARRAY_FILTER_USE_BOTH ) ) );
	}
	private static function types() { return self::content_types(); }
	/** El catálogo no usa flujo editorial: muestra cada ubicación guardada sin depender de su estado. */
	private static function locations() { return get_posts( array( 'post_type' => 'digitalisimo_location', 'post_status' => array( 'publish', 'private', 'draft', 'pending' ), 'posts_per_page' => -1, 'orderby' => 'title', 'order' => 'ASC' ) ); }
	private static function pillars() { return get_posts( array( 'post_type' => self::types(), 'posts_per_page' => -1, 'meta_key' => 'digitalisimo_seo_pillar', 'meta_value' => 'on' ) ); }
	public static function cluster_candidates() { return get_posts( array( 'post_type' => self::types(), 'post_status' => 'publish', 'posts_per_page' => -1, 'orderby' => 'title', 'order' => 'ASC' ) ); }
	public static function is_cluster_candidate( $post_id ) { $post = get_post( absint( $post_id ) ); return $post && 'publish' === $post->post_status && in_array( $post->post_type, self::types(), true ); }
	/** Resuelve un ID local o un slug heredado desde la red al pilar de este sitio. */
	public static function cluster_candidate_id( $value ) { $id = absint( $value ); if ( $id && self::is_cluster_candidate( $id ) ) return $id; $slug = sanitize_title( (string) $value ); if ( ! $slug ) return 0; $matches = get_posts( array( 'post_type' => self::types(), 'post_status' => 'publish', 'name' => $slug, 'posts_per_page' => 1, 'orderby' => 'ID', 'order' => 'ASC' ) ); return ! empty( $matches[0] ) ? (int) $matches[0]->ID : 0; }
	/** Selector compartido por el editor, Contenido y la configuración de red. */
	public static function cluster_select( $name, $selected = 0, $id = '' ) { echo '<select class="widefat"' . ( $id ? ' id="' . esc_attr( $id ) . '"' : '' ) . ' name="' . esc_attr( $name ) . '"><option value="0">Sin pilar predeterminado</option>'; foreach ( self::cluster_candidates() as $pillar ) { $type = get_post_type_object( $pillar->post_type ); echo '<option value="' . esc_attr( $pillar->ID ) . '" ' . selected( absint( $selected ), $pillar->ID, false ) . '>' . esc_html( ( $type->labels->singular_name ?? $pillar->post_type ) . ' · ' . $pillar->post_title ) . '</option>'; } echo '</select>'; }
	/** En red se guarda un slug para resolver el pilar equivalente dentro de cada sitio. */
	public static function cluster_slug_select( $name, $selected = '', $id = '' ) { echo '<select class="widefat"' . ( $id ? ' id="' . esc_attr( $id ) . '"' : '' ) . ' name="' . esc_attr( $name ) . '"><option value="">Sin pilar predeterminado</option>'; foreach ( self::cluster_candidates() as $pillar ) { $type = get_post_type_object( $pillar->post_type ); echo '<option value="' . esc_attr( $pillar->post_name ) . '" ' . selected( (string) $selected, $pillar->post_name, false ) . '>' . esc_html( ( $type->labels->singular_name ?? $pillar->post_type ) . ' · ' . $pillar->post_title ) . '</option>'; } echo '</select>'; }
	public static function metaboxes() { add_meta_box( 'digitalisimo_location_details', 'Catálogo de ubicación SEO', array( __CLASS__, 'location_details_box' ), 'digitalisimo_location', 'normal', 'high' ); foreach ( self::types() as $type ) { add_meta_box( 'digitalisimo_keywords_editor', 'Palabras clave', array( __CLASS__, 'keywords_box' ), $type, 'side', 'high' ); add_meta_box( 'digitalisimo_cluster_method', 'Cluster de contenido', array( __CLASS__, 'cluster_box' ), $type, 'side', 'high' ); add_meta_box( 'digitalisimo_location', 'Ubicación', array( __CLASS__, 'location_box' ), $type, 'side' ); } }
	public static function keywords_box( $post ) { wp_nonce_field( 'digitalisimo_editorial_save', 'digitalisimo_editorial_nonce' ); $keywords = array_filter( array_map( 'trim', explode( ',', (string) get_post_meta( $post->ID, 'digitalisimo_seo_keywords', true ) ) ) ); $intent = get_post_meta( $post->ID, 'digitalisimo_seo_search_intent', true ); echo '<div class="digitalisimo-keyword-manager" data-limit="' . esc_attr( min( 20, max( 1, absint( Digitalisimo_Integrations_Settings::get( 'keyword_max_count', 5 ) ) ) ) ) . '"><p class="description">Arrastra una ficha al inicio para convertirla en la palabra clave principal.</p><div class="digitalisimo-keyword-chips"></div><div class="digitalisimo-keyword-add"><input type="text" class="widefat" placeholder="Escribe una palabra clave"><button type="button" class="button button-primary">Añadir</button></div><input type="hidden" class="digitalisimo-keyword-value" name="digitalisimo_editorial_keywords" value="' . esc_attr( implode( ', ', $keywords ) ) . '"></div><p><label><strong>Intención de búsqueda</strong><select class="widefat" name="digitalisimo_editorial_keyword_intent"><option value="">Sin definir</option>'; foreach ( array( 'Informacional', 'Transaccional', 'Navegacional', 'Investigación Comercial' ) as $option ) echo '<option value="' . esc_attr( $option ) . '" ' . selected( $intent, $option, false ) . '>' . esc_html( $option ) . '</option>'; echo '</select></label></p>'; }
	public static function cluster_box( $post ) { wp_nonce_field( 'digitalisimo_editorial_save', 'digitalisimo_editorial_nonce' ); $selected = absint( get_post_meta( $post->ID, '_related_pillar', true ) ); echo '<p><label><input type="checkbox" name="digitalisimo_cluster_pillar" value="1" ' . checked( 'on', get_post_meta( $post->ID, 'digitalisimo_seo_pillar', true ), false ) . '> Marcar como contenido pilar</label></p><p><label><strong>Contenido pilar relacionado</strong><br><select class="widefat" name="digitalisimo_cluster_parent"><option value="">Ninguno</option>'; foreach ( self::cluster_candidates() as $pillar ) if ( $pillar->ID !== $post->ID ) { $type = get_post_type_object( $pillar->post_type ); echo '<option value="' . esc_attr( $pillar->ID ) . '" ' . selected( $selected, $pillar->ID, false ) . '>' . esc_html( ( $type->labels->singular_name ?? $pillar->post_type ) . ' · ' . $pillar->post_title ) . '</option>'; } echo '</select></label></p><p class="description">Sólo muestra contenido público publicado. Al relacionarlo, se marca automáticamente como pilar.</p>'; }
	public static function location_details_box( $post ) { wp_nonce_field( 'digitalisimo_location_save', 'digitalisimo_location_nonce' ); $level = self::location_level( $post->ID ); echo '<p>Construye el catálogo en orden: País → Estado → Ciudad → Zona. Asigna el padre desde Atributos de página.</p><p><label><strong>Tipo de ubicación</strong><br><select name="digitalisimo_location_level"><option value="">Selecciona un tipo</option>'; foreach ( self::location_levels() as $key => $label ) echo '<option value="' . esc_attr( $key ) . '" ' . selected( $level, $key, false ) . '>' . esc_html( $label ) . '</option>'; echo '</select></label></p>'; }
	public static function save_location( $id, $post ) { if ( wp_is_post_revision( $id ) || ! isset( $_POST['digitalisimo_location_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['digitalisimo_location_nonce'] ) ), 'digitalisimo_location_save' ) || ! current_user_can( 'edit_post', $id ) ) return; $level = sanitize_key( $_POST['digitalisimo_location_level'] ?? '' ); if ( array_key_exists( $level, self::location_levels() ) ) update_post_meta( $id, '_digitalisimo_location_level', $level ); else delete_post_meta( $id, '_digitalisimo_location_level' ); }
	public static function location_box( $post ) { wp_nonce_field( 'digitalisimo_editorial_save', 'digitalisimo_editorial_nonce' ); $selected = absint( get_post_meta( $post->ID, '_related_location_id', true ) ); echo '<select class="widefat" name="digitalisimo_location"><option value="">Sin ubicación</option>'; foreach ( self::locations() as $location ) { $level = self::location_level( $location->ID ); echo '<option value="' . esc_attr( $location->ID ) . '" ' . selected( $selected, $location->ID, false ) . '>' . esc_html( self::location_label( $location->ID ) . ( $level ? ' (' . self::location_levels()[ $level ] . ')' : '' ) ) . '</option>'; } echo '</select><p class="description">Elige una ubicación del catálogo. No uses este campo para keywords.</p>'; }
	public static function save( $id ) { if ( wp_is_post_revision( $id ) || ! isset( $_POST['digitalisimo_editorial_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['digitalisimo_editorial_nonce'] ) ), 'digitalisimo_editorial_save' ) || ! current_user_can( 'edit_post', $id ) ) return; $keywords = array_filter( array_map( 'trim', explode( ',', sanitize_text_field( wp_unslash( $_POST['digitalisimo_editorial_keywords'] ?? '' ) ) ) ) ); $limit = min( 20, max( 1, absint( Digitalisimo_Integrations_Settings::get( 'keyword_max_count', 5 ) ) ) ); update_post_meta( $id, 'digitalisimo_seo_keywords', implode( ', ', array_slice( array_unique( $keywords ), 0, $limit ) ) ); update_post_meta( $id, 'digitalisimo_seo_search_intent', sanitize_text_field( wp_unslash( $_POST['digitalisimo_editorial_keyword_intent'] ?? '' ) ) ); update_post_meta( $id, 'digitalisimo_seo_pillar', isset( $_POST['digitalisimo_cluster_pillar'] ) ? 'on' : '' ); $parent = absint( $_POST['digitalisimo_cluster_parent'] ?? 0 ); if ( $parent && $parent !== $id && in_array( get_post_type( $parent ), self::types(), true ) ) { update_post_meta( $id, '_related_pillar', $parent ); update_post_meta( $parent, 'digitalisimo_seo_pillar', 'on' ); } else delete_post_meta( $id, '_related_pillar' ); $location_id = absint( $_POST['digitalisimo_location'] ?? 0 ); if ( $location_id && 'digitalisimo_location' === get_post_type( $location_id ) ) update_post_meta( $id, '_related_location_id', $location_id ); else delete_post_meta( $id, '_related_location_id' ); }
	/** Aplica el pilar global sólo una vez, al crear contenido nuevo, sin tocar los existentes. */
	public static function apply_default_cluster( $post_id, $post, $update, $post_before ) { if ( $update || ! $post || ! in_array( $post->post_type, self::types(), true ) || get_post_meta( $post_id, '_related_pillar', true ) ) return; $pillar = self::cluster_candidate_id( Digitalisimo_Integrations_Settings::get( 'default_cluster_pillar', 0 ) ); if ( $pillar && $pillar !== $post_id ) { update_post_meta( $post_id, '_related_pillar', $pillar ); update_post_meta( $pillar, 'digitalisimo_seo_pillar', 'on' ); } }
	public static function create_location() { if ( ! current_user_can( 'manage_options' ) || ! check_admin_referer( 'digitalisimo_create_location' ) ) wp_die( 'No autorizado.' ); self::locations_cpt(); $name = sanitize_text_field( wp_unslash( $_POST['digitalisimo_location_name'] ?? '' ) ); $level = sanitize_key( $_POST['digitalisimo_location_level'] ?? '' ); $parent = absint( $_POST['digitalisimo_location_parent'] ?? 0 ); $args = array( 'page' => 'digitalisimo-content', 'content_tab' => 'locations' ); if ( ! $name || ! array_key_exists( $level, self::location_levels() ) ) { $args['location_error'] = 'validation'; wp_safe_redirect( add_query_arg( $args, admin_url( 'admin.php' ) ) ); exit; } if ( $parent && 'digitalisimo_location' !== get_post_type( $parent ) ) $parent = 0; $id = wp_insert_post( array( 'post_type' => 'digitalisimo_location', 'post_status' => 'publish', 'post_title' => $name, 'post_parent' => $parent, 'post_author' => get_current_user_id() ), true ); $created = ! is_wp_error( $id ) && absint( $id ) && 'digitalisimo_location' === get_post_type( $id ); if ( $created ) update_post_meta( $id, '_digitalisimo_location_level', $level ); else { $args['location_error'] = is_wp_error( $id ) ? sanitize_key( $id->get_error_code() ) : 'database'; } $args[ $created ? 'location_created' : 'location_error' ] = $created ? '1' : $args['location_error']; wp_safe_redirect( add_query_arg( $args, admin_url( 'admin.php' ) ) ); exit; }
	public static function columns( $columns ) { $columns['digitalisimo_cluster'] = 'Cluster'; $columns['digitalisimo_location'] = 'Ubicación'; return $columns; }
	public static function column_value( $column, $id ) { if ( 'digitalisimo_cluster' === $column ) $item = get_post( absint( get_post_meta( $id, '_related_pillar', true ) ) ); elseif ( 'digitalisimo_location' === $column ) $item = get_post( absint( get_post_meta( $id, '_related_location_id', true ) ) ); else $item = null; if ( $item ) echo esc_html( $item->post_title ); }
	public static function sortable( $columns ) { $columns['digitalisimo_cluster'] = 'digitalisimo_cluster'; $columns['digitalisimo_location'] = 'digitalisimo_location'; return $columns; }
	public static function filters() { global $typenow; if ( ! in_array( $typenow, self::types(), true ) ) return; echo '<select name="digitalisimo_filter_location"><option value="">Todas las ubicaciones</option>'; foreach ( self::locations() as $location ) echo '<option value="' . esc_attr( $location->ID ) . '" ' . selected( absint( $_GET['digitalisimo_filter_location'] ?? 0 ), $location->ID, false ) . '>' . esc_html( $location->post_title ) . '</option>'; echo '</select>'; }
	public static function query( $query ) { if ( ! is_admin() || ! $query->is_main_query() ) return; $order = $query->get( 'orderby' ); $map = array( 'digitalisimo_cluster' => '_related_pillar', 'digitalisimo_location' => '_related_location_id' ); if ( isset( $map[ $order ] ) ) { $query->set( 'meta_key', $map[ $order ] ); $query->set( 'orderby', 'meta_value' ); } $meta = (array) $query->get( 'meta_query' ); if ( isset( $_GET['digitalisimo_filter_location'] ) && absint( $_GET['digitalisimo_filter_location'] ) ) $meta[] = array( 'key' => '_related_location_id', 'value' => absint( $_GET['digitalisimo_filter_location'] ) ); if ( $meta ) $query->set( 'meta_query', $meta ); }
	public static function bulk_fields( $column, $type ) { if ( ! in_array( $type, self::types(), true ) || 'digitalisimo_cluster' !== $column ) return; echo '<fieldset><label>Cluster <select name="digitalisimo_bulk_pillar"><option value="">Sin cambios</option><option value="0">Quitar cluster</option>'; foreach ( self::pillars() as $pillar ) echo '<option value="' . esc_attr( $pillar->ID ) . '">' . esc_html( $pillar->post_title ) . '</option>'; echo '</select></label><label> Ubicación <select name="digitalisimo_bulk_location"><option value="">Sin cambios</option><option value="0">Quitar ubicación</option>'; foreach ( self::locations() as $location ) echo '<option value="' . esc_attr( $location->ID ) . '">' . esc_html( $location->post_title ) . '</option>'; echo '</select></label></fieldset>'; }
	public static function bulk_save() { if ( empty( $_POST['bulk_edit'] ) || empty( $_POST['post_ids'] ) || ! current_user_can( 'edit_posts' ) ) return; foreach ( array_map( 'absint', (array) $_POST['post_ids'] ) as $id ) { foreach ( array( 'pillar' => '_related_pillar', 'location' => '_related_location_id', ) as $field => $key ) { $value = $_POST[ 'digitalisimo_bulk_' . $field ] ?? ''; if ( '' !== $value && current_user_can( 'edit_post', $id ) ) { if ( '0' === $value && in_array( $field, array( 'pillar', 'location' ), true ) ) delete_post_meta( $id, $key ); else update_post_meta( $id, $key, sanitize_text_field( wp_unslash( $value ) ) ); } } } }
}
