<?php
defined( 'ABSPATH' ) || exit;

/** Herramientas editoriales nativas: ubicaciones, clusters y estado de producción. */
class Digitalisimo_Integrations_Editorial {
	public static function init() {
		add_action( 'init', array( __CLASS__, 'locations_cpt' ) ); add_action( 'add_meta_boxes', array( __CLASS__, 'metaboxes' ) ); add_action( 'save_post', array( __CLASS__, 'save' ), 30 );
		// Variables editoriales dinámicas para plantillas de contenido.
		add_shortcode( 'palabra_clave', array( __CLASS__, 'shortcode_primary_keyword' ) );
		add_shortcode( 'palabras_clave_secundarias', array( __CLASS__, 'shortcode_secondary_keywords' ) );
		add_shortcode( 'contenido_pilar', array( __CLASS__, 'shortcode_pillar' ) );
		add_shortcode( 'contenido_secundario', array( __CLASS__, 'shortcode_secondary' ) );
		add_shortcode( 'descripcion_sitio', array( __CLASS__, 'shortcode_site_description' ) );
		add_shortcode( 'digitalisimo_article_chat', array( __CLASS__, 'shortcode_article_chat' ) );
		add_action( 'admin_enqueue_scripts', array( __CLASS__, 'assets' ) );
		add_action( 'wp_enqueue_scripts', array( __CLASS__, 'public_dialogue_assets' ), 20 );
		add_filter( 'manage_post_posts_columns', array( __CLASS__, 'columns' ) ); add_filter( 'manage_page_posts_columns', array( __CLASS__, 'columns' ) ); add_action( 'manage_post_posts_custom_column', array( __CLASS__, 'column_value' ), 10, 2 ); add_action( 'manage_page_posts_custom_column', array( __CLASS__, 'column_value' ), 10, 2 );
		add_filter( 'manage_edit-post_sortable_columns', array( __CLASS__, 'sortable' ) ); add_filter( 'manage_edit-page_sortable_columns', array( __CLASS__, 'sortable' ) ); add_action( 'restrict_manage_posts', array( __CLASS__, 'filters' ) ); add_action( 'pre_get_posts', array( __CLASS__, 'query' ) );
		add_action( 'bulk_edit_custom_box', array( __CLASS__, 'bulk_fields' ), 10, 2 ); add_action( 'admin_action_editpost', array( __CLASS__, 'bulk_save' ) );
	}
	private static function post_keywords( $post_id = 0 ) {
		$post_id = $post_id ?: get_the_ID();
		return array_values( array_filter( array_map( 'trim', explode( ',', (string) get_post_meta( $post_id, 'digitalisimo_seo_keywords', true ) ) ) ) );
	}
	/** Inserta la keyword principal configurada para que una plantilla se actualice al editarla. */
	public static function shortcode_primary_keyword() {
		$keywords = self::post_keywords();
		return esc_html( $keywords[0] ?? '' );
	}
	/** Inserta las keywords secundarias configuradas como una lista semántica. */
	public static function shortcode_secondary_keywords() {
		$keywords = self::post_keywords();
		array_shift( $keywords );
		return $keywords ? '<ul><li>' . implode( '</li><li>', array_map( 'esc_html', $keywords ) ) . '</li></ul>' : '';
	}
	public static function shortcode_pillar() {
		$pillar = get_post( absint( get_post_meta( get_the_ID(), '_related_pillar', true ) ) );
		return $pillar ? '<a href="' . esc_url( get_permalink( $pillar ) ) . '">' . esc_html( $pillar->post_title ) . '</a>' : '';
	}
	public static function shortcode_secondary() {
		$posts = get_posts( array( 'post_type' => array( 'post', 'page' ), 'post_status' => 'publish', 'posts_per_page' => -1, 'meta_key' => '_related_pillar', 'meta_value' => get_the_ID() ) );
		if ( ! $posts ) return '';
		$html = '<ul>';
		foreach ( $posts as $post ) $html .= '<li><a href="' . esc_url( get_permalink( $post ) ) . '">' . esc_html( $post->post_title ) . '</a></li>';
		return $html . '</ul>';
	}
	public static function shortcode_site_description() { return esc_html( get_bloginfo( 'description' ) ); }
	public static function shortcode_article_chat() { $data = json_decode( (string) get_post_meta( get_the_ID(), 'digitalisimo_article_chat', true ), true ); if ( empty( $data['speakers'] ) || empty( $data['messages'] ) ) return ''; $speakers = array(); foreach ( (array) $data['speakers'] as $speaker ) if ( ! empty( $speaker['id'] ) && ! empty( $speaker['name'] ) ) $speakers[ sanitize_key( $speaker['id'] ) ] = $speaker; if ( ! $speakers ) return ''; $html = '<div class="digitalisimo-dialogue digitalisimo-article-chat" aria-label="Conversación">'; foreach ( (array) $data['messages'] as $message ) { $id = sanitize_key( $message['speaker'] ?? '' ); if ( empty( $speakers[ $id ] ) || empty( $message['text'] ) ) continue; $speaker = $speakers[ $id ]; $align = in_array( $speaker['align'] ?? '', array( 'start', 'center', 'end' ), true ) ? $speaker['align'] : 'start'; $avatar = ! empty( $speaker['image_id'] ) ? wp_get_attachment_image( absint( $speaker['image_id'] ), 'thumbnail', false, array( 'class' => 'digitalisimo-chat-avatar' ) ) : '<span class="digitalisimo-chat-icon" aria-hidden="true">' . esc_html( $speaker['icon'] ?? '💬' ) . '</span>'; $html .= '<p class="digitalisimo-dialogue-' . esc_attr( $align ) . '">' . $avatar . '<strong>' . esc_html( $speaker['name'] ) . '</strong>' . esc_html( $message['text'] ) . '</p>'; } return $html . '</div>'; }

	/** Carga el estilo de diálogo sólo si el contenido publicado usa ese bloque. */
	public static function public_dialogue_assets() {
		if ( ! is_singular() ) return;
		$post = get_post();
		if ( ! $post || false === strpos( (string) $post->post_content, 'digitalisimo-dialogue' ) ) return;
		wp_enqueue_style( 'digitalisimo-editorial-dialogue', DIGITALISIMO_INTEGRATIONS_URL . 'assets/editorial-dialogue.css', array(), DIGITALISIMO_INTEGRATIONS_VERSION );
	}
	public static function assets( $hook ) { if ( ! in_array( $hook, array( 'post.php', 'post-new.php' ), true ) ) return; wp_enqueue_style( 'digitalisimo-keyword-manager', DIGITALISIMO_INTEGRATIONS_URL . 'assets/keyword-manager.css', array(), DIGITALISIMO_INTEGRATIONS_VERSION ); wp_enqueue_script( 'digitalisimo-keyword-manager', DIGITALISIMO_INTEGRATIONS_URL . 'assets/keyword-manager.js', array(), DIGITALISIMO_INTEGRATIONS_VERSION, true ); wp_enqueue_media(); wp_enqueue_style( 'digitalisimo-article-chat', DIGITALISIMO_INTEGRATIONS_URL . 'assets/article-chat.css', array(), DIGITALISIMO_INTEGRATIONS_VERSION ); wp_enqueue_script( 'digitalisimo-article-chat', DIGITALISIMO_INTEGRATIONS_URL . 'assets/article-chat.js', array(), DIGITALISIMO_INTEGRATIONS_VERSION, true ); }
	public static function locations_cpt() { register_post_type( 'digitalisimo_location', array( 'labels' => array( 'name' => 'Ubicaciones', 'singular_name' => 'Ubicación', 'add_new_item' => 'Añadir ubicación' ), 'public' => false, 'show_ui' => true, 'show_in_menu' => 'digitalisimo', 'supports' => array( 'title', 'editor' ), 'capability_type' => 'post' ) ); }
	private static function types() { return get_post_types( array( 'public' => true, 'show_ui' => true ), 'names' ); }
	private static function locations() { return get_posts( array( 'post_type' => 'digitalisimo_location', 'posts_per_page' => -1, 'orderby' => 'title', 'order' => 'ASC' ) ); }
	private static function pillars() { return get_posts( array( 'post_type' => self::types(), 'posts_per_page' => -1, 'meta_key' => 'digitalisimo_seo_pillar', 'meta_value' => 'on' ) ); }
	public static function metaboxes() { foreach ( self::types() as $type ) { add_meta_box( 'digitalisimo_keywords_editor', 'Palabras clave', array( __CLASS__, 'keywords_box' ), $type, 'side', 'high' ); add_meta_box( 'digitalisimo_cluster_method', 'Cluster de contenido', array( __CLASS__, 'cluster_box' ), $type, 'side', 'high' ); add_meta_box( 'digitalisimo_location', 'Ubicación', array( __CLASS__, 'location_box' ), $type, 'side' ); add_meta_box( 'digitalisimo_article_chat', 'Chat del artículo', array( __CLASS__, 'chat_box' ), $type, 'normal', 'default' ); } }
	public static function keywords_box( $post ) { wp_nonce_field( 'digitalisimo_editorial_save', 'digitalisimo_editorial_nonce' ); $keywords = array_filter( array_map( 'trim', explode( ',', (string) get_post_meta( $post->ID, 'digitalisimo_seo_keywords', true ) ) ) ); $intent = get_post_meta( $post->ID, 'digitalisimo_seo_search_intent', true ); echo '<div class="digitalisimo-keyword-manager" data-limit="' . esc_attr( min( 20, max( 1, absint( Digitalisimo_Integrations_Settings::get( 'keyword_max_count', 5 ) ) ) ) ) . '"><p class="description">Arrastra una ficha al inicio para convertirla en la palabra clave principal.</p><div class="digitalisimo-keyword-chips"></div><div class="digitalisimo-keyword-add"><input type="text" class="widefat" placeholder="Escribe una palabra clave"><button type="button" class="button button-primary">Añadir</button></div><input type="hidden" class="digitalisimo-keyword-value" name="digitalisimo_editorial_keywords" value="' . esc_attr( implode( ', ', $keywords ) ) . '"></div><p><label><strong>Intención de búsqueda</strong><select class="widefat" name="digitalisimo_editorial_keyword_intent"><option value="">Sin definir</option>'; foreach ( array( 'Informacional', 'Transaccional', 'Navegacional', 'Investigación Comercial' ) as $option ) echo '<option value="' . esc_attr( $option ) . '" ' . selected( $intent, $option, false ) . '>' . esc_html( $option ) . '</option>'; echo '</select></label></p>'; }
	public static function cluster_box( $post ) { wp_nonce_field( 'digitalisimo_editorial_save', 'digitalisimo_editorial_nonce' ); $selected = absint( get_post_meta( $post->ID, '_related_pillar', true ) ); echo '<p><label><input type="checkbox" name="digitalisimo_cluster_pillar" value="1" ' . checked( 'on', get_post_meta( $post->ID, 'digitalisimo_seo_pillar', true ), false ) . '> Marcar como contenido pilar</label></p><p><label><strong>Contenido pilar relacionado</strong><br><select class="widefat" name="digitalisimo_cluster_parent"><option value="">Ninguno</option>'; foreach ( self::pillars() as $pillar ) if ( $pillar->ID !== $post->ID ) echo '<option value="' . esc_attr( $pillar->ID ) . '" ' . selected( $selected, $pillar->ID, false ) . '>' . esc_html( $pillar->post_title ) . '</option>'; echo '</select></label></p><p class="description">Un pilar agrupa contenidos secundarios. Un contenido secundario solo puede pertenecer a un pilar.</p>'; }
	public static function location_box( $post ) { wp_nonce_field( 'digitalisimo_editorial_save', 'digitalisimo_editorial_nonce' ); $selected = absint( get_post_meta( $post->ID, '_related_location_id', true ) ); echo '<select class="widefat" name="digitalisimo_location"><option value="">Sin ubicación</option>'; foreach ( self::locations() as $location ) echo '<option value="' . esc_attr( $location->ID ) . '" ' . selected( $selected, $location->ID, false ) . '>' . esc_html( $location->post_title ) . '</option>'; echo '</select>'; }
	public static function chat_box( $post ) {
		$data = json_decode( (string) get_post_meta( $post->ID, 'digitalisimo_article_chat', true ), true ); $speakers = (array) ( $data['speakers'] ?? array() ); $messages = (array) ( $data['messages'] ?? array() );
		if ( ! $speakers ) $speakers = array( array( 'id' => 'user', 'name' => 'Empresario', 'icon' => '🧑', 'align' => 'end' ), array( 'id' => 'maryia', 'name' => 'MaryIA', 'icon' => '🤖', 'align' => 'center' ), array( 'id' => 'daniel', 'name' => 'Daniel', 'icon' => '👨‍💼', 'align' => 'start' ) ); if ( ! $messages ) $messages = array( array( 'speaker' => 'user', 'text' => 'Tengo una duda sobre este tema.' ), array( 'speaker' => 'maryia', 'text' => 'Consulta recibida. Revisemos los datos.' ), array( 'speaker' => 'daniel', 'text' => 'Lo aterrizamos a una decisión clara.' ) );
		echo '<div class="digitalisimo-article-chat-editor"><p>Agrega personajes y ordena los mensajes como deben verse de arriba hacia abajo. Cada foto se elige desde la Biblioteca; si no hay foto, se usa el icono.</p><h4>Personajes</h4><div class="digitalisimo-chat-speakers">';
		foreach ( $speakers as $speaker ) { $key = sanitize_key( $speaker['id'] ?? uniqid( 'speaker_' ) ); echo '<div class="digitalisimo-chat-speaker"><input type="hidden" name="digitalisimo_article_chat_speakers[' . esc_attr( $key ) . '][id]" value="' . esc_attr( $key ) . '"><label class="digitalisimo-chat-field">Nombre <input class="regular-text digitalisimo-chat-name" name="digitalisimo_article_chat_speakers[' . esc_attr( $key ) . '][name]" value="' . esc_attr( $speaker['name'] ?? '' ) . '"></label> <label class="digitalisimo-chat-field">Icono <input class="small-text" name="digitalisimo_article_chat_speakers[' . esc_attr( $key ) . '][icon]" value="' . esc_attr( $speaker['icon'] ?? '💬' ) . '"></label> <label class="digitalisimo-chat-field">Alineación <select name="digitalisimo_article_chat_speakers[' . esc_attr( $key ) . '][align]">'; foreach ( array( 'start' => 'Izquierda', 'center' => 'Centro', 'end' => 'Derecha' ) as $align => $label ) echo '<option value="' . esc_attr( $align ) . '" ' . selected( $speaker['align'] ?? '', $align, false ) . '>' . esc_html( $label ) . '</option>'; echo '</select></label><input type="hidden" class="digitalisimo-chat-image-id" name="digitalisimo_article_chat_speakers[' . esc_attr( $key ) . '][image_id]" value="' . absint( $speaker['image_id'] ?? 0 ) . '"><button type="button" class="button digitalisimo-chat-media">Elegir foto</button> <span class="digitalisimo-chat-image-status">' . ( ! empty( $speaker['image_id'] ) ? 'Foto seleccionada.' : 'Sin foto: se usará el icono.' ) . '</span> <button type="button" class="button-link-delete digitalisimo-chat-remove-speaker">Quitar personaje</button></div>'; }
		echo '</div><p><button type="button" class="button digitalisimo-chat-add-speaker">Añadir personaje</button></p><h4>Conversación</h4><div class="digitalisimo-chat-messages">'; foreach ( $messages as $message ) echo '<div class="digitalisimo-chat-message"><select class="digitalisimo-chat-message-speaker" name="digitalisimo_article_chat_messages[][speaker]" data-selected="' . esc_attr( $message['speaker'] ?? '' ) . '"></select><textarea rows="2" name="digitalisimo_article_chat_messages[][text]">' . esc_textarea( $message['text'] ?? '' ) . '</textarea><button type="button" class="button-link-delete digitalisimo-chat-remove-message">Quitar</button></div>'; echo '</div><p><button type="button" class="button button-secondary digitalisimo-chat-add-message">Añadir mensaje</button></p><p><code>[digitalisimo_article_chat]</code> inserta la conversación en el lugar elegido.</p></div>';
	}

	public static function save( $id ) { if ( wp_is_post_revision( $id ) || ! isset( $_POST['digitalisimo_editorial_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['digitalisimo_editorial_nonce'] ) ), 'digitalisimo_editorial_save' ) || ! current_user_can( 'edit_post', $id ) ) return; $keywords = array_filter( array_map( 'trim', explode( ',', sanitize_text_field( wp_unslash( $_POST['digitalisimo_editorial_keywords'] ?? '' ) ) ) ) ); $limit = min( 20, max( 1, absint( Digitalisimo_Integrations_Settings::get( 'keyword_max_count', 5 ) ) ) ); update_post_meta( $id, 'digitalisimo_seo_keywords', implode( ', ', array_slice( array_unique( $keywords ), 0, $limit ) ) ); update_post_meta( $id, 'digitalisimo_seo_search_intent', sanitize_text_field( wp_unslash( $_POST['digitalisimo_editorial_keyword_intent'] ?? '' ) ) ); update_post_meta( $id, 'digitalisimo_seo_pillar', isset( $_POST['digitalisimo_cluster_pillar'] ) ? 'on' : '' ); $parent = absint( $_POST['digitalisimo_cluster_parent'] ?? 0 ); if ( $parent && $parent !== $id ) update_post_meta( $id, '_related_pillar', $parent ); else delete_post_meta( $id, '_related_pillar' ); update_post_meta( $id, '_related_location_id', absint( $_POST['digitalisimo_location'] ?? 0 ) ); if ( isset( $_POST['digitalisimo_article_chat_speakers'] ) ) { $speakers = array(); foreach ( (array) $_POST['digitalisimo_article_chat_speakers'] as $row ) { $key = sanitize_key( $row['id'] ?? '' ); $name = sanitize_text_field( $row['name'] ?? '' ); if ( $key && $name ) $speakers[] = array( 'id' => $key, 'name' => $name, 'icon' => sanitize_text_field( $row['icon'] ?? '💬' ), 'image_id' => absint( $row['image_id'] ?? 0 ), 'align' => in_array( $row['align'] ?? '', array( 'start', 'center', 'end' ), true ) ? $row['align'] : 'start' ); } $ids = wp_list_pluck( $speakers, 'id' ); $messages = array(); foreach ( (array) ( $_POST['digitalisimo_article_chat_messages'] ?? array() ) as $row ) { $speaker = sanitize_key( $row['speaker'] ?? '' ); $text = sanitize_textarea_field( $row['text'] ?? '' ); if ( $text && in_array( $speaker, $ids, true ) ) $messages[] = array( 'speaker' => $speaker, 'text' => $text ); } update_post_meta( $id, 'digitalisimo_article_chat', wp_json_encode( array( 'speakers' => $speakers, 'messages' => $messages ), JSON_UNESCAPED_UNICODE ) ); } }
	public static function columns( $columns ) { $columns['digitalisimo_cluster'] = 'Cluster'; $columns['digitalisimo_location'] = 'Ubicación'; return $columns; }
	public static function column_value( $column, $id ) { if ( 'digitalisimo_cluster' === $column ) $item = get_post( absint( get_post_meta( $id, '_related_pillar', true ) ) ); elseif ( 'digitalisimo_location' === $column ) $item = get_post( absint( get_post_meta( $id, '_related_location_id', true ) ) ); else $item = null; if ( $item ) echo esc_html( $item->post_title ); }
	public static function sortable( $columns ) { $columns['digitalisimo_cluster'] = 'digitalisimo_cluster'; $columns['digitalisimo_location'] = 'digitalisimo_location'; return $columns; }
	public static function filters() { global $typenow; if ( ! in_array( $typenow, self::types(), true ) ) return; echo '<select name="digitalisimo_filter_location"><option value="">Todas las ubicaciones</option>'; foreach ( self::locations() as $location ) echo '<option value="' . esc_attr( $location->ID ) . '" ' . selected( absint( $_GET['digitalisimo_filter_location'] ?? 0 ), $location->ID, false ) . '>' . esc_html( $location->post_title ) . '</option>'; echo '</select>'; }
	public static function query( $query ) { if ( ! is_admin() || ! $query->is_main_query() ) return; $order = $query->get( 'orderby' ); $map = array( 'digitalisimo_cluster' => '_related_pillar', 'digitalisimo_location' => '_related_location_id' ); if ( isset( $map[ $order ] ) ) { $query->set( 'meta_key', $map[ $order ] ); $query->set( 'orderby', 'meta_value' ); } $meta = (array) $query->get( 'meta_query' ); if ( isset( $_GET['digitalisimo_filter_location'] ) && absint( $_GET['digitalisimo_filter_location'] ) ) $meta[] = array( 'key' => '_related_location_id', 'value' => absint( $_GET['digitalisimo_filter_location'] ) ); if ( $meta ) $query->set( 'meta_query', $meta ); }
	public static function bulk_fields( $column, $type ) { if ( ! in_array( $type, self::types(), true ) || 'digitalisimo_cluster' !== $column ) return; echo '<fieldset><label>Cluster <select name="digitalisimo_bulk_pillar"><option value="">Sin cambios</option><option value="0">Quitar cluster</option>'; foreach ( self::pillars() as $pillar ) echo '<option value="' . esc_attr( $pillar->ID ) . '">' . esc_html( $pillar->post_title ) . '</option>'; echo '</select></label><label> Ubicación <select name="digitalisimo_bulk_location"><option value="">Sin cambios</option><option value="0">Quitar ubicación</option>'; foreach ( self::locations() as $location ) echo '<option value="' . esc_attr( $location->ID ) . '">' . esc_html( $location->post_title ) . '</option>'; echo '</select></label></fieldset>'; }
	public static function bulk_save() { if ( empty( $_POST['bulk_edit'] ) || empty( $_POST['post_ids'] ) || ! current_user_can( 'edit_posts' ) ) return; foreach ( array_map( 'absint', (array) $_POST['post_ids'] ) as $id ) { foreach ( array( 'pillar' => '_related_pillar', 'location' => '_related_location_id', ) as $field => $key ) { $value = $_POST[ 'digitalisimo_bulk_' . $field ] ?? ''; if ( '' !== $value && current_user_can( 'edit_post', $id ) ) { if ( '0' === $value && in_array( $field, array( 'pillar', 'location' ), true ) ) delete_post_meta( $id, $key ); else update_post_meta( $id, $key, sanitize_text_field( wp_unslash( $value ) ) ); } } } }
}
