<?php
defined( 'ABSPATH' ) || exit;
final class Digitalisimo_Plugin_Catalog {
	const ACTION = 'digitalisimo_install_catalog_plugin';
	public static function init() { add_action( 'admin_post_' . self::ACTION, array( __CLASS__, 'install' ) ); add_action( 'admin_menu', array( __CLASS__, 'menu' ), 99 ); if ( is_multisite() ) add_action( 'network_admin_menu', array( __CLASS__, 'network_menu' ), 99 ); }
	public static function menu() { add_submenu_page( 'digitalisimo', 'Plugins · Digitalisimo', 'Plugins', 'install_plugins', 'digitalisimo-plugins', array( __CLASS__, 'page' ) ); }
	public static function network_menu() { add_submenu_page( 'digitalisimo-network', 'Plugins · Digitalisimo', 'Plugins', 'manage_network_plugins', 'digitalisimo-plugins', array( __CLASS__, 'page' ) ); }
	private static function plugins() { return array( 'digitalisimo-ecommerce' => array( 'Ecommerce', 'digitalisimo-ecommerce/digitalisimo-ecommerce.php' ), 'digitalisimo-ia-tools' => array( 'IA Tools', 'digitalisimo.chatbot/digitalisimo-chatbot.php' ), 'digitalisimo-hosting' => array( 'Hosting', 'digitalisimo-hosting/digitalisimo-hosting.php' ), 'digitalisimo-backups' => array( 'Backups', 'digitalisimo-backups/digitalisimo-backups.php' ), 'digitalisimo-tools' => array( 'DIGITALÍSIMO Tools', 'digitalisimo-tools/digitalisimo-tools.php' ) ); }
	private static function releases() { $r = wp_remote_get( 'https://api.github.com/repos/danbutanda/digitalisimo-plugin/releases?per_page=50', array( 'timeout' => 12, 'headers' => array( 'User-Agent' => 'Digitalisimo-Catalog' ) ) ); $out = array(); if ( ! is_wp_error( $r ) ) foreach ( (array) json_decode( wp_remote_retrieve_body( $r ), true ) as $release ) foreach ( (array) ( $release['assets'] ?? array() ) as $asset ) if ( preg_match( '/^(digitalisimo-[a-z-]+)-([0-9.]+)\.zip$/', $asset['name'] ?? '', $m ) && ( empty( $out[ $m[1] ] ) || version_compare( $m[2], $out[ $m[1] ]['version'], '>' ) ) ) $out[ $m[1] ] = array( 'version' => $m[2], 'package' => esc_url_raw( $asset['browser_download_url'] ?? '' ) ); return $out; }
	public static function page() { if ( ! current_user_can( is_multisite() ? 'manage_network_plugins' : 'install_plugins' ) ) return; $releases = self::releases(); echo '<div class="wrap"><h1>Plugins · Digitalisimo</h1><table class="widefat striped"><tbody>'; foreach ( self::plugins() as $slug => $p ) { $installed = file_exists( WP_PLUGIN_DIR . '/' . $p[1] ); echo '<tr><td><strong>' . esc_html( $p[0] ) . '</strong></td><td>' . esc_html( $releases[ $slug ]['version'] ?? 'Sin Release' ) . '</td><td>' . ( $installed ? 'Instalado' : 'Disponible' ) . '</td><td>'; if ( ! $installed && ! empty( $releases[ $slug ]['package'] ) ) echo '<a class="button button-primary" href="' . esc_url( wp_nonce_url( add_query_arg( array( 'action' => self::ACTION, 'slug' => $slug ), admin_url( 'admin-post.php' ) ), self::ACTION . $slug ) ) . '">Instalar</a>'; echo '</td></tr>'; } echo '</tbody></table></div>'; }
	public static function install() { $slug = sanitize_key( $_GET['slug'] ?? '' ); check_admin_referer( self::ACTION . $slug ); if ( ! current_user_can( is_multisite() ? 'manage_network_plugins' : 'install_plugins' ) ) wp_die( 'No autorizado.' ); $release = self::releases()[ $slug ] ?? array(); if ( empty( $release['package'] ) ) wp_die( 'Paquete no disponible.' ); require_once ABSPATH . 'wp-admin/includes/class-wp-upgrader.php'; require_once ABSPATH . 'wp-admin/includes/file.php'; ( new Plugin_Upgrader( new Automatic_Upgrader_Skin() ) )->install( $release['package'] ); wp_safe_redirect( is_multisite() ? network_admin_url( 'plugins.php' ) : admin_url( 'plugins.php' ) ); exit; }
}
