<?php
defined( 'ABSPATH' ) || exit;
/** Método editorial único consumible por WordPress, API y clientes MCP. */
class Digitalisimo_Integrations_Content_Playbook {
	public static function defaults() { return array(
		'content_editorial_voice' => 'Tono amigable, cercano y experto en tecnología. Explica con claridad, usa español de México y evita promesas de posicionamiento garantizado.',
		'content_editorial_context' => 'Digitalisimo es una agencia digital mexicana. Combina SEO, marketing, desarrollo web, automatización e inteligencia digital para ayudar a empresas a crecer.',
		'content_editorial_cta' => 'Cierra con una invitación útil a solicitar una asesoría con Digitalisimo, relacionada de forma natural con el tema del artículo.',
		'content_editorial_method' => 'Responde la intención de búsqueda al inicio. No repitas el H1 en el cuerpo. Usa una keyword principal de forma natural y secundarias sólo cuando aporten contexto. Organiza con H2 y H3, ejemplos, preguntas frecuentes y enlaces internos reales. Puedes abrir con un diálogo breve entre 🧑 Empresario, 🤖 MaryIA y 👨‍💼 Daniel; MaryIA habla con precisión robótica y Daniel aterriza decisiones. El diálogo aparece una sola vez al inicio.',
	); }
	public static function profile() { $out = array(); foreach ( self::defaults() as $key => $value ) $out[ str_replace( 'content_editorial_', '', $key ) ] = (string) Digitalisimo_Integrations_Settings::get( $key, $value ); return $out; }
	public static function prompt( $primary, $secondary = array(), $title = '' ) { $p = self::profile(); return "Método editorial DIGITALISIMO:\nVoz: {$p['voice']}\nContexto: {$p['context']}\nCTA: {$p['cta']}\nReglas: {$p['method']}\n\nKeyword principal: {$primary}\nKeywords secundarias: " . implode( ', ', array_map( 'sanitize_text_field', (array) $secondary ) ) . "\nTítulo sugerido: {$title}\n\nDevuelve JSON válido con title, seo_title, meta_description (120-160 caracteres), secondary_keywords y content (HTML sin H1)."; }
	public static function generate( $primary, $secondary = array(), $title = '' ) { if ( ! class_exists( 'Digitalisimo_AI' ) ) return new WP_Error( 'digitalisimo_ai_missing', 'Activa Digitalisimo IA Tools y configura un proveedor para generar contenido.' ); $answer = Digitalisimo_AI::complete( 'content', self::prompt( $primary, $secondary, $title ), 'Genera solamente el JSON solicitado; usa datos proporcionados y no inventes servicios, resultados ni enlaces.' ); if ( is_wp_error( $answer ) ) return $answer; $data = json_decode( trim( preg_replace( '/^```(?:json)?|```$/m', '', $answer ) ), true ); if ( ! is_array( $data ) || empty( $data['content'] ) || empty( $data['title'] ) || empty( $data['meta_description'] ) ) return new WP_Error( 'digitalisimo_ai_format', 'La IA no devolvió un borrador estructurado válido.' ); $data['content'] = preg_replace( '#^\s*<h1\b[^>]*>.*?</h1>\s*#is', '', wp_kses_post( $data['content'] ), 1 ); return $data; }
}
