<?php
defined( 'ABSPATH' ) || exit;

/** Lee una URL pública propia y presenta las señales SEO que realmente devolvió el front. */
class Digitalisimo_Integrations_SEO_Front_Inspector {
	private static function same_site_url( $url ) {
		$parts = wp_parse_url( $url ); $home = wp_parse_url( home_url( '/' ) );
		return ! empty( $parts['scheme'] ) && ! empty( $parts['host'] ) && empty( $parts['user'] ) && empty( $parts['pass'] ) && isset( $home['host'] ) && strtolower( $parts['host'] ) === strtolower( $home['host'] ) && in_array( strtolower( $parts['scheme'] ), array( 'http', 'https' ), true );
	}
	private static function resolve_url( $base, $location ) {
		$location = trim( html_entity_decode( (string) $location, ENT_QUOTES, get_bloginfo( 'charset' ) ) );
		if ( preg_match( '#^https?://#i', $location ) ) return $location;
		$parts = wp_parse_url( $base ); $origin = ( $parts['scheme'] ?? 'https' ) . '://' . ( $parts['host'] ?? '' ) . ( isset( $parts['port'] ) ? ':' . $parts['port'] : '' );
		if ( 0 === strpos( $location, '//' ) ) return ( $parts['scheme'] ?? 'https' ) . ':' . $location;
		if ( 0 === strpos( $location, '/' ) ) return $origin . $location;
		$path = isset( $parts['path'] ) ? $parts['path'] : '/';
		return $origin . trailingslashit( dirname( $path ) ) . $location;
	}
	private static function fetch( $url ) {
		$current = $url; $redirects = array(); $insecure_tls = false;
		for ( $step = 0; $step < 6; $step++ ) {
			if ( ! self::same_site_url( $current ) ) return new WP_Error( 'digitalisimo_front_url', 'La URL y sus redirecciones deben permanecer en este mismo sitio.' );
			$response = wp_safe_remote_get( $current, array( 'timeout' => 15, 'redirection' => 0, 'limit_response_size' => 1048576, 'user-agent' => 'Digitalisimo Front Inspector/1.0', 'headers' => array( 'Cache-Control' => 'no-cache' ) ) );
			if ( is_wp_error( $response ) && ( false !== stripos( $response->get_error_message(), 'cURL error 60' ) || false !== stripos( $response->get_error_message(), 'certificate' ) ) ) {
				$response = wp_safe_remote_get( $current, array( 'timeout' => 15, 'redirection' => 0, 'limit_response_size' => 1048576, 'sslverify' => false, 'user-agent' => 'Digitalisimo Front Inspector/1.0', 'headers' => array( 'Cache-Control' => 'no-cache' ) ) );
				$insecure_tls = ! is_wp_error( $response );
			}
			if ( is_wp_error( $response ) ) return $response;
			$code = (int) wp_remote_retrieve_response_code( $response ); $location = wp_remote_retrieve_header( $response, 'location' );
			if ( $code >= 300 && $code < 400 && $location ) { $next = self::resolve_url( $current, $location ); $redirects[] = array( 'code' => $code, 'from' => $current, 'to' => $next ); $current = $next; continue; }
			return array( 'url' => $current, 'response' => $response, 'redirects' => $redirects, 'insecure_tls' => $insecure_tls );
		}
		return new WP_Error( 'digitalisimo_front_redirect', 'La URL superó el máximo de cinco redirecciones.' );
	}
	private static function head( $html ) { return preg_match( '#<head\b[^>]*>(.*?)</head\s*>#is', $html, $match ) ? $match[1] : ''; }
	private static function attributes( $tag ) {
		$attrs = array(); preg_match_all( '/([a-zA-Z_:][-a-zA-Z0-9_:.]*)\s*=\s*(?:"([^"]*)"|\'([^\']*)\'|([^\s>]+))/s', $tag, $matches, PREG_SET_ORDER );
		foreach ( $matches as $match ) $attrs[ strtolower( $match[1] ) ] = html_entity_decode( $match[2] !== '' ? $match[2] : ( $match[3] !== '' ? $match[3] : $match[4] ), ENT_QUOTES, get_bloginfo( 'charset' ) );
		return $attrs;
	}
	private static function tags( $html, $name ) { preg_match_all( '#<' . preg_quote( $name, '#' ) . '\b[^>]*>#is', $html, $matches ); return $matches[0]; }
	private static function meta( $head ) {
		$meta = array(); foreach ( self::tags( $head, 'meta' ) as $tag ) { $attrs = self::attributes( $tag ); $key = strtolower( $attrs['name'] ?? ( $attrs['property'] ?? ( $attrs['http-equiv'] ?? '' ) ) ); if ( $key ) { if ( ! isset( $meta[ $key ] ) ) $meta[ $key ] = array(); $meta[ $key ][] = $attrs['content'] ?? ''; } } return $meta;
	}
	private static function links( $head ) {
		$links = array(); foreach ( self::tags( $head, 'link' ) as $tag ) { $attrs = self::attributes( $tag ); if ( ! empty( $attrs['rel'] ) ) $links[] = $attrs; } return $links;
	}
	private static function schema_types( $value, &$types ) {
		if ( ! is_array( $value ) ) return;
		if ( ! empty( $value['@type'] ) ) foreach ( (array) $value['@type'] as $type ) $types[] = (string) $type;
		foreach ( $value as $item ) self::schema_types( $item, $types );
	}
	private static function schema_ids( $value, &$ids ) {
		if ( ! is_array( $value ) ) return;
		// Un @id sin @type es una referencia a una entidad, no una segunda definición.
		if ( ! empty( $value['@id'] ) && ! empty( $value['@type'] ) ) $ids[] = (string) $value['@id'];
		foreach ( $value as $item ) self::schema_ids( $item, $ids );
	}
	private static function schemas( $head ) {
		$out = array(); preg_match_all( '#<script\b[^>]*type\s*=\s*(["\'])application/ld\+json\1[^>]*>(.*?)</script\s*>#is', $head, $matches, PREG_SET_ORDER );
		foreach ( $matches as $match ) { $raw = trim( html_entity_decode( $match[2], ENT_NOQUOTES, get_bloginfo( 'charset' ) ) ); $data = json_decode( $raw, true ); $types = array(); $ids = array(); if ( JSON_ERROR_NONE === json_last_error() ) { self::schema_types( $data, $types ); self::schema_ids( $data, $ids ); } $out[] = array( 'valid' => JSON_ERROR_NONE === json_last_error(), 'error' => json_last_error_msg(), 'types' => array_values( array_unique( array_filter( $types ) ) ), 'ids' => array_values( array_filter( $ids ) ) ); }
		return $out;
	}
	private static function values( $items ) { return array_values( array_filter( array_map( 'trim', (array) $items ), 'strlen' ) ); }
	private static function item( $label, $values, $empty = 'No detectado' ) { echo '<tr><th scope="row">' . esc_html( $label ) . '</th><td>' . ( $values ? esc_html( implode( "\n", $values ) ) : '<span class="digitalisimo-front-missing">' . esc_html( $empty ) . '</span>' ) . '</td></tr>'; }
	private static function configured( $key ) { return (bool) Digitalisimo_Integrations_Settings::get( $key ); }
	public static function render() {
		$url = home_url( '/' ); $report = null; $error = '';
		if ( isset( $_POST['digitalisimo_front_inspect'] ) && check_admin_referer( 'digitalisimo_front_inspect' ) ) {
			$url = esc_url_raw( wp_unslash( $_POST['digitalisimo_front_url'] ?? '' ) );
			if ( ! self::same_site_url( $url ) ) $error = 'Escribe una URL pública de este mismo sitio.';
			else { $fetched = self::fetch( $url ); if ( is_wp_error( $fetched ) ) $error = $fetched->get_error_message(); else $report = $fetched; }
		}
		echo '<section class="digitalisimo-front-inspector"><h2>SEO Front</h2><p>Lee la respuesta pública y anónima de una URL de este sitio. Muestra las señales que están realmente en el HTML; no cambia contenido ni configuración.</p><form method="post" class="digitalisimo-front-form">'; wp_nonce_field( 'digitalisimo_front_inspect' ); echo '<label for="digitalisimo_front_url">URL pública</label><input id="digitalisimo_front_url" class="large-text" name="digitalisimo_front_url" type="url" required value="' . esc_attr( $url ) . '">'; submit_button( 'Inspeccionar front', 'primary', 'digitalisimo_front_inspect', false ); echo '</form>';
		if ( $error ) { echo '<div class="notice notice-error inline"><p>' . esc_html( $error ) . '</p></div></section>'; return; }
		if ( ! $report ) { echo '<p class="description">Selecciona una página, entrada o producto publicado para revisar title, metas, social, canonical, robots y Schema tal como salen al front.</p></section>'; return; }
		$response = $report['response']; $body = (string) wp_remote_retrieve_body( $response ); $head = self::head( $body ); $meta = self::meta( $head ); $links = self::links( $head ); $schemas = self::schemas( $head ); $canonicals = array(); $hreflangs = array(); $pagination = array();
		if ( ! empty( $report['insecure_tls'] ) ) echo '<div class="notice notice-warning inline"><p>El servidor que ejecuta WordPress no pudo validar el certificado SSL de este mismo dominio y se consultó únicamente esta URL propia sin esa validación. El informe se generó; revisa la resolución DNS, SNI o cadena de certificados desde el hosting. Esto no confirma por sí solo un fallo para visitantes externos.</p></div>';
		foreach ( $links as $link ) { $rels = preg_split( '/\s+/', strtolower( $link['rel'] ) ); if ( in_array( 'canonical', $rels, true ) && ! empty( $link['href'] ) ) $canonicals[] = $link['href']; if ( in_array( 'alternate', $rels, true ) && ! empty( $link['hreflang'] ) && ! empty( $link['href'] ) ) $hreflangs[] = $link['hreflang'] . ': ' . $link['href']; if ( ( in_array( 'next', $rels, true ) || in_array( 'prev', $rels, true ) ) && ! empty( $link['href'] ) ) $pagination[] = implode( ' ', $rels ) . ': ' . $link['href']; }
		preg_match_all( '#<title\b[^>]*>(.*?)</title\s*>#is', $head, $titles ); $titles = array_map( function( $title ) { return trim( wp_strip_all_tags( html_entity_decode( $title, ENT_QUOTES, get_bloginfo( 'charset' ) ) ) ); }, $titles[1] ?? array() ); $charsets = array(); foreach ( self::tags( $head, 'meta' ) as $tag ) { $attrs = self::attributes( $tag ); if ( ! empty( $attrs['charset'] ) ) $charsets[] = $attrs['charset']; }
		preg_match( '#<html\b[^>]*>#i', $body, $html_tag ); $html_attrs = ! empty( $html_tag[0] ) ? self::attributes( $html_tag[0] ) : array(); $headings = array(); preg_match_all( '#<h([1-6])\b[^>]*>(.*?)</h\1\s*>#is', $body, $heading_matches, PREG_SET_ORDER ); foreach ( $heading_matches as $heading ) { $text = trim( wp_strip_all_tags( html_entity_decode( $heading[2], ENT_QUOTES, get_bloginfo( 'charset' ) ) ) ); if ( $text ) $headings[] = array( 'level' => 'H' . $heading[1], 'text' => $text ); } $h1_count = count( array_filter( $headings, function( $heading ) { return 'H1' === $heading['level']; } ) ); $images = self::tags( $body, 'img' ); $image_rows = array(); $missing_alt = 0; $missing_image_title = 0; foreach ( $images as $image ) { $attrs = self::attributes( $image ); if ( empty( trim( $attrs['alt'] ?? '' ) ) ) $missing_alt++; if ( empty( $attrs['title'] ) ) $missing_image_title++; $image_rows[] = array( 'src' => $attrs['src'] ?? '', 'alt' => $attrs['alt'] ?? '', 'title' => $attrs['title'] ?? '' ); } $anchors = self::tags( $body, 'a' ); $internal_links = 0; $external_links = 0; $home_host = strtolower( (string) wp_parse_url( home_url( '/' ), PHP_URL_HOST ) ); $link_rows = array(); foreach ( $anchors as $anchor ) { $attrs = self::attributes( $anchor ); $href = trim( $attrs['href'] ?? '' ); if ( ! $href || 0 === strpos( $href, '#' ) || preg_match( '#^(mailto:|tel:|javascript:)#i', $href ) ) continue; $host = strtolower( (string) wp_parse_url( $href, PHP_URL_HOST ) ); $kind = ( ! $host || $host === $home_host ) ? 'Interno' : 'Externo'; if ( 'Interno' === $kind ) $internal_links++; else $external_links++; if ( ! isset( $link_rows[ $href ] ) ) $link_rows[ $href ] = array( 'count' => 0, 'kind' => $kind, 'title' => $attrs['title'] ?? '', 'rel' => $attrs['rel'] ?? '' ); $link_rows[ $href ]['count']++; } $script_rows = array(); foreach ( self::tags( $head, 'script' ) as $script ) { $attrs = self::attributes( $script ); if ( ! empty( $attrs['src'] ) ) $script_rows[] = $attrs['src']; }
		foreach ( $image_rows as &$image ) { $image['url'] = self::resolve_url( $report['url'], $image['src'] ); $image['origin'] = strtolower( (string) wp_parse_url( $image['url'], PHP_URL_HOST ) ) === $home_host ? 'Biblioteca / propio' : 'Externa'; } unset( $image );
		$schema_types = array(); $schema_ids = array(); $invalid_schema = 0; foreach ( $schemas as $schema ) { $schema_types = array_merge( $schema_types, $schema['types'] ); $schema_ids = array_merge( $schema_ids, $schema['ids'] ); if ( ! $schema['valid'] ) $invalid_schema++; } $schema_types = array_values( array_unique( $schema_types ) ); $duplicate_schema_ids = array_keys( array_filter( array_count_values( $schema_ids ), function( $count ) { return $count > 1; } ) );
		$link_title_missing = count( array_filter( $link_rows, function( $link ) { return empty( trim( $link['title'] ) ); } ) ); $duplicate_links = count( array_filter( $link_rows, function( $link ) { return $link['count'] > 3; } ) ); $post_id = url_to_postid( $report["url"] ); $configured_keywords = $post_id ? (string) get_post_meta( $post_id, "digitalisimo_seo_keywords", true ) : implode( ", ", (array) ( $meta["keywords"] ?? array() ) ); $keyword_list = array_values( array_filter( array_map( "trim", explode( ",", $configured_keywords ) ) ) ); $primary_keyword = $keyword_list[0] ?? ""; $front_text = function_exists( 'mb_strtolower' ) ? mb_strtolower( wp_strip_all_tags( $body ) ) : strtolower( wp_strip_all_tags( $body ) ); $contains = function( $value, $keyword ) { return $keyword && false !== ( function_exists( 'mb_stripos' ) ? mb_stripos( (string) $value, $keyword ) : stripos( (string) $value, $keyword ) ); }; $context_checks = array( "Title" => $contains( implode( " ", $titles ), $primary_keyword ), "Descripción" => $contains( implode( " ", (array) ( $meta["description"] ?? array() ) ), $primary_keyword ), "H1" => ! empty( $headings[0] ) && $contains( $headings[0]["text"], $primary_keyword ), "URL" => $contains( $report["url"], sanitize_title( $primary_keyword ) ), "Contenido" => $contains( $front_text, $primary_keyword ) ); $context_score = $primary_keyword ? (int) round( 100 * count( array_filter( $context_checks ) ) / count( $context_checks ) ) : 0; $description_length = strlen( wp_strip_all_tags( implode( ' ', (array) ( $meta['description'] ?? array() ) ) ) ); $scores = array( 'summary' => (int) round( 100 * ( ( 1 === count( $titles ) ) + ( 1 === count( $meta['description'] ?? array() ) && $description_length >= 120 && $description_length <= 160 ) + ! empty( $meta['keywords'] ) + ( 1 === count( $canonicals ) ) + ! empty( $meta['robots'] ) + ! empty( $html_attrs['lang'] ) + ! empty( $meta['author'] ) ) / 7 ), 'headers' => (int) round( 100 * ( ( 1 === $h1_count ) + ! empty( $headings ) + empty( array_filter( $headings, function( $h ) { return in_array( $h['level'], array( 'H5', 'H6' ), true ); } ) ) ) / 3 ), 'images' => $images ? (int) round( 100 * ( count( $images ) - $missing_alt ) / count( $images ) ) : 50, 'links' => $link_rows ? (int) round( 100 * ( ( count( $link_rows ) - $link_title_missing ) / count( $link_rows ) + ( $internal_links > 0 ? 1 : 0 ) + ( 0 === $duplicate_links ? 1 : 0 ) ) / 3 ) : 0, 'social' => (int) round( 100 * ( ! empty( $meta['og:title'] ) + ! empty( $meta['og:description'] ) + ! empty( $meta['og:image'] ) + ! empty( $meta['twitter:card'] ) + ! $invalid_schema + ! $duplicate_schema_ids ) / 6 ) ); $scores['global'] = (int) round( array_sum( $scores ) / 5 );
		$secondary_keywords = array_slice( $keyword_list, 1 );
		$tabs = array( 'summary' => 'Resumen', 'headers' => 'Encabezados', 'images' => 'Imágenes', 'links' => 'Enlaces', 'social' => 'Social', 'tools' => 'Herramientas' ); echo '<div class="digitalisimo-front-score"><span class="digitalisimo-score-ring" style="--score:' . absint( $scores['global'] ) . '"><strong>' . absint( $scores['global'] ) . '</strong><small>/100</small></span><p><strong>SEO Front</strong><br>Puntaje técnico de la respuesta publicada.</p></div><p class="digitalisimo-content-links digitalisimo-front-tabs">'; foreach ( $tabs as $tab => $label ) { $score = $scores[ $tab ] ?? null; echo '<a class="button ' . ( 'summary' === $tab ? 'button-primary' : 'button-secondary' ) . '" data-front-tab="' . esc_attr( $tab ) . '" href="#' . esc_attr( $tab ) . '">' . esc_html( $label ) . ( null !== $score ? ' <span class="digitalisimo-score-ring digitalisimo-score-ring-small" style="--score:' . absint( $score ) . '">' . absint( $score ) . '</span>' : '' ) . '</a>'; } echo '</p><div class="digitalisimo-front-body">';
		echo '<section data-front-panel="summary"><h3>Keyword principal: ' . esc_html( $primary_keyword ?: 'Sin configurar' ) . '</h3><p><strong>Relevancia de landing: ' . absint( $context_score ) . '/100</strong></p><ul class="digitalisimo-front-warnings">'; foreach ( $context_checks as $label => $ok ) echo '<li>' . ( $ok ? '✓' : '⚠' ) . ' ' . esc_html( $label ) . ( $ok ? '' : ': incorpora la keyword principal.' ) . '</li>'; echo '</ul><h3>Resumen técnico</h3><table class="widefat striped digitalisimo-front-table"><tbody>'; self::item( 'Estado HTTP', array( 'HTTP ' . (int) wp_remote_retrieve_response_code( $response ) . ' · ' . $report['url'] ) ); self::item( 'Redirecciones', array_map( function( $redirect ) { return 'HTTP ' . $redirect['code'] . ': ' . $redirect['from'] . ' → ' . $redirect['to']; }, $report['redirects'] ), 'Sin redirecciones' ); self::item( 'Title (' . count( $titles ) . ')', self::values( $titles ) ); self::item( 'Meta description (' . count( $meta['description'] ?? array() ) . ')', self::values( $meta['description'] ?? array() ) ); self::item( 'Meta keywords (' . count( $meta['keywords'] ?? array() ) . ')', self::values( $meta['keywords'] ?? array() ) ); self::item( 'Canonical (' . count( $canonicals ) . ')', self::values( $canonicals ) ); self::item( 'Robots', self::values( array_merge( $meta['robots'] ?? array(), $meta['googlebot'] ?? array() ) ) ); self::item( 'Autor', self::values( $meta['author'] ?? array() ) ); self::item( 'Publisher', self::values( $meta['publisher'] ?? array() ) ); self::item( 'Idioma HTML', self::values( array( $html_attrs['lang'] ?? '' ) ) ); self::item( 'Encabezados', array( 'H1: ' . $h1_count . ' · H2: ' . count( array_filter( $headings, function( $h ) { return 'H2' === $h['level']; } ) ) . ' · H3: ' . count( array_filter( $headings, function( $h ) { return 'H3' === $h['level']; } ) ) . ' · H4: ' . count( array_filter( $headings, function( $h ) { return 'H4' === $h['level']; } ) ) . ' · H5: ' . count( array_filter( $headings, function( $h ) { return 'H5' === $h['level']; } ) ) . ' · H6: ' . count( array_filter( $headings, function( $h ) { return 'H6' === $h['level']; } ) ) ) ); self::item( 'Imágenes y enlaces', array( count( $images ) . ' imágenes · ' . count( $link_rows ) . ' enlaces únicos' ) ); echo '</tbody></table></section>';
		echo '<section data-front-panel="headers" hidden><h3>Índice de encabezados</h3><p class="description">Titulares en el orden real del HTML.</p><table class="widefat striped digitalisimo-front-table"><thead><tr><th>Tipo</th><th>Título</th></tr></thead><tbody>'; foreach ( $headings as $heading ) echo '<tr><td><strong>' . esc_html( $heading['level'] ) . '</strong></td><td>' . esc_html( $heading['text'] ) . '</td></tr>'; if ( ! $headings ) echo '<tr><td colspan="2">No se detectaron encabezados H1–H6.</td></tr>'; echo '</tbody></table></section>';
		echo '<section data-front-panel="images" hidden><h3>Imágenes · ' . absint( $scores['images'] ) . '/100</h3><p>' . esc_html( count( $images ) . ' detectadas · ' . $missing_alt . ' sin alt · ' . $missing_image_title . ' sin title. El atributo title no es obligatorio para SEO; alt sí aporta contexto cuando la imagen no es decorativa.' ) . '</p><table class="widefat striped digitalisimo-front-table"><thead><tr><th>Miniatura</th><th>Origen</th><th>Alt</th><th>Title</th></tr></thead><tbody>'; foreach ( $image_rows as $image ) echo '<tr><td><img class="digitalisimo-front-thumb" src="' . esc_url( $image['url'] ) . '" alt="' . esc_attr( $image['alt'] ) . '"></td><td><strong>' . esc_html( $image['origin'] ) . '</strong><br>' . esc_html( $image['url'] ) . '</td><td>' . esc_html( $image['alt'] ) . '</td><td>' . esc_html( $image['title'] ) . '</td></tr>'; if ( ! $image_rows ) echo '<tr><td colspan="4">No se detectaron imágenes.</td></tr>'; echo '</tbody></table></section>';
		echo '<section data-front-panel="links" hidden><h3>Enlaces</h3><p>' . esc_html( $internal_links . ' internos · ' . $external_links . ' externos · ' . count( $link_rows ) . ' URL únicas.' ) . '</p><table class="widefat striped digitalisimo-front-table"><thead><tr><th>URL</th><th>Tipo</th><th>Veces</th><th>Title</th><th>Rel</th></tr></thead><tbody>'; foreach ( $link_rows as $href => $link ) echo '<tr><td>' . esc_html( $href ) . '</td><td>' . esc_html( $link['kind'] ) . '</td><td>' . absint( $link['count'] ) . '</td><td>' . esc_html( $link['title'] ) . '</td><td>' . esc_html( $link['rel'] ) . '</td></tr>'; if ( ! $link_rows ) echo '<tr><td colspan="5">No se detectaron enlaces navegables.</td></tr>'; echo '</tbody></table></section>';
		echo '<section data-front-panel="social" hidden><h3>Social y Schema</h3><table class="widefat striped digitalisimo-front-table"><tbody>'; foreach ( $meta as $key => $values ) if ( 0 === strpos( $key, 'og:' ) || 0 === strpos( $key, 'twitter:' ) ) self::item( $key, self::values( $values ) ); self::item( 'Schema JSON-LD', array( count( $schemas ) . ' bloque(s); ' . $invalid_schema . ' con JSON inválido' ) ); self::item( 'Tipos Schema', self::values( $schema_types ) ); self::item( 'IDs Schema repetidos', self::values( $duplicate_schema_ids ), 'No se detectaron' ); echo '</tbody></table></section>';
		echo '<section data-front-panel="tools" hidden><h3>Herramientas y datos completos</h3><p><a class="button button-secondary" target="_blank" rel="noopener" href="' . esc_url( home_url( '/robots.txt' ) ) . '">robots.txt</a> <a class="button button-secondary" target="_blank" rel="noopener" href="' . esc_url( home_url( '/wp-sitemap.xml' ) ) . '">Sitemap XML</a> <a class="button button-secondary" target="_blank" rel="noopener" href="https://search.google.com/test/rich-results?url=' . rawurlencode( $report['url'] ) . '">Rich Results</a> <a class="button button-secondary" target="_blank" rel="noopener" href="https://pagespeed.web.dev/analysis?url=' . rawurlencode( $report['url'] ) . '">PageSpeed</a></p><h4>Metas completas</h4><table class="widefat striped digitalisimo-front-table"><tbody>'; foreach ( $meta as $key => $values ) self::item( $key, self::values( $values ) ); echo '</tbody></table><details><summary><strong>Scripts externos (' . count( $script_rows ) . ')</strong></summary><pre class="digitalisimo-front-head">' . esc_html( implode( "\n", $script_rows ) ) . '</pre></details><details><summary><strong>Ver el &lt;head&gt; recibido</strong></summary><pre class="digitalisimo-front-head">' . esc_html( $head ) . '</pre></details></section>';
		$warnings = array(); if ( 1 !== count( $titles ) ) $warnings[] = 'Debe haber un solo title; se detectaron ' . count( $titles ) . '.'; if ( 1 !== $h1_count ) $warnings[] = 'Se recomienda un solo H1; se detectaron ' . $h1_count . '.'; if ( count( $meta['description'] ?? array() ) > 1 ) $warnings[] = 'Hay más de una meta description.'; if ( count( $canonicals ) > 1 ) $warnings[] = 'Hay más de una URL canonical.'; if ( $invalid_schema ) $warnings[] = 'Hay ' . $invalid_schema . ' bloque(s) Schema con JSON inválido.'; if ( $duplicate_schema_ids ) $warnings[] = 'Hay IDs de Schema repetidos; otro plugin o el tema puede estar emitiendo la misma entidad.'; if ( $missing_alt ) $warnings[] = 'Hay ' . $missing_alt . ' imágenes sin atributo alt.'; if ( self::configured( 'seo_open_graph' ) && empty( $meta['og:title'] ) ) $warnings[] = 'Open Graph está activo en Digitalisimo, pero og:title no se detectó en el front.'; if ( self::configured( 'seo_schema_enabled' ) && ! $schemas ) $warnings[] = 'Schema está activo en Digitalisimo, pero no se detectó JSON-LD en el front.';
		$basic_recommendations = array();
		$add_recommendation = function( $title, $cause, $place, $proposal ) use ( &$basic_recommendations ) { $basic_recommendations[] = array( 'title' => $title, 'cause' => $cause, 'place' => $place, 'proposal' => $proposal ); };
		if ( ! $primary_keyword ) $add_recommendation( 'Define una keyword principal', 'La landing no tiene una keyword principal configurada en Digitalisimo SEO.', 'Editor de esta página → panel SEO → Keywords.', 'Define una frase objetivo y coloca las variantes como keywords secundarias.' );
		elseif ( ! $context_checks['Title'] ) $add_recommendation( 'Incorpora la keyword en el title', 'El title publicado no contiene “' . $primary_keyword . '”.', 'Editor de esta página → panel SEO → Título SEO.', 'Incluye la keyword principal de forma natural, conservando una promesa clara para la búsqueda.' );
		if ( $primary_keyword && ! $context_checks['Descripción'] ) $add_recommendation( 'Incorpora la keyword en la meta description', 'La meta description publicada no contiene “' . $primary_keyword . '”.', 'Editor de esta página → panel SEO → Descripción SEO.', 'Incluye la keyword una vez y explica el beneficio concreto de la landing.' );
		if ( $primary_keyword && ! $context_checks['H1'] ) $add_recommendation( 'Alinea el H1 con la keyword', 'El H1 publicado no contiene “' . $primary_keyword . '”.', 'Constructor o editor visual → encabezado H1 principal.', 'Incluye la keyword en un H1 claro, sin duplicar encabezados H1.' );
		if ( $primary_keyword && ! $context_checks['Contenido'] ) $add_recommendation( 'Añade contexto semántico al contenido', 'El texto visible no contiene “' . $primary_keyword . '”.', 'Primer bloque de contenido y secciones de servicios de la landing.', 'Explica el servicio o propuesta con la keyword de manera natural; no la repitas artificialmente.' );
		if ( $primary_keyword && ! $context_checks['URL'] ) $add_recommendation( 'Revisa la URL objetivo', 'El slug publicado no refleja “' . $primary_keyword . '”.', 'Editor de esta página → enlace permanente.', 'Evalúa cambiar el slug sólo si no afecta URLs ya posicionadas; redirige 301 la URL anterior si haces el cambio.' );
		if ( $missing_alt ) $add_recommendation( 'Completa los textos alternativos de imágenes', 'Se detectaron ' . $missing_alt . ' imágenes sin atributo alt.', 'Pestaña Imágenes de este informe y Biblioteca de medios o widget de cada imagen.', 'Describe la función o contenido real de cada imagen. Usa la keyword sólo cuando corresponda a la imagen, nunca en elementos decorativos.' );
		if ( 1 !== $h1_count ) $add_recommendation( 'Corrige la estructura H1', 'La página publica ' . $h1_count . ' encabezados H1.', 'Constructor o editor visual de la landing.', 'Conserva un H1 que describa el objetivo principal y organiza las secciones con H2 y H3.' );
		if ( 1 !== count( $titles ) ) $add_recommendation( 'Corrige el title publicado', 'Se detectaron ' . count( $titles ) . ' etiquetas title.', 'Configuración SEO de la página y cualquier plugin o tema que emita metas.', 'Deja un solo title para evitar señales contradictorias.' );
		if ( 1 !== count( $canonicals ) ) $add_recommendation( 'Corrige la canonical', 'Se detectaron ' . count( $canonicals ) . ' URLs canonical.', 'Configuración SEO de la página y tema o plugins que emitan canonical.', 'Deja una canonical absoluta que apunte a la URL preferida de esta landing.' );
		foreach ( array_slice( $secondary_keywords, 0, 5 ) as $secondary_keyword ) if ( ! $contains( $front_text, $secondary_keyword ) ) $add_recommendation( 'Integra una keyword secundaria relevante', 'La keyword secundaria “' . $secondary_keyword . '” no se detecta en el contenido visible.', 'Sección que explica el servicio relacionado.', 'Úsala sólo si la sección realmente responde a esa intención de búsqueda.' );
		echo '<section data-front-panel="summary"><div class="digitalisimo-front-recommendations"><article class="digitalisimo-front-recommendation-card"><h3>Recomendaciones técnicas automáticas</h3><p>Se calculan con el HTML publicado, la keyword principal y las secundarias. No consumen IA.</p>';
		if ( $basic_recommendations ) { echo '<ol class="digitalisimo-front-recommendation-list">'; foreach ( $basic_recommendations as $recommendation ) echo '<li><h4>' . esc_html( $recommendation['title'] ) . '</h4><p><strong>Causa:</strong> ' . esc_html( $recommendation['cause'] ) . '</p><p><strong>Lugar a editar:</strong> ' . esc_html( $recommendation['place'] ) . '</p><p><strong>Propuesta:</strong> ' . esc_html( $recommendation['proposal'] ) . '</p></li>'; echo '</ol>'; } else echo '<p class="digitalisimo-front-success">✓ Las comprobaciones automáticas no encontraron ajustes prioritarios para esta landing.</p>';
		echo '</article><article class="digitalisimo-front-recommendation-card digitalisimo-front-ai-card"><h3>Recomendaciones profundas con IA</h3><p>Usa el perfil SEO configurado en Digitalisimo IA Tools para priorizar y ampliar únicamente los hallazgos de esta landing.</p>';
		if ( class_exists( 'Digitalisimo_AI' ) ) { $missing_image_list = array_values( array_filter( array_map( function( $image ) { return empty( trim( $image['alt'] ) ) ? $image['url'] : ''; }, $image_rows ) ) ); $prompt = 'Actúa como auditor SEO técnico. Analiza exclusivamente esta landing y los datos observados; no inventes problemas ni recomiendes velocidad, enlaces rotos, sitemap, robots, HTTPS u otras tareas si no aparecen como fallas. URL: ' . $report['url'] . '. Keyword principal: ' . ( $primary_keyword ?: 'sin configurar' ) . '. Secundarias: ' . implode( ', ', $secondary_keywords ) . '. Relevancia contextual: ' . $context_score . '/100. Señales de keyword: ' . wp_json_encode( $context_checks ) . '. Title: ' . implode( ' | ', $titles ) . '. Meta description: ' . implode( ' | ', (array) ( $meta['description'] ?? array() ) ) . '. H1: ' . ( $headings[0]['text'] ?? '' ) . '. Imágenes sin alt (' . count( $missing_image_list ) . '): ' . implode( ' | ', array_slice( $missing_image_list, 0, 30 ) ) . '. Incidencias técnicas reales: ' . implode( ' | ', $warnings ) . '. Devuelve máximo 8 acciones, cada una exactamente con este formato: número y título; Causa: dato exacto; Lugar a editar: ubicación concreta; Propuesta: cambio concreto que use la keyword sólo cuando sea natural.'; echo '<div class="digitalisimo-front-ai-result" aria-live="polite"></div><p class="digitalisimo-front-ai-action"><button type="button" class="button button-primary digitalisimo-front-ai" data-prompt="' . esc_attr( $prompt ) . '">Generar recomendaciones con IA</button></p>'; } else echo '<p class="description">Activa Digitalisimo IA Tools para generar el análisis profundo bajo demanda.</p>';
		echo '</article></div></section></div><script>(function(){function plain(value){return String(value||"").replace(/\\*\\*/g,"").replace(/`/g,"").trim()}function plan(target,value){target.innerHTML="";var lines=String(value||"").replace(/\\r/g,"").split("\\n"),list=document.createElement("ol"),item=null,has=false;lines.forEach(function(raw){var line=raw.trim(),number=line.match(/^\\d+[.)]\\s*(.*)$/),field=line.match(/^[-•]\\s*(?:\\*\\*)?(Causa|Lugar a editar|Propuesta)(?:\\*\\*)?\\s*:\\s*(.*)$/i);if(!line)return;if(number){item=document.createElement("li");list.appendChild(item);has=true;if(number[1]){var title=document.createElement("h4");title.textContent=plain(number[1]);item.appendChild(title)}return}if(!item){item=document.createElement("li");list.appendChild(item);has=true}if(field){var paragraph=document.createElement("p"),label=document.createElement("strong");label.textContent=field[1]+":";paragraph.appendChild(label);paragraph.appendChild(document.createTextNode(" "+plain(field[2])));item.appendChild(paragraph);return}if(/^\\*\\*.*\\*\\*$/.test(line)){var heading=document.createElement("h4");heading.textContent=plain(line);item.appendChild(heading);return}var text=document.createElement("p");text.textContent=plain(line);item.appendChild(text)});if(has)target.appendChild(list);else target.textContent="La IA no devolvió recomendaciones utilizables."}document.querySelectorAll("[data-front-tab]").forEach(function(link){link.addEventListener("click",function(event){event.preventDefault();var tab=link.dataset.frontTab;document.querySelectorAll("[data-front-panel]").forEach(function(panel){panel.hidden=panel.dataset.frontPanel!==tab});document.querySelectorAll("[data-front-tab]").forEach(function(item){item.classList.toggle("button-primary",item===link);item.classList.toggle("button-secondary",item!==link)});history.replaceState(null,"",location.pathname+location.search+"#"+tab)})});document.querySelectorAll(".digitalisimo-front-ai").forEach(function(button){button.addEventListener("click",function(){var out=button.closest(".digitalisimo-front-ai-card").querySelector(".digitalisimo-front-ai-result");button.disabled=true;out.textContent="Analizando la landing…";fetch("' . esc_js( rest_url( 'digitalisimo-ai/v1/complete' ) ) . '",{method:"POST",headers:{"Content-Type":"application/json","X-WP-Nonce":"' . esc_js( wp_create_nonce( 'wp_rest' ) ) . '"},body:JSON.stringify({profile:"seo",prompt:button.dataset.prompt})}).then(function(response){return response.json()}).then(function(data){if(data.answer)plan(out,data.answer);else out.textContent=data.message||"No fue posible generar recomendaciones."}).catch(function(){out.textContent="Error de conexión."}).finally(function(){button.disabled=false})})})})();</script></section>
	}
}
