<?php
defined( 'ABSPATH' ) || exit;

/** Auditoría técnica bajo demanda para URLs públicas; no hace llamadas externas al guardar. */
class Digitalisimo_Integrations_SEO_AI_Audit_Tools {
	public static function init() { add_action( 'admin_menu', array( __CLASS__, 'menu' ), 32 ); }
	public static function menu() { add_submenu_page( 'digitalisimo', 'SEO AI · Auditoría', 'SEO AI · Auditoría', 'manage_options', 'digitalisimo-seo-ai-audit', array( __CLASS__, 'page' ) ); }
	private static function audit( $url ) {
		$response = wp_remote_get( $url, array( 'timeout' => 15, 'redirection' => 5, 'user-agent' => 'Digitalisimo SEO Audit/1.0' ) );
		if ( is_wp_error( $response ) ) return array( 'error' => $response->get_error_message() );
		$body = (string) wp_remote_retrieve_body( $response ); $code = (int) wp_remote_retrieve_response_code( $response ); $final = wp_remote_retrieve_header( $response, 'x-final-url' ) ?: $url;
		$post_id = url_to_postid( $url ); $robots = $post_id ? (array) Digitalisimo_Integrations_SEO::meta( $post_id, 'robots', array() ) : array(); $noindex = in_array( 'noindex', $robots, true ) || ( $post_id && '1' === get_post_meta( $post_id, 'digitalisimo_seo_noindex', true ) ); $canonical = $post_id ? ( Digitalisimo_Integrations_SEO::meta( $post_id, 'canonical' ) ?: get_permalink( $post_id ) ) : '';
		$text = trim( wp_strip_all_tags( $body ) ); preg_match_all( '/<h[1-6][^>]*>/i', $body, $headings ); preg_match_all( '/<h1[\s>]/i', $body, $h1 ); preg_match( '/<link[^>]+rel=["\']canonical["\'][^>]+href=["\']([^"\']+)/i', $body, $match ); preg_match_all( '/<a[^>]+href=["\']([^"\'#?][^"\']*)/i', $body, $links ); $home_host = wp_parse_url( home_url(), PHP_URL_HOST ); $internal = array(); foreach ( (array) ( $links[1] ?? array() ) as $link ) { $host = wp_parse_url( $link, PHP_URL_HOST ); if ( ! $host || $host === $home_host ) $internal[] = $link; } $internal = array_unique( $internal );
		$org = (string) Digitalisimo_Integrations_Settings::get( 'seo_organization_name' ); $site = (string) Digitalisimo_Integrations_Settings::get( 'seo_site_name' ); $local = (bool) Digitalisimo_Integrations_Settings::get( 'seo_local_enabled' ); $local_name = (string) Digitalisimo_Integrations_Settings::get( 'seo_local_name' ); $stable = false !== strpos( $body, home_url( '/#organization' ) ) && false !== strpos( $body, home_url( '/#website' ) ) && false !== strpos( $body, untrailingslashit( $url ) . '#webpage' ); $entity_consistent = $org && ( ! $site || mb_strtolower( $org ) === mb_strtolower( $site ) || $local || ! $local_name || mb_strtolower( $org ) === mb_strtolower( $local_name ) );
		return array( 'HTTP' => array( $code >= 200 && $code < 400, 'HTTP ' . $code . ( $final !== $url ? ' · redirige a ' . $final : '' ) ), 'Robots' => array( ! $noindex, $noindex ? 'Noindex' : 'Rastreable' ), 'Canonical' => array( $canonical && ( empty( $match[1] ) || untrailingslashit( $canonical ) === untrailingslashit( $match[1] ) ), $canonical ?: 'No se resolvió canonical' ), 'Sitemap' => array( (bool) Digitalisimo_Integrations_Settings::get( 'sitemap_enabled', 1 ), home_url( '/wp-sitemap.xml' ) ), 'Contenido textual' => array( str_word_count( $text ) >= 80, str_word_count( $text ) . ' palabras HTML' ), 'Estructura' => array( ! empty( $h1[0] ) && ! empty( $headings[0] ), count( $h1[0] ) . ' H1 · ' . count( $headings[0] ) . ' encabezados' ), 'Enlaces internos' => array( count( $internal ) > 0, count( $internal ) . ' enlaces internos detectados' ), 'Schema' => array( false !== stripos( $body, 'application/ld+json' ), false !== stripos( $body, 'application/ld+json' ) ? 'Detectado' : 'No detectado' ), 'IDs de Schema' => array( $stable, $stable ? '#organization, #website y #webpage estables' : 'No se detectaron IDs estables de Organization/WebSite/WebPage' ), 'Entidades' => array( (bool) $entity_consistent, $entity_consistent ? 'Organization, WebSite y SEO local coherentes' : 'Revisar Organization, Site Name y SEO local' ), 'Autoridad editorial' => array( ! $post_id || (bool) get_the_author_meta( 'display_name', get_post_field( 'post_author', $post_id ) ), $post_id ? ( get_the_modified_date( 'Y-m-d', $post_id ) . ' · autor ' . get_the_author_meta( 'display_name', get_post_field( 'post_author', $post_id ) ) ) : 'No aplicable a URL no asociada a contenido' ), 'Acceso externo' => array( ! in_array( $code, array( 401, 403, 429 ), true ), in_array( $code, array( 401, 403, 429 ), true ) ? 'Posible bloqueo CDN/WAF' : 'Sin bloqueo observable' ) );
	}
	public static function page() {
		if ( ! current_user_can( 'manage_options' ) ) return; $url = esc_url_raw( wp_unslash( $_POST['audit_url'] ?? home_url( '/' ) ) );
		echo '<div class="wrap"><h1>SEO AI · Auditoría por URL</h1><p>Verifica el comportamiento observable desde WordPress. Un CDN, WAF o firewall externo puede aplicar reglas adicionales.</p><form method="post">'; wp_nonce_field( 'digitalisimo_seo_ai_audit' ); echo '<input class="large-text" name="audit_url" type="url" value="' . esc_attr( $url ) . '"> '; submit_button( 'Analizar URL', 'primary', 'run_audit', false ); echo '</form>';
		if ( isset( $_POST['run_audit'] ) && check_admin_referer( 'digitalisimo_seo_ai_audit' ) && $url ) { $checks = self::audit( $url ); if ( isset( $checks['error'] ) ) echo '<div class="notice notice-error"><p>' . esc_html( $checks['error'] ) . '</p></div>'; else { $passed = count( array_filter( $checks, function( $item ) { return $item[0]; } ) ); $score = (int) round( 100 * $passed / count( $checks ) ); echo '<h2>SEO AI Score: ' . esc_html( $score ) . '/100</h2><p class="description">Métrica técnica interna; no garantiza posicionamiento ni citación.</p><table class="widefat striped"><tbody>'; foreach ( $checks as $label => $item ) echo '<tr><th>' . esc_html( $label ) . '</th><td>' . ( $item[0] ? '✓' : '⚠' ) . ' ' . esc_html( $item[1] ) . '</td></tr>'; echo '</tbody></table>'; } }
		echo '</div>';
	}
}
