<?php
defined( 'ABSPATH' ) || exit;

/** Privacidad y operación del registro agregado de referencias IA. */
class Digitalisimo_Integrations_SEO_AI_Referral_Tools {
	const OPTION = 'digitalisimo_integrations_options';
	const LOG = 'digitalisimo_seo_ai_referrals';
	public static function init() { add_action( 'admin_menu', array( __CLASS__, 'menu' ), 34 ); add_action( 'admin_post_digitalisimo_ai_referrals', array( __CLASS__, 'save' ) ); }
	public static function menu() { add_submenu_page( 'digitalisimo', 'SEO AI · Referencias', 'SEO AI · Referencias', 'manage_options', 'digitalisimo-seo-ai-references', array( __CLASS__, 'page' ) ); }
	/** Registro único de fuentes; las fuentes personalizadas usan "hostname | nombre" por línea. */
	public static function sources() { $base = array( 'chatgpt.com' => 'ChatGPT', 'perplexity.ai' => 'Perplexity', 'copilot.microsoft.com' => 'Copilot', 'gemini.google.com' => 'Gemini', 'claude.ai' => 'Claude' ); $custom = (array) get_option( self::OPTION, array() ); foreach ( preg_split( '/\r\n|\r|\n/', (string) ( $custom['seo_ai_referral_sources'] ?? '' ) ) as $line ) { $parts = array_map( 'trim', explode( '|', $line, 2 ) ); if ( ! empty( $parts[0] ) && ! empty( $parts[1] ) && preg_match( '/^[a-z0-9.-]+$/i', $parts[0] ) ) $base[ strtolower( $parts[0] ) ] = sanitize_text_field( $parts[1] ); } return apply_filters( 'digitalisimo_seo_ai_referral_sources', $base ); }
	public static function save() {
		if ( ! current_user_can( 'manage_options' ) || ! check_admin_referer( 'digitalisimo_ai_referrals' ) ) wp_die( esc_html__( 'Solicitud no autorizada.', 'digitalisimo-integrations' ) );
		$action = sanitize_key( wp_unslash( $_POST['referral_action'] ?? '' ) ); $option = (array) get_option( self::OPTION, array() );
		if ( 'settings' === $action ) { $option['seo_ai_referrals_enabled'] = empty( $_POST['enabled'] ) ? 0 : 1; $option['seo_ai_referral_retention'] = in_array( absint( $_POST['retention'] ?? 90 ), array( 30, 90, 180, 365 ), true ) ? absint( $_POST['retention'] ) : 90; $lines = array(); foreach ( preg_split( '/\r\n|\r|\n/', (string) wp_unslash( $_POST['sources'] ?? '' ) ) as $line ) { $parts = array_map( 'trim', explode( '|', $line, 2 ) ); if ( ! empty( $parts[0] ) && ! empty( $parts[1] ) && preg_match( '/^[a-z0-9.-]+$/i', $parts[0] ) ) $lines[] = strtolower( $parts[0] ) . ' | ' . sanitize_text_field( $parts[1] ); } $option['seo_ai_referral_sources'] = implode( "\n", array_unique( $lines ) ); update_option( self::OPTION, $option, false ); self::purge( $option['seo_ai_referral_retention'] ); }
		if ( 'clear' === $action ) update_option( self::LOG, array(), false );
		wp_safe_redirect( add_query_arg( 'page', 'digitalisimo-seo-ai-references', admin_url( 'admin.php' ) ) ); exit;
	}
	private static function purge( $days ) { $cutoff = time() - ( absint( $days ) * DAY_IN_SECONDS ); $rows = array_values( array_filter( (array) get_option( self::LOG, array() ), function( $row ) use ( $cutoff ) { return (int) ( $row['time'] ?? 0 ) >= $cutoff; } ) ); update_option( self::LOG, $rows, false ); }
	public static function page() {
		if ( ! current_user_can( 'manage_options' ) ) return; $option = (array) get_option( self::OPTION, array() ); self::purge( $option['seo_ai_referral_retention'] ?? 90 ); $rows = (array) get_option( self::LOG, array() ); $counts = array_count_values( wp_list_pluck( $rows, 'source' ) ); $daily = array(); $pages = array(); foreach ( $rows as $row ) { $day = wp_date( 'Y-m-d', (int) ( $row['time'] ?? 0 ) ); $daily[ $day ] = ( $daily[ $day ] ?? 0 ) + 1; $page = (string) ( $row['page'] ?? '' ); if ( $page ) $pages[ $page ] = ( $pages[ $page ] ?? 0 ) + 1; } ksort( $daily ); arsort( $pages );
		echo '<div class="wrap"><h1>SEO AI · Referencias</h1><p>Registra sólo plataforma, página de destino, fecha y UTM cuando exista. No guarda prompts, conversaciones, IPs ni información personal.</p><form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '">'; wp_nonce_field( 'digitalisimo_ai_referrals' ); echo '<input type="hidden" name="action" value="digitalisimo_ai_referrals"><input type="hidden" name="referral_action" value="settings"><p><label><input type="checkbox" name="enabled" value="1" ' . checked( ! empty( $option['seo_ai_referrals_enabled'] ), true, false ) . '> Activar detección</label> <label>Retención <select name="retention">'; foreach ( array( 30, 90, 180, 365 ) as $days ) echo '<option value="' . $days . '" ' . selected( (int) ( $option['seo_ai_referral_retention'] ?? 90 ), $days, false ) . '>' . $days . ' días</option>'; echo '</select></label></p><p><label><strong>Fuentes adicionales</strong><br><textarea class="large-text code" rows="4" name="sources" placeholder="ejemplo.ai | Ejemplo IA">' . esc_textarea( $option['seo_ai_referral_sources'] ?? '' ) . '</textarea></label><br><span class="description">Una por línea. Sólo hostname y nombre administrativo.</span></p>'; submit_button( 'Guardar', 'primary', 'submit', false ); echo '</form><h2>Resumen por plataforma</h2><ul>'; foreach ( $counts as $source => $count ) echo '<li>' . esc_html( $source ) . ': ' . absint( $count ) . '</li>'; echo '</ul><h2>Evolución diaria</h2><table class="widefat striped"><thead><tr><th>Fecha</th><th>Visitas detectadas</th></tr></thead><tbody>'; foreach ( array_slice( array_reverse( $daily, true ), 0, 30, true ) as $day => $count ) echo '<tr><td>' . esc_html( $day ) . '</td><td>' . absint( $count ) . '</td></tr>'; echo '</tbody></table><h2>Landings más visitadas</h2><table class="widefat striped"><thead><tr><th>Landing</th><th>Visitas</th></tr></thead><tbody>'; foreach ( array_slice( $pages, 0, 20, true ) as $page => $count ) echo '<tr><td>' . esc_html( $page ) . '</td><td>' . absint( $count ) . '</td></tr>'; echo '</tbody></table><form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '">'; wp_nonce_field( 'digitalisimo_ai_referrals' ); echo '<input type="hidden" name="action" value="digitalisimo_ai_referrals"><input type="hidden" name="referral_action" value="clear">'; submit_button( 'Borrar todos los registros', 'delete', 'submit', false ); echo '</form></div>';
	}
}
