<?php
defined( 'ABSPATH' ) || exit;

/** SEO local nativo de Digitalisimo. */
class Digitalisimo_Integrations_SEO {
	const PREFIX = 'digitalisimo_seo_';

	public static function init() {
		if ( ! Digitalisimo_Integrations_Settings::get( 'enable_seo' ) ) return;
		add_action( 'admin_menu', array( __CLASS__, 'admin_menu' ), 20 );
		add_action( 'add_meta_boxes', array( __CLASS__, 'metabox' ) ); add_action( 'save_post', array( __CLASS__, 'save_meta' ) ); add_action( 'save_post', array( __CLASS__, 'save_keywords' ), 20 );
		// Los metadatos públicos se emiten exclusivamente por SEO_Suite. Esta clase
		// conserva editor, keywords, clusters e importadores sin duplicar señales SEO.
		add_filter( 'manage_post_posts_columns', array( __CLASS__, 'column' ) ); add_filter( 'manage_page_posts_columns', array( __CLASS__, 'column' ) ); add_action( 'manage_post_posts_custom_column', array( __CLASS__, 'column_value' ), 10, 2 ); add_action( 'manage_page_posts_custom_column', array( __CLASS__, 'column_value' ), 10, 2 );
		add_shortcode( 'contenido_pilar', array( __CLASS__, 'shortcode_pillar' ) ); add_shortcode( 'contenido_secundario', array( __CLASS__, 'shortcode_secondary' ) ); add_shortcode( 'palabra_clave', array( __CLASS__, 'shortcode_primary_keyword' ) ); add_shortcode( 'palabras_clave_secundarias', array( __CLASS__, 'shortcode_secondary_keywords' ) ); add_shortcode( 'descripcion_sitio', array( __CLASS__, 'shortcode_site_description' ) );
		add_action( 'admin_post_digitalisimo_refresh_intents', array( __CLASS__, 'refresh_intents' ) );
		add_action( 'admin_post_digitalisimo_migrate_rankmath', array( __CLASS__, 'migrate_rankmath' ) );
		add_action( 'admin_post_digitalisimo_import_seo_data', array( __CLASS__, 'import_legacy_seo_data' ) );
	}
	private static function key( $name ) { return self::PREFIX . $name; }
	public static function meta( $id, $name, $default = '' ) { return Digitalisimo_Integrations_SEO_Resolver::post( $id, $name, $default ); }
	private static function related_pillar( $id ) { return absint( get_post_meta( $id, '_related_pillar', true ) ); }
	private static function is_pillar( $id ) { return 'on' === self::meta( $id, 'pillar' ); }
	private static function keyword_post_types() { $types = array_filter( array_map( 'sanitize_key', array_map( 'trim', explode( ',', (string) Digitalisimo_Integrations_Settings::get( 'keyword_post_types', 'all' ) ) ) ) ); if ( in_array( 'all', $types, true ) ) return get_post_types( array( 'show_ui' => true ), 'names' ); return $types; }

	public static function admin_menu() {
		add_submenu_page( null, 'Contenido', 'Contenido', 'manage_options', 'digitalisimo-content', array( __CLASS__, 'content_page' ) );
		foreach ( array( 'digitalisimo-keywords' => 'Keywords', 'digitalisimo-clusters' => 'Clusters', 'digitalisimo-intents' => 'Intención SEO' ) as $slug => $label ) add_submenu_page( null, $label, $label, 'manage_options', $slug, array( __CLASS__, strtolower( str_replace( array( 'digitalisimo-', '-' ), array( '', '_' ), $slug ) ) . '_page' ) );
	}
	/** Pantalla editorial única: conserva la navegación SEO y cambia el cuerpo por sección. */
	public static function content_page( $forced_tab = '' ) {
		if ( ! current_user_can( 'manage_options' ) ) return;
		$tab = $forced_tab ?: sanitize_key( $_GET['content_tab'] ?? 'keywords' );
		$tabs = array( 'keywords' => 'Keywords', 'clusters' => 'Clusters', 'intents' => 'Intención de búsqueda' );
		if ( ! isset( $tabs[ $tab ] ) ) $tab = 'keywords';
		echo '<div class="wrap digitalisimo-admin-shell"><h1>SEO · Digitalisimo</h1>'; Digitalisimo_Integrations_SEO_Suite::navigation_tabs( 'content' ); echo '<h2>Contenido</h2><p>Gestiona la estrategia editorial sin perder la navegación principal de SEO.</p><p class="digitalisimo-content-links">'; foreach ( $tabs as $id => $label ) echo '<a class="button ' . ( $tab === $id ? 'button-primary' : 'button-secondary' ) . '" data-content-tab="' . esc_attr( $id ) . '" href="#' . esc_attr( $id ) . '">' . esc_html( $label ) . '</a> '; echo '</p><div class="digitalisimo-content-body">';
		foreach ( $tabs as $id => $label ) { echo '<section class="digitalisimo-content-panel" data-content-panel="' . esc_attr( $id ) . '"' . ( $tab === $id ? '' : ' hidden' ) . '>'; if ( 'keywords' === $id ) self::keywords_content(); elseif ( 'clusters' === $id ) self::clusters_content(); else self::intents_content(); echo '</section>'; }
		echo '</div><script>document.querySelectorAll("[data-content-tab]").forEach(function(link){link.addEventListener("click",function(event){event.preventDefault();var tab=link.dataset.contentTab;document.querySelectorAll("[data-content-panel]").forEach(function(panel){panel.hidden=panel.dataset.contentPanel!==tab;});document.querySelectorAll("[data-content-tab]").forEach(function(item){item.classList.toggle("button-primary",item===link);item.classList.toggle("button-secondary",item!==link);});history.replaceState(null,"",location.pathname+location.search.replace(/([?&])content_tab=[^&]*&?/,"$1").replace(/[?&]$/,"")+"#"+tab);});});</script></div>';
	}
	public static function metabox() { foreach ( self::keyword_post_types() as $type ) if ( post_type_exists( $type ) ) { add_meta_box( 'digitalisimo_seo', __( 'SEO de Digitalísimo', 'digitalisimo-integrations' ), array( __CLASS__, 'metabox_html' ), $type, 'normal', 'high' ); add_meta_box( 'digitalisimo_keywords', __( 'Palabras clave de Digitalisimo', 'digitalisimo-integrations' ), array( __CLASS__, 'keywords_box' ), $type, 'normal', 'high' ); } }
	public static function keywords_box( $post ) { wp_nonce_field( 'digitalisimo_keywords_save', 'digitalisimo_keywords_nonce' ); $keywords = array_filter( array_map( 'trim', explode( ',', (string) self::meta( $post->ID, 'keywords' ) ) ) ); $primary = array_shift( $keywords ); $intent = get_post_meta( $post->ID, self::key( 'search_intent' ), true ); echo '<p><label><strong>Palabra clave principal</strong><input class="widefat" name="digitalisimo_keyword_primary" value="' . esc_attr( $primary ) . '"></label></p><p><label><strong>Palabras clave secundarias</strong><textarea class="widefat" rows="4" name="digitalisimo_keyword_secondary" placeholder="Una por línea">' . esc_textarea( implode( "\n", $keywords ) ) . '</textarea></label></p><p><label><strong>Intención de búsqueda</strong><select class="widefat" name="digitalisimo_keyword_intent"><option value="">Sin definir</option>'; foreach ( array( 'Informacional', 'Transaccional', 'Navegacional', 'Investigación Comercial' ) as $option ) echo '<option value="' . esc_attr( $option ) . '" ' . selected( $intent, $option, false ) . '>' . esc_html( $option ) . '</option>'; echo '</select></label></p>'; self::analysis_box( $post, $primary ); echo '<p class="description">Las keywords no se publican como meta keywords: se usan para analizar y mejorar señales SEO reales.</p>'; }
	private static function analysis_box( $post, $keyword ) { if ( ! $keyword ) { echo '<p class="description">Añade una keyword principal y guarda para ver el análisis SEO.</p>'; return; } $content = wp_strip_all_tags( $post->post_content ); $title = self::meta( $post->ID, 'title' ) ?: $post->post_title; $description = self::meta( $post->ID, 'description' ); $slug = $post->post_name; $needle = mb_strtolower( $keyword ); $checks = array( 'Título SEO' => false !== mb_stripos( $title, $needle ), 'Meta descripción' => $description && false !== mb_stripos( $description, $needle ), 'URL (slug)' => false !== mb_stripos( $slug, sanitize_title( $keyword ) ), 'Primer 10% del texto' => false !== mb_stripos( mb_substr( $content, 0, max( 1, (int) ( mb_strlen( $content ) / 10 ) ) ), $needle ), 'Contenido (mín. 300 palabras)' => str_word_count( $content ) >= 300, 'Encabezado H2/H3' => preg_match( '/<h[2-3][^>]*>.*' . preg_quote( $keyword, '/' ) . '.*<\/h[2-3]>/iu', $post->post_content ) ); $passed = count( array_filter( $checks ) ); $score = (int) round( 100 * $passed / count( $checks ) ); $color = $score >= 80 ? '#008a20' : ( $score >= 50 ? '#dba617' : '#b32d2e' ); echo '<hr><p><strong>Análisis SEO: <span style="color:' . esc_attr( $color ) . '">' . esc_html( $score ) . '/100</span></strong></p><ul style="margin-left:1em;list-style:disc">'; foreach ( $checks as $label => $passed ) echo '<li>' . ( $passed ? '✓' : '○' ) . ' ' . esc_html( $label ) . '</li>'; echo '</ul>'; }
	public static function metabox_html( $post ) {
		wp_nonce_field( 'digitalisimo_seo_save', 'digitalisimo_seo_nonce' ); $pillars = get_posts( array( 'post_type' => array( 'post', 'page' ), 'posts_per_page' => -1, 'post__not_in' => array( $post->ID ), 'meta_key' => self::key( 'pillar' ), 'meta_value' => 'on' ) );
		echo '<p><label><strong>Título SEO</strong><br><input class="widefat" name="digitalisimo_seo_title" value="' . esc_attr( self::meta( $post->ID, 'title' ) ) . '"></label></p><p><label><strong>Meta descripción</strong><br><textarea class="widefat" rows="3" name="digitalisimo_seo_description">' . esc_textarea( self::meta( $post->ID, 'description' ) ) . '</textarea></label></p><p><label><strong>Palabras clave</strong><br><input class="widefat" name="digitalisimo_seo_keywords" value="' . esc_attr( self::meta( $post->ID, 'keywords' ) ) . '"></label></p><p><label><strong>URL canonical</strong><br><input class="widefat" type="url" name="digitalisimo_seo_canonical" value="' . esc_attr( self::meta( $post->ID, 'canonical' ) ) . '"></label></p>';
		$robots = (array) self::meta( $post->ID, 'robots', array() ); echo '<p><label><input type="checkbox" name="digitalisimo_seo_noindex" value="1" ' . checked( in_array( 'noindex', $robots, true ), true, false ) . '> Excluir de buscadores (noindex)</label></p><p><label><input type="checkbox" name="digitalisimo_seo_pillar" value="on" ' . checked( self::is_pillar( $post->ID ), true, false ) . '> Marcar como contenido pilar</label></p><p><label><strong>Contenido pilar relacionado</strong><br><select class="widefat" name="digitalisimo_related_pillar"><option value="">Ninguno</option>';
		foreach ( $pillars as $pillar ) echo '<option value="' . esc_attr( $pillar->ID ) . '" ' . selected( self::related_pillar( $post->ID ), $pillar->ID, false ) . '>' . esc_html( $pillar->post_title ) . '</option>'; echo '</select></label></p>';
	}
	public static function save_meta( $id ) { if ( wp_is_post_revision( $id ) || ! isset( $_POST['digitalisimo_seo_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['digitalisimo_seo_nonce'] ) ), 'digitalisimo_seo_save' ) || ! current_user_can( 'edit_post', $id ) ) return; foreach ( array( 'title', 'description' ) as $field ) update_post_meta( $id, self::key( $field ), sanitize_text_field( wp_unslash( $_POST[ 'digitalisimo_seo_' . $field ] ?? '' ) ) ); $keywords = sanitize_text_field( wp_unslash( $_POST['digitalisimo_seo_keywords'] ?? '' ) ); $keywords = array_filter( array_map( 'trim', explode( ',', $keywords ) ) ); if ( ! $keywords && Digitalisimo_Integrations_Settings::get( 'keyword_auto_from_title' ) ) $keywords = array( get_the_title( $id ) ); $keywords = array_slice( $keywords, 0, absint( Digitalisimo_Integrations_Settings::get( 'keyword_max_count', 5 ) ) ); update_post_meta( $id, self::key( 'keywords' ), implode( ', ', $keywords ) ); update_post_meta( $id, self::key( 'canonical' ), esc_url_raw( wp_unslash( $_POST['digitalisimo_seo_canonical'] ?? '' ) ) ); update_post_meta( $id, self::key( 'robots' ), isset( $_POST['digitalisimo_seo_noindex'] ) ? array( 'noindex' ) : array() ); update_post_meta( $id, self::key( 'pillar' ), isset( $_POST['digitalisimo_seo_pillar'] ) ? 'on' : '' ); $pillar = absint( $_POST['digitalisimo_related_pillar'] ?? 0 ); if ( $pillar ) update_post_meta( $id, '_related_pillar', $pillar ); else delete_post_meta( $id, '_related_pillar' ); }
	public static function save_keywords( $id ) { if ( wp_is_post_revision( $id ) || ! isset( $_POST['digitalisimo_keywords_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['digitalisimo_keywords_nonce'] ) ), 'digitalisimo_keywords_save' ) || ! current_user_can( 'edit_post', $id ) ) return; $primary = sanitize_text_field( wp_unslash( $_POST['digitalisimo_keyword_primary'] ?? '' ) ); $secondary = preg_split( '/\r\n|\r|\n/', sanitize_textarea_field( wp_unslash( $_POST['digitalisimo_keyword_secondary'] ?? '' ) ) ); $keywords = array_filter( array_merge( array( $primary ), array_map( 'trim', $secondary ) ) ); if ( ! $keywords && Digitalisimo_Integrations_Settings::get( 'keyword_auto_from_title' ) ) $keywords = array( get_the_title( $id ) ); $keywords = array_slice( array_unique( $keywords ), 0, absint( Digitalisimo_Integrations_Settings::get( 'keyword_max_count', 5 ) ) ); update_post_meta( $id, self::key( 'keywords' ), implode( ', ', $keywords ) ); $intent = sanitize_text_field( wp_unslash( $_POST['digitalisimo_keyword_intent'] ?? '' ) ); update_post_meta( $id, self::key( 'search_intent' ), $intent ); }

	public static function document_title( $title ) { return ! is_singular() || ! self::meta( get_queried_object_id(), 'title' ) ? $title : self::meta( get_queried_object_id(), 'title' ); }
	private static function global_noindex() { $get = array( 'search' => 'noindex_search', 'authors' => 'noindex_authors', 'date' => 'noindex_date_archives', 'attachments' => 'noindex_attachments', 'elementor' => 'noindex_elementor', 'woo' => 'noindex_woo_pages' ); if ( is_search() && Digitalisimo_Integrations_Settings::get( $get['search'] ) ) return true; if ( is_author() && Digitalisimo_Integrations_Settings::get( $get['authors'] ) ) return true; if ( is_date() && Digitalisimo_Integrations_Settings::get( $get['date'] ) ) return true; if ( is_attachment() && Digitalisimo_Integrations_Settings::get( $get['attachments'] ) ) return true; if ( is_singular( 'elementor_library' ) && Digitalisimo_Integrations_Settings::get( $get['elementor'] ) ) return true; if ( is_tag() && Digitalisimo_Integrations_Settings::get( 'noindex_empty_tags' ) && 0 === (int) get_queried_object()->count ) return true; if ( Digitalisimo_Integrations_Settings::get( $get['woo'] ) && ( ( function_exists( 'is_checkout' ) && is_checkout() ) || ( function_exists( 'is_cart' ) && is_cart() ) || ( function_exists( 'is_account_page' ) && is_account_page() ) || ( function_exists( 'is_order_received_page' ) && is_order_received_page() ) ) ) return true; if ( is_page() ) { $slugs = array_filter( array_map( 'sanitize_title', preg_split( '/\r\n|\r|\n/', (string) Digitalisimo_Integrations_Settings::get( 'noindex_page_slugs', '' ) ) ) ); $ids = array_filter( array_map( 'absint', preg_split( '/\s*,\s*/', (string) Digitalisimo_Integrations_Settings::get( 'noindex_page_ids', '' ) ) ) ); if ( in_array( get_post_field( 'post_name', get_queried_object_id() ), $slugs, true ) || in_array( get_queried_object_id(), $ids, true ) ) return true; } return false; }
	public static function robots( $robots ) { if ( self::global_noindex() || ( is_singular() && in_array( 'noindex', (array) self::meta( get_queried_object_id(), 'robots', array() ), true ) ) ) $robots['noindex'] = true; return $robots; }
	public static function head_tags() { if ( ! is_singular() || is_admin() ) return; $id = get_queried_object_id(); $title = self::meta( $id, 'title' ) ?: get_the_title( $id ); $description = self::meta( $id, 'description' ) ?: get_the_excerpt( $id ); $canonical = self::meta( $id, 'canonical' ) ?: get_permalink( $id ); if ( $description ) echo '<meta name="description" content="' . esc_attr( wp_strip_all_tags( $description ) ) . '">' . "\n"; echo '<link rel="canonical" href="' . esc_url( $canonical ) . '">' . "\n"; echo '<meta property="og:title" content="' . esc_attr( wp_strip_all_tags( $title ) ) . '">' . "\n" . '<meta property="og:description" content="' . esc_attr( wp_strip_all_tags( $description ) ) . '">' . "\n" . '<meta property="og:url" content="' . esc_url( $canonical ) . '">' . "\n" . '<meta property="og:type" content="article">' . "\n"; if ( has_post_thumbnail( $id ) ) echo '<meta property="og:image" content="' . esc_url( get_the_post_thumbnail_url( $id, 'full' ) ) . '">' . "\n"; self::schema( $id, $canonical, $description ); }
	private static function schema( $id, $canonical, $description ) { $post = get_post( $id ); if ( ! $post ) return; $crumbs = array( array( '@type' => 'ListItem', 'position' => 1, 'name' => __( 'Inicio', 'digitalisimo-integrations' ), 'item' => home_url( '/' ) ) ); if ( $pillar = get_post( self::related_pillar( $id ) ) ) $crumbs[] = array( '@type' => 'ListItem', 'position' => 2, 'name' => $pillar->post_title, 'item' => get_permalink( $pillar ) ); $crumbs[] = array( '@type' => 'ListItem', 'position' => count( $crumbs ) + 1, 'name' => get_the_title( $post ), 'item' => $canonical ); $schema = array( '@context' => 'https://schema.org', '@graph' => array( array( '@type' => 'Article', 'headline' => get_the_title( $post ), 'datePublished' => get_the_date( DATE_W3C, $post ), 'dateModified' => get_the_modified_date( DATE_W3C, $post ), 'mainEntityOfPage' => $canonical, 'description' => wp_strip_all_tags( $description ), 'author' => array( '@type' => 'Person', 'name' => get_the_author_meta( 'display_name', $post->post_author ) ) ), array( '@type' => 'BreadcrumbList', 'itemListElement' => $crumbs ) ) ); echo '<script type="application/ld+json">' . wp_json_encode( $schema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE ) . '</script>' . "\n"; }
	private static function configured_post_types() { return array_filter( array_map( 'sanitize_key', array_map( 'trim', explode( ',', (string) Digitalisimo_Integrations_Settings::get( 'sitemap_post_types', 'post,page' ) ) ) ) ); }
	private static function excluded_ids() { $ids = array_merge( array_filter( array_map( 'absint', preg_split( '/\s*,\s*/', (string) Digitalisimo_Integrations_Settings::get( 'sitemap_exclude_ids', '' ) ) ) ), array_filter( array_map( 'absint', preg_split( '/\s*,\s*/', (string) Digitalisimo_Integrations_Settings::get( 'noindex_page_ids', '' ) ) ) ) ); if ( Digitalisimo_Integrations_Settings::get( 'noindex_woo_pages' ) && function_exists( 'wc_get_page_id' ) ) foreach ( array( 'cart', 'checkout', 'myaccount' ) as $page ) $ids[] = absint( wc_get_page_id( $page ) ); return array_unique( array_filter( $ids ) ); }
	public static function sitemap_enabled( $enabled ) { return (bool) Digitalisimo_Integrations_Settings::get( 'sitemap_enabled', 1 ); }
	public static function sitemap_post_types( $types ) { $allowed = self::configured_post_types(); foreach ( $types as $name => $object ) if ( ! in_array( $name, $allowed, true ) ) unset( $types[ $name ] ); return $types; }
	public static function sitemap_query( $args, $type ) { $args['post__not_in'] = array_unique( array_merge( (array) ( $args['post__not_in'] ?? array() ), self::excluded_ids() ) ); $args['meta_query'] = isset( $args['meta_query'] ) ? (array) $args['meta_query'] : array(); $args['meta_query'][] = array( 'relation' => 'OR', array( 'key' => self::key( 'robots' ), 'compare' => 'NOT EXISTS' ), array( 'key' => self::key( 'robots' ), 'value' => 'noindex', 'compare' => 'NOT LIKE' ) ); return $args; }
	public static function column( $columns ) { $columns['digitalisimo_cluster'] = __( 'Cluster', 'digitalisimo-integrations' ); return $columns; }
	public static function column_value( $column, $id ) { if ( 'digitalisimo_cluster' === $column ) { $pillar = get_post( self::related_pillar( $id ) ); echo $pillar ? esc_html( $pillar->post_title ) : '—'; } }
	public static function shortcode_pillar() { $pillar = get_post( self::related_pillar( get_the_ID() ) ); return $pillar ? '<a href="' . esc_url( get_permalink( $pillar ) ) . '">' . esc_html( $pillar->post_title ) . '</a>' : ''; }
	public static function shortcode_secondary() { $posts = get_posts( array( 'post_type' => array( 'post', 'page' ), 'posts_per_page' => -1, 'meta_key' => '_related_pillar', 'meta_value' => get_the_ID() ) ); if ( ! $posts ) return ''; $html = '<ul>'; foreach ( $posts as $post ) $html .= '<li><a href="' . esc_url( get_permalink( $post ) ) . '">' . esc_html( $post->post_title ) . '</a></li>'; return $html . '</ul>'; }
	public static function shortcode_primary_keyword() { $keywords = explode( ',', (string) self::meta( get_the_ID(), 'keywords' ) ); return esc_html( trim( $keywords[0] ?? '' ) ); }
	public static function shortcode_secondary_keywords() { $keywords = array_filter( array_map( 'trim', explode( ',', (string) self::meta( get_the_ID(), 'keywords' ) ) ) ); array_shift( $keywords ); return $keywords ? '<ul><li>' . implode( '</li><li>', array_map( 'esc_html', $keywords ) ) . '</li></ul>' : ''; }
	public static function shortcode_site_description() { return esc_html( get_option( 'blogdescription' ) ); }
	private static function detect_intent( $keyword ) { $prompt = 'Clasifica la intención de búsqueda de "' . $keyword . '". Responde solo: Informacional, Transaccional, Navegacional o Investigación Comercial.'; if ( class_exists( 'Digitalisimo_AI' ) ) { $answer = Digitalisimo_AI::complete( 'seo', $prompt, 'Tarea SEO interna.' ); if ( ! is_wp_error( $answer ) ) return $answer; } if ( class_exists( 'Digitalisimo_SEO_AI_Client' ) && Digitalisimo_SEO_AI_Client::available() ) { $answer = Digitalisimo_SEO_AI_Client::complete( $prompt, 'Eres experto en SEO.', 30 ); if ( ! is_wp_error( $answer ) ) return $answer; } $key = Digitalisimo_Integrations_Settings::get( 'openai_api_key' ); if ( ! $key ) return new WP_Error( 'missing_key', __( 'Configura los proveedores de IA en Digitalisimo · SEO o la clave de OpenAI.', 'digitalisimo-integrations' ) ); $body = array( 'model' => Digitalisimo_Integrations_Settings::get( 'openai_model', 'gpt-4o-mini' ), 'messages' => array( array( 'role' => 'system', 'content' => 'Eres experto en SEO.' ), array( 'role' => 'user', 'content' => $prompt ) ), 'temperature' => 0, 'max_tokens' => 30 ); $response = wp_remote_post( 'https://api.openai.com/v1/chat/completions', array( 'headers' => array( 'Authorization' => 'Bearer ' . $key, 'Content-Type' => 'application/json' ), 'body' => wp_json_encode( $body ), 'timeout' => 20 ) ); if ( is_wp_error( $response ) ) return $response; $data = json_decode( wp_remote_retrieve_body( $response ), true ); $text = trim( $data['choices'][0]['message']['content'] ?? '' ); return $text ? $text : new WP_Error( 'openai_response', __( 'Respuesta no válida de OpenAI.', 'digitalisimo-integrations' ) ); }
	public static function refresh_intents() { if ( ! current_user_can( 'manage_options' ) || ! check_admin_referer( 'digitalisimo_refresh_intents' ) ) wp_die( esc_html__( 'Solicitud no autorizada.', 'digitalisimo-integrations' ) ); foreach ( get_posts( array( 'post_type' => 'post', 'posts_per_page' => -1, 'fields' => 'ids' ) ) as $id ) { $keyword = trim( explode( ',', (string) self::meta( $id, 'keywords' ) )[0] ?? '' ); if ( $keyword ) { $intent = self::detect_intent( $keyword ); if ( ! is_wp_error( $intent ) ) update_post_meta( $id, self::key( 'search_intent' ), $intent ); } } wp_safe_redirect( admin_url( 'admin.php?page=digitalisimo-intents&updated=1' ) ); exit; }
	public static function migrate_rankmath() { if(!current_user_can('manage_options')||!check_admin_referer('digitalisimo_migrate_rankmath'))wp_die('No autorizado.');$ids=get_posts(array('post_type'=>'any','post_status'=>'any','posts_per_page'=>-1,'fields'=>'ids','meta_query'=>array('relation'=>'OR',array('key'=>'rank_math_focus_keyword','compare'=>'EXISTS'),array('key'=>'rank_math_title','compare'=>'EXISTS'),array('key'=>'rank_math_description','compare'=>'EXISTS'),array('key'=>'rank_math_canonical_url','compare'=>'EXISTS'),array('key'=>'rank_math_robots','compare'=>'EXISTS'),array('key'=>'rank_math_pillar_content','compare'=>'EXISTS'))));$fields=array('rank_math_title'=>'title','rank_math_description'=>'description','rank_math_focus_keyword'=>'keywords','rank_math_canonical_url'=>'canonical');$count=0;foreach($ids as$id){foreach($fields as$from=>$to){$target=self::key($to);$value=get_post_meta($id,$from,true);if($value&&!get_post_meta($id,$target,true)){update_post_meta($id,$target,$value);$count++;}}$robots=(array)get_post_meta($id,'rank_math_robots',true);if(in_array('noindex',$robots,true)&&!get_post_meta($id,self::key('robots'),true)){update_post_meta($id,self::key('robots'),array('noindex'));$count++;}if('on'===get_post_meta($id,'rank_math_pillar_content',true)&&!get_post_meta($id,self::key('pillar'),true)){update_post_meta($id,self::key('pillar'),'on');$count++;}}update_option('digitalisimo_seo_rankmath_migrated',time(),false);wp_safe_redirect(admin_url('admin.php?page=digitalisimo-seo&migrated='.$count));exit; }
	/** Compatibilidad con el botón de migración de versiones anteriores. */
	public static function import_legacy_seo_data() {
		if ( ! current_user_can( 'manage_options' ) || ! check_admin_referer( 'digitalisimo_import_seo_data' ) ) wp_die( esc_html__( 'Solicitud no autorizada.', 'digitalisimo-integrations' ) );
		$source = sanitize_key( wp_unslash( $_POST['source'] ?? '' ) );
		if ( ! in_array( $source, array( 'rankmath', 'yoast', 'all' ), true ) ) $source = 'all';
		$sources = 'all' === $source ? array( 'rankmath', 'yoast' ) : array( $source );
		$imported = 0;
		$found = 0;
		foreach ( $sources as $provider ) {
			$map = 'rankmath' === $provider
				? array( 'rank_math_title' => 'title', 'rank_math_description' => 'description', 'rank_math_focus_keyword' => 'keywords', 'rank_math_canonical_url' => 'canonical' )
				: array( '_yoast_wpseo_title' => 'title', '_yoast_wpseo_metadesc' => 'description', '_yoast_wpseo_focuskw' => 'keywords', '_yoast_wpseo_canonical' => 'canonical' );
			$special = 'rankmath' === $provider ? array( 'rank_math_robots', 'rank_math_pillar_content' ) : array( '_yoast_wpseo_meta-robots-noindex', '_yoast_wpseo_is_cornerstone' );
			$query = array( 'relation' => 'OR' );
			foreach ( array_merge( array_keys( $map ), $special ) as $meta_key ) $query[] = array( 'key' => $meta_key, 'compare' => 'EXISTS' );
			$ids = get_posts( array( 'post_type' => 'any', 'post_status' => 'any', 'posts_per_page' => -1, 'fields' => 'ids', 'meta_query' => $query ) );
			$found += count( $ids );
			foreach ( $ids as $id ) {
				foreach ( $map as $from => $to ) {
					$value = get_post_meta( $id, $from, true );
					$target = self::key( $to );
					if ( '' !== (string) $value && ! get_post_meta( $id, $target, true ) ) { update_post_meta( $id, $target, sanitize_text_field( $value ) ); $imported++; }
				}
				$robots = self::key( 'robots' );
				$pillar = self::key( 'pillar' );
				if ( 'rankmath' === $provider ) {
					$legacy_robots = get_post_meta( $id, 'rank_math_robots', true );
					$noindex = in_array( 'noindex', (array) $legacy_robots, true ) || false !== stripos( (string) $legacy_robots, 'noindex' );
					$is_pillar = 'on' === get_post_meta( $id, 'rank_math_pillar_content', true );
				} else {
					$noindex = '1' === (string) get_post_meta( $id, '_yoast_wpseo_meta-robots-noindex', true );
					$is_pillar = '1' === (string) get_post_meta( $id, '_yoast_wpseo_is_cornerstone', true );
				}
				if ( $noindex && ! get_post_meta( $id, $robots, true ) ) { update_post_meta( $id, $robots, array( 'noindex' ) ); $imported++; }
				if ( $is_pillar && ! get_post_meta( $id, $pillar, true ) ) { update_post_meta( $id, $pillar, 'on' ); $imported++; }
			}
		}
		update_option( 'digitalisimo_seo_legacy_imported', time(), false );
		wp_safe_redirect( add_query_arg( array( 'page' => 'digitalisimo-seo', 'seo_imported' => $imported, 'seo_found' => $found, 'seo_source' => $source ), admin_url( 'admin.php' ) ) );
		exit;
	}
	public static function seo_page() {
		if ( ! current_user_can( 'manage_options' ) ) return;
		echo '<div class="wrap"><h1>SEO de Digitalisimo</h1><p>El SEO se administra de forma nativa desde el metabox SEO de Digitalisimo en cada contenido.</p><p>Configura las reglas globales desde <a href="' . esc_url( admin_url( 'admin.php?page=digitalisimo-keyword-settings' ) ) . '">Ajustes de keywords</a> y <a href="' . esc_url( admin_url( 'admin.php?page=digitalisimo-sitemap-settings' ) ) . '">Ajustes de sitemap</a>.</p>';
		if ( isset( $_GET['seo_imported'] ) ) echo '<div class="notice notice-success is-dismissible"><p>' . sprintf( esc_html__( 'Migración completada: %1$d campos SEO importados desde %2$s. Se revisaron %3$d contenidos y nunca se sobrescribieron datos de Digitalisimo.', 'digitalisimo-integrations' ), absint( $_GET['seo_imported'] ), esc_html( sanitize_text_field( wp_unslash( $_GET['seo_source'] ?? '' ) ) ), absint( $_GET['seo_found'] ?? 0 ) ) . '</p></div>';
		echo '<hr><h2>Importar SEO desde otro plugin</h2><p>Importa los datos ya guardados aunque Rank Math o Yoast SEO estén desactivados. Se migran título SEO, meta descripción, palabra clave principal, canonical, noindex y contenido pilar/cornerstone cuando existen. Las categorías y el contenido no se modifican.</p><p><strong>Protección:</strong> Digitalisimo conserva cualquier valor que ya tenga configurado.</p>';
		foreach ( array( 'rankmath' => 'Importar desde Rank Math', 'yoast' => 'Importar desde Yoast SEO', 'all' => 'Importar desde ambos' ) as $source => $label ) {
			echo '<form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '" style="display:inline-block;margin:0 8px 8px 0"><input type="hidden" name="action" value="digitalisimo_import_seo_data"><input type="hidden" name="source" value="' . esc_attr( $source ) . '">';
			wp_nonce_field( 'digitalisimo_import_seo_data' );
			submit_button( $label, 'secondary', 'submit', false );
			echo '</form>';
		}
		echo '</div>';
	}
	/** Normaliza una lista de keywords sin escribir ni modificar los metadatos originales. */
	private static function keyword_list( $value ) {
		if ( is_array( $value ) ) $value = implode( ',', array_filter( array_map( 'strval', $value ) ) );
		return array_values( array_unique( array_filter( array_map( 'trim', preg_split( '/[,\r\n]+/', (string) $value ) ) ) ) );
	}
	/** Obtiene las keywords de cada fuente conocida: Digitalisimo, Rank Math y Yoast. */
	private static function post_keywords( $post_id ) {
		$sources = array();
		$known = array( 'Digitalisimo' => get_post_meta( $post_id, self::key( 'keywords' ), true ), 'Rank Math' => get_post_meta( $post_id, 'rank_math_focus_keyword', true ), 'Yoast SEO' => get_post_meta( $post_id, '_yoast_wpseo_focuskw', true ) );
		$yoast_multiple = get_post_meta( $post_id, '_yoast_wpseo_focuskeywords', true );
		if ( is_array( $yoast_multiple ) ) { $values = array(); foreach ( $yoast_multiple as $item ) { if ( is_array( $item ) && ! empty( $item['focuskw'] ) ) $values[] = $item['focuskw']; elseif ( is_string( $item ) ) $values[] = $item; } if ( $values ) $known['Yoast SEO'] = array_merge( self::keyword_list( $known['Yoast SEO'] ), $values ); }
		foreach ( $known as $source => $value ) { $keywords = self::keyword_list( $value ); if ( $keywords ) $sources[ $source ] = $keywords; }
		return $sources;
	}
	/** Inventario de keywords de páginas, entradas y tipos de contenido públicos, sin limitarse al editor activo. */
	public static function keywords_page() { self::content_page( 'keywords' ); }
	private static function keywords_content() {
		$posts = get_posts( array( 'post_type' => get_post_types( array( 'public' => true ), 'names' ), 'post_status' => 'any', 'posts_per_page' => -1, 'orderby' => 'title', 'order' => 'ASC' ) );
		echo '<p>Inventario de keywords guardadas en Digitalisimo, Rank Math o Yoast SEO. Incluye páginas, entradas y tipos de contenido públicos; no modifica ningún dato.</p><table class="widefat striped"><thead><tr><th>Contenido</th><th>Tipo y estado</th><th>Keyword principal</th><th>Todas las keywords</th><th>Fuente</th></tr></thead><tbody>';
		$count = 0;
		foreach ( $posts as $post ) { $sources = self::post_keywords( $post->ID ); if ( ! $sources ) continue; $all = array(); foreach ( $sources as $keywords ) $all = array_merge( $all, $keywords ); $all = array_values( array_unique( $all ) ); $count++; echo '<tr><td><a href="' . esc_url( get_edit_post_link( $post->ID ) ) . '">' . esc_html( $post->post_title ?: __( '(Sin título)', 'digitalisimo-integrations' ) ) . '</a></td><td>' . esc_html( get_post_type_object( $post->post_type )->labels->singular_name ) . '<br><small>' . esc_html( $post->post_status ) . '</small></td><td>' . esc_html( $all[0] ?? '' ) . '</td><td>' . esc_html( implode( ', ', $all ) ) . '</td><td>' . esc_html( implode( ', ', array_keys( $sources ) ) ) . '</td></tr>'; }
		if ( ! $count ) echo '<tr><td colspan="5">No se encontraron keywords en los campos de Digitalisimo, Rank Math o Yoast SEO.</td></tr>';
		echo '</tbody></table><p class="description">Se encontraron ' . absint( $count ) . ' contenidos con keywords.</p>';
	}
	public static function clusters_page() { self::content_page( 'clusters' ); }
	private static function clusters_content() { $pillars = get_posts( array( 'post_type' => array( 'post', 'page' ), 'posts_per_page' => -1, 'meta_key' => self::key( 'pillar' ), 'meta_value' => 'on' ) ); echo '<p>Relaciona contenido pilar con sus páginas secundarias.</p><ul>'; foreach ( $pillars as $pillar ) { echo '<li><strong>' . esc_html( $pillar->post_title ) . '</strong>'; $children = get_posts( array( 'post_type' => array( 'post', 'page' ), 'posts_per_page' => -1, 'meta_key' => '_related_pillar', 'meta_value' => $pillar->ID ) ); if ( $children ) { echo '<ul>'; foreach ( $children as $child ) echo '<li>' . esc_html( $child->post_title ) . '</li>'; echo '</ul>'; } echo '</li>'; } if ( ! $pillars ) echo '<li>Aún no hay contenido pilar configurado.</li>'; echo '</ul>'; }
	public static function intents_page() { self::content_page( 'intents' ); }
	private static function intents_content() { $posts = get_posts( array( 'post_type' => 'post', 'posts_per_page' => -1 ) ); echo '<p>La actualización usa el proveedor configurado en AI y Chatbot para clasificar la keyword principal.</p><form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '"><input type="hidden" name="action" value="digitalisimo_refresh_intents">'; wp_nonce_field( 'digitalisimo_refresh_intents' ); submit_button( 'Actualizar intenciones con OpenAI', 'secondary', 'submit', false ); echo '</form><table class="widefat striped"><thead><tr><th>Entrada</th><th>Keyword</th><th>Intención</th></tr></thead><tbody>'; foreach ( $posts as $post ) { $keyword = trim( explode( ',', (string) self::meta( $post->ID, 'keywords' ) )[0] ?? '' ); if ( $keyword ) echo '<tr><td>' . esc_html( $post->post_title ) . '</td><td>' . esc_html( $keyword ) . '</td><td>' . esc_html( get_post_meta( $post->ID, self::key( 'search_intent' ), true ) ) . '</td></tr>'; } echo '</tbody></table>'; }
}
