<?php
defined( 'ABSPATH' ) || exit;

class Digitalisimo_Hosting {
	const OPTION = 'digitalisimo_hosting_options';
	public static function init() { add_action( 'rest_api_init', array( __CLASS__, 'routes' ) ); add_action( 'wp_enqueue_scripts', array( __CLASS__, 'assets' ) ); add_shortcode( 'resultado_dominio', array( __CLASS__, 'result_shortcode' ) ); add_shortcode( 'digitalisimo_hosting_resultado_dominio', array( __CLASS__, 'result_shortcode' ) ); add_action( 'init', array( __CLASS__, 'cart_compatibility' ), 20 ); }
	private static function defaults() { return array( 'inherit_network'=>0, 'enabled'=>1, 'api_user'=>'', 'username'=>'', 'api_key'=>'', 'client_ip'=>'', 'domain_products'=>".com|\n.mx|\n.org|", 'form_selector'=>'.elementor-form', 'domain_field'=>'form_fields[dominio]', 'extension_field'=>'form_fields[extension]' ); }
	private static function local() { return (array) get_option( self::OPTION, array() ); }
	private static function all() { $local=self::local(); $source=( is_multisite() && !empty($local['inherit_network']) ) ? (array)get_site_option(self::OPTION,array()) : $local; return wp_parse_args($source,self::defaults()); }
	private static function origin_label() { return is_multisite() && ! empty( self::local()['inherit_network'] ) ? 'Configuración de red' : 'Este sitio'; }
	/** Contador efímero por visitante; no se guarda la IP ni se escribe en logs. */
	private static function rate_limit( $scope, $limit = 20 ) { $ip = (string) ( $_SERVER['REMOTE_ADDR'] ?? '' ); $key = 'digitalisimo_hosting_rate_' . md5( wp_salt( 'nonce' ) . '|' . sanitize_key( $scope ) . '|' . $ip ); $count = (int) get_transient( $key ); if ( $count >= $limit ) return false; set_transient( $key, $count + 1, MINUTE_IN_SECONDS ); return true; }
	private static function products() { $out=array(); foreach(preg_split('/\r\n|\r|\n/',(string)self::all()['domain_products']) as $line){$p=array_map('trim',explode('|',$line,2));if(2===count($p)&&$p[0]&&absint($p[1]))$out[strtolower($p[0])]=absint($p[1]);}return$out; }
	public static function page() { if(!current_user_can('manage_options'))return; $saved=isset($_POST['digitalisimo_hosting_save'])&&check_admin_referer('digitalisimo_hosting_save'); if($saved)self::save(false); self::form(false,$saved); }
	public static function network_page() { if(!current_user_can('manage_network_options'))return; $saved=isset($_POST['digitalisimo_hosting_network_save'])&&check_admin_referer('digitalisimo_hosting_network_save'); if($saved)self::save(true); self::form(true,$saved); }
	private static function form($network,$saved=false) { $o=$network?wp_parse_args((array)get_site_option(self::OPTION,array()),self::defaults()):self::all(); echo '<div class="wrap"><h1>Digitalisimo · Hosting'.($network?' de red':'').'</h1><p>Consulta dominios, conecta formularios Elementor y envía el dominio seleccionado al carrito WooCommerce.</p>'; if($saved)echo '<div class="notice notice-success is-dismissible"><p>Configuración '.($network?'de red ':'').'guardada.</p></div>'; echo '<form method="post">';wp_nonce_field($network?'digitalisimo_hosting_network_save':'digitalisimo_hosting_save');if(!$network&&is_multisite())echo '<p class="notice notice-info inline"><label><input type="hidden" name="hosting[inherit_network]" value="0"><input type="checkbox" name="hosting[inherit_network]" value="1" '.checked(!empty(self::local()['inherit_network']),true,false).'> <strong>Heredar configuración de la red</strong></label><br><span class="description">Valor efectivo: '.esc_html(self::origin_label()).'. Al desactivar herencia, este sitio puede personalizar su configuración.</span></p>';self::check('enabled','Activar Hosting',$o);self::field('api_user','Usuario API Namecheap',$o);self::field('username','Usuario Namecheap',$o);self::field('api_key','Clave API Namecheap',$o,'password');self::field('client_ip','IP autorizada por Namecheap',$o);self::area('domain_products','Productos por extensión',$o,'Una línea por extensión: .com|123');echo '<h2>Formulario Elementor</h2>';self::field('form_selector','Selector CSS del formulario',$o);self::field('domain_field','Campo dominio',$o);self::field('extension_field','Campo extensión',$o);echo '<p>Usa <code>[resultado_dominio]</code> donde quieres mostrar el resultado.</p>';submit_button($network?'Guardar Hosting de red':'Guardar Hosting','primary',$network?'digitalisimo_hosting_network_save':'digitalisimo_hosting_save');echo '</form></div>'; }
	private static function field($key,$label,$o,$type='text'){ $v='password'===$type?'':($o[$key]??'');echo '<p><label><strong>'.esc_html($label).'</strong><br><input class="regular-text" type="'.esc_attr($type).'" name="hosting['.esc_attr($key).']" value="'.esc_attr($v).'"></label>'.('password'===$type&&!empty($o[$key])?' <span class="description">Ya configurada; déjala vacía para conservarla.</span>':'').'</p>'; }
	private static function area($key,$label,$o,$help=''){echo '<p><label><strong>'.esc_html($label).'</strong><br><textarea class="large-text code" rows="4" name="hosting['.esc_attr($key).']">'.esc_textarea($o[$key]??'').'</textarea></label><br><span class="description">'.esc_html($help).'</span></p>';}
	private static function check($key,$label,$o){echo '<p><label><input type="hidden" name="hosting['.esc_attr($key).']" value="0"><input type="checkbox" name="hosting['.esc_attr($key).']" value="1" '.checked(!empty($o[$key]),true,false).'> <strong>'.esc_html($label).'</strong></label></p>';}
	private static function save($network) { $old=$network?(array)get_site_option(self::OPTION,array()):self::local();$in=(array)wp_unslash($_POST['hosting']??array());$o=array_merge($old,array_map('sanitize_text_field',$in));$o['enabled']=empty($in['enabled'])?0:1;if(!empty($in['api_key']))$o['api_key']=sanitize_text_field($in['api_key']);$o['domain_products']=sanitize_textarea_field($in['domain_products']??'');if($network)update_site_option(self::OPTION,$o);else update_option(self::OPTION,$o,false); }
	public static function routes(){register_rest_route('digitalisimo-hosting/v1','/check-domain',array('methods'=>'GET','callback'=>array(__CLASS__,'check_domain'),'permission_callback'=>'__return_true'));register_rest_route('digitalisimo-hosting/v1','/product-price',array('methods'=>'GET','callback'=>array(__CLASS__,'price'),'permission_callback'=>'__return_true'));}
	public static function check_domain($request){$domain=strtolower(sanitize_text_field($request->get_param('domain')));if(!preg_match('/^[a-z0-9-]+\.[a-z]{2,20}$/',$domain))return new WP_Error('invalid_domain','Dominio no válido.',array('status'=>400));if(!self::rate_limit('domain-check'))return new WP_Error('rate_limit','Demasiadas consultas. Intenta de nuevo en un minuto.',array('status'=>429));$o=self::all();if(empty($o['enabled'])||!$o['api_key']||!$o['api_user']||!$o['username']||!$o['client_ip'])return new WP_Error('not_configured','La consulta de dominios no está configurada.',array('status'=>503));$r=wp_remote_get(add_query_arg(array('ApiUser'=>$o['api_user'],'ApiKey'=>$o['api_key'],'UserName'=>$o['username'],'ClientIp'=>$o['client_ip'],'Command'=>'namecheap.domains.check','DomainList'=>$domain),'https://api.namecheap.com/xml.response'),array('timeout'=>15));if(is_wp_error($r))return$r;$xml=simplexml_load_string(wp_remote_retrieve_body($r));if(!$xml||!isset($xml->CommandResponse->DomainCheckResult))return new WP_Error('namecheap_response','Respuesta inválida de Namecheap.',array('status'=>502));return rest_ensure_response(array('available'=>'true'===strtolower((string)$xml->CommandResponse->DomainCheckResult['Available'])));}
	public static function price($request){if(!function_exists('wc_get_product'))return new WP_Error('woocommerce','WooCommerce no está activo.',array('status'=>503));$product=wc_get_product(absint($request->get_param('product_id')));if(!$product)return new WP_Error('product_not_found','Producto no encontrado.',array('status'=>404));return rest_ensure_response(array('price_html'=>$product->get_price_html(),'price'=>$product->get_price(),'currency'=>get_woocommerce_currency_symbol()));}
	public static function assets(){if(is_admin()||empty(self::all()['enabled']))return;$o=self::all();wp_enqueue_script('digitalisimo-hosting-form',DIGITALISIMO_HOSTING_URL.'assets/domain-form.js',array(),DIGITALISIMO_HOSTING_VERSION,true);wp_localize_script('digitalisimo-hosting-form','digitalisimoHosting',array('endpoint'=>rest_url('digitalisimo-hosting/v1/'),'selector'=>$o['form_selector'],'domainField'=>$o['domain_field'],'extensionField'=>$o['extension_field'],'products'=>self::products(),'cart'=>function_exists('wc_get_cart_url')?wc_get_cart_url():home_url('/cart/')));}
	public static function result_shortcode(){return '<div class="digitalisimo-hosting-result" aria-live="polite"></div>';}
	public static function cart_compatibility(){if(class_exists('Digitalisimo_Integrations_WooCommerce')||!function_exists('WC'))return;add_filter('woocommerce_add_cart_item_data',function($data){if(isset($_REQUEST['domain_name']))$data['digitalisimo_domain']=sanitize_text_field(wp_unslash($_REQUEST['domain_name']));return$data;},10);add_filter('woocommerce_get_item_data',function($data,$item){if(!empty($item['digitalisimo_domain']))$data[]=array('name'=>'Dominio','value'=>$item['digitalisimo_domain']);return$data;},10,2);add_action('woocommerce_checkout_create_order_line_item',function($item,$key,$values){if(!empty($values['digitalisimo_domain']))$item->add_meta_data('Dominio',$values['digitalisimo_domain'],true);},10,3);}
}
