<?php
namespace Digitalisimo\Tools\Elementor_Network_Templates;
defined( 'ABSPATH' ) || exit;
final class Network_Admin {
	const PAGE = 'digitalisimo-tools-elementor-templates';
	public static function init() { add_action( 'admin_menu', array( __CLASS__, 'menu' ), 90 ); add_action( 'network_admin_menu', array( __CLASS__, 'menu' ), 90 ); add_action( 'admin_post_digitalisimo_tools_save_template', array( __CLASS__, 'save_template' ) ); add_action( 'admin_post_digitalisimo_tools_sync_template', array( __CLASS__, 'sync_template' ) ); add_action( 'admin_post_digitalisimo_tools_toggle_template', array( __CLASS__, 'toggle_template' ) ); add_action( 'admin_post_digitalisimo_tools_save_settings', array( __CLASS__, 'save_settings' ) ); }
	public static function menu() { if ( ! is_multisite() ) return; $network = is_network_admin(); add_submenu_page( $network ? 'digitalisimo-network' : 'digitalisimo', 'DIGITALÍSIMO Tools', 'DIGITALÍSIMO Tools', $network ? 'manage_network_options' : 'manage_options', self::PAGE, array( __CLASS__, 'page' ) ); }
	private static function url( $args = array() ) { return add_query_arg( $args, network_admin_url( 'admin.php?page=' . self::PAGE ) ); }
	private static function guard( $action ) { if ( ! current_user_can( 'manage_network_options' ) ) wp_die( esc_html__( 'No tienes permiso para administrar la red.', 'digitalisimo-tools' ) ); check_admin_referer( $action ); }
	public static function save_settings() { self::guard( 'digitalisimo_tools_settings' ); Registry::settings(); update_site_option( Registry::SETTINGS, array( 'master_blog_id' => absint( $_POST['master_blog_id'] ?? 0 ), 'log_limit' => min( 1000, max( 10, absint( $_POST['log_limit'] ?? 200 ) ) ) ) ); wp_safe_redirect( self::url( array( 'message' => 'settings' ) ) ); exit; }
	public static function save_template() { self::guard( 'digitalisimo_tools_template' ); $uuid = sanitize_key( wp_unslash( $_POST['uuid'] ?? '' ) ); $post = absint( $_POST['master_post_id'] ?? 0 ); if ( ! $uuid ) $uuid = 'template-' . $post . '-' . wp_generate_password( 8, false, false );
		$targets = array( 'mode' => in_array( $_POST['target_mode'] ?? '', array( 'all', 'selected' ), true ) ? $_POST['target_mode'] : 'all', 'include' => array_map( 'absint', (array) ( $_POST['include'] ?? array() ) ), 'exclude' => array_map( 'absint', (array) ( $_POST['exclude'] ?? array() ) ) );
		Registry::save( array( 'uuid' => $uuid, 'master_blog_id' => Registry::master_blog_id(), 'master_post_id' => $post, 'auto_sync' => ! empty( $_POST['auto_sync'] ), 'locked' => ! empty( $_POST['locked'] ), 'collection' => sanitize_text_field( wp_unslash( $_POST['collection'] ?? '' ) ), 'targets' => $targets, 'active' => ! empty( $_POST['active'] ) ) ); wp_safe_redirect( self::url( array( 'message' => 'saved' ) ) ); exit;
	}
	public static function sync_template() { self::guard( 'digitalisimo_tools_sync' ); $uuid = sanitize_key( $_POST['uuid'] ?? '' ); $blog = absint( $_POST['blog_id'] ?? 0 ); Sync::enqueue( $uuid, $blog ); wp_safe_redirect( self::url( array( 'message' => 'queued' ) ) ); exit; }
	public static function toggle_template() { self::guard( 'digitalisimo_tools_toggle' ); $item = Registry::get( sanitize_key( $_POST['uuid'] ?? '' ) ); if ( $item ) Registry::update( $item['uuid'], array( 'active' => empty( $item['active'] ) ) ); wp_safe_redirect( self::url( array( 'message' => 'saved' ) ) ); exit; }
	public static function page() {
		if ( ! current_user_can( 'manage_network_options' ) ) { echo '<div class="wrap"><h1>DIGITALÍSIMO Tools</h1><p>Esta pantalla se administra desde la red.</p></div>'; return; }
		$tab = sanitize_key( $_GET['tab'] ?? 'elementor' );
		echo '<div class="wrap"><h1>DIGITALÍSIMO Tools</h1><p><a class="button' . ( 'elementor' === $tab ? ' button-primary' : '' ) . '" href="' . esc_url( self::url() ) . '">Plantillas Elementor</a> <a class="button' . ( 'webp' === $tab ? ' button-primary' : '' ) . '" href="' . esc_url( self::url( array( 'tab' => 'webp' ) ) ) . '">Optimizar imágenes WebP</a></p>';
		if ( 'webp' === $tab ) { \Digitalisimo\Tools\Media_WebP::page(); echo '</div>'; return; }
		$settings = Registry::settings(); $templates = array(); if ( Elementor_Adapter::available() ) { switch_to_blog( Registry::master_blog_id() ); try { $templates = Elementor_Adapter::template_posts(); } finally { restore_current_blog(); } }
		$sites = get_sites( array( 'number' => 0, 'orderby' => 'blog_id' ) ); $editing = Registry::get( sanitize_key( $_GET['edit'] ?? '' ) );
		if ( ! Elementor_Adapter::available() ) echo '<div class="notice notice-warning"><p>Elementor debe estar activo en el sitio maestro para sincronizar plantillas.</p></div>';
		if ( isset( $_GET['message'] ) ) echo '<div class="notice notice-success"><p>Configuración guardada. Las sincronizaciones grandes se procesan en cola.</p></div>';
		echo '<h2>Configuración de red</h2><form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '">'; wp_nonce_field( 'digitalisimo_tools_settings' ); echo '<input type="hidden" name="action" value="digitalisimo_tools_save_settings"><p><label>Sitio maestro <select name="master_blog_id">'; foreach ( $sites as $site ) echo '<option value="' . esc_attr( $site->blog_id ) . '"' . selected( $settings['master_blog_id'], $site->blog_id, false ) . '>' . esc_html( $site->blog_id . ' · ' . $site->domain . $site->path ) . '</option>'; echo '</select></label> <label>Conservar registros <input type="number" name="log_limit" min="10" max="1000" value="' . esc_attr( $settings['log_limit'] ) . '"></label> <button class="button">Guardar</button></p></form>';
		echo '<h2>' . esc_html( $editing ? 'Configurar plantilla global' : 'Agregar plantilla global' ) . '</h2><form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '">'; wp_nonce_field( 'digitalisimo_tools_template' ); echo '<input type="hidden" name="action" value="digitalisimo_tools_save_template"><input type="hidden" name="active" value="' . ( $editing ? ! empty( $editing['active'] ) : 1 ) . '"><p><label>Plantilla <select name="master_post_id">'; foreach ( $templates as $template ) echo '<option value="' . esc_attr( $template->ID ) . '"' . selected( $editing['master_post_id'] ?? 0, $template->ID, false ) . '>' . esc_html( $template->post_title . ' (#' . $template->ID . ')' ) . '</option>'; echo '</select></label> <label>Identificador global <input name="uuid" pattern="[a-z0-9_-]+" value="' . esc_attr( $editing['uuid'] ?? '' ) . '" placeholder="portfolio-coahuila-1000"></label> <label>Colección <input name="collection" value="' . esc_attr( $editing['collection'] ?? '' ) . '"></label><br><label><input type="checkbox" name="auto_sync" value="1"' . checked( ! empty( $editing['auto_sync'] ), true, false ) . '> Sincronizar al guardar</label> <label><input type="checkbox" name="locked" value="1"' . checked( ! empty( $editing['locked'] ), true, false ) . '> Bloquear edición local</label> <label>Destinos <select name="target_mode"><option value="all"' . selected( $editing['targets']['mode'] ?? 'all', 'all', false ) . '>Todos los sitios</option><option value="selected"' . selected( $editing['targets']['mode'] ?? '', 'selected', false ) . '>Sólo seleccionados</option></select></label></p><fieldset><legend>Seleccionar o excluir sitios</legend>';
		foreach ( $sites as $site ) { if ( absint( $site->blog_id ) === Registry::master_blog_id() ) continue; $label = $site->blog_id . ' · ' . $site->domain . $site->path; echo '<label style="display:inline-block;margin-right:16px"><input type="checkbox" name="include[]" value="' . esc_attr( $site->blog_id ) . '"' . checked( in_array( absint( $site->blog_id ), (array) ( $editing['targets']['include'] ?? array() ), true ), true, false ) . '> Incluir ' . esc_html( $label ) . '</label><label style="display:inline-block;margin-right:16px"><input type="checkbox" name="exclude[]" value="' . esc_attr( $site->blog_id ) . '"' . checked( in_array( absint( $site->blog_id ), (array) ( $editing['targets']['exclude'] ?? array() ), true ), true, false ) . '> Excluir</label><br>'; }
		echo '</fieldset><p><button class="button button-primary">' . esc_html( $editing ? 'Guardar configuración' : 'Agregar plantilla global' ) . '</button></p></form>';
		echo '<h2>Plantillas globales</h2><table class="widefat striped"><thead><tr><th>Nombre</th><th>Tipo</th><th>Sitio maestro</th><th>Post ID</th><th>Identificador</th><th>Dependencias</th><th>Destinos</th><th>Última sincronización</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>';
		foreach ( Registry::all() as $item ) { switch_to_blog( absint( $item['master_blog_id'] ) ); try { $post = get_post( $item['master_post_id'] ); $deps = Dependency_Resolver::dependencies( $item ); } finally { restore_current_blog(); } $last = ! empty( $item['last_sync'] ) ? max( $item['last_sync'] ) : 0; echo '<tr><td>' . esc_html( $post ? $post->post_title : 'No existe' ) . '</td><td>' . esc_html( $post ? get_post_meta( $post->ID, '_elementor_template_type', true ) : '' ) . '</td><td>' . esc_html( $item['master_blog_id'] ) . '</td><td>' . esc_html( $item['master_post_id'] ) . '</td><td><code>' . esc_html( $item['uuid'] ) . '</code></td><td>' . esc_html( count( $deps ) ) . '</td><td>' . esc_html( count( Registry::destinations( $item ) ) ) . '</td><td>' . esc_html( $last ? wp_date( 'Y-m-d H:i', $last ) : 'Pendiente' ) . '</td><td>' . esc_html( empty( $item['active'] ) ? 'Desactivada' : ( $last ? 'Sincronizada' : 'Pendiente' ) ) . '</td><td><a class="button" href="' . esc_url( self::url( array( 'edit' => $item['uuid'] ) ) ) . '">Configurar</a> <form style="display:inline" method="post" action="' . esc_url( network_admin_url( 'admin-post.php' ) ) . '">'; wp_nonce_field( 'digitalisimo_tools_sync' ); echo '<input type="hidden" name="action" value="digitalisimo_tools_sync_template"><input type="hidden" name="uuid" value="' . esc_attr( $item['uuid'] ) . '"><select name="blog_id"><option value="0">Todos</option>'; foreach ( Registry::destinations( $item ) as $target ) echo '<option value="' . esc_attr( $target ) . '">Sitio ' . esc_html( $target ) . '</option>'; echo '</select><button class="button">Sincronizar</button></form> <form style="display:inline" method="post" action="' . esc_url( network_admin_url( 'admin-post.php' ) ) . '">'; wp_nonce_field( 'digitalisimo_tools_toggle' ); echo '<input type="hidden" name="action" value="digitalisimo_tools_toggle_template"><input type="hidden" name="uuid" value="' . esc_attr( $item['uuid'] ) . '"><button class="button">' . esc_html( empty( $item['active'] ) ? 'Activar' : 'Desactivar sincronización' ) . '</button></form></td></tr>'; }
		echo '</tbody></table><h2>Registros</h2><table class="widefat striped"><thead><tr><th>Fecha</th><th>Plantilla</th><th>Origen</th><th>Destino</th><th>Resultado</th><th>Duración</th><th>Error</th></tr></thead><tbody>'; foreach ( array_slice( Logger::all(), 0, 30 ) as $row ) echo '<tr><td>' . esc_html( $row['date'] ) . '</td><td>' . esc_html( $row['uuid'] ) . '</td><td>' . esc_html( $row['origin'] ) . '</td><td>' . esc_html( $row['destination'] ) . '</td><td>' . esc_html( $row['result'] ) . '</td><td>' . esc_html( $row['duration'] ) . ' s</td><td>' . esc_html( $row['error'] ) . '</td></tr>'; echo '</tbody></table></div>';
	}
}
